import type { Brand } from './types';

/**
 * Batch 1 of the partner network registry.
 * Facts here were taken from each platform's own live homepage / APK listing
 * at the time of review. Where a domain was unreachable it is marked
 * `live: false` and the entry describes the platform, not uptime.
 */
export const brands1: Brand[] = [
  {
    key: 'in7gaming',
    slug: 'in7-gaming-co-review',
    name: 'IN7 Gaming',
    domain: 'in7gaming.co',
    url: 'https://www.in7gaming.co',
    live: true,
    tagline: 'The IN7 platform on its .co address, still running the same ₹777 welcome credit.',
    blurbHi: 'IN7 ka doosra official address. Wahi ₹777 bonus, wahi 48 MB APK.',
    bonus: '₹777 welcome credit',
    apkSize: '48 MB',
    version: 'Latest 2026 build',
    android: 'Android 5.0+',
    payout: 'UPI, PhonePe, Google Pay, Paytm, bank transfer',
    categories: ['Teen Patti', 'Andar Bahar', 'Slots', 'Spin wheel', 'Card games'],
    usp: 'Sign-up takes under a minute, and the welcome credit is already sitting in your balance before you\'ve opened your first table.',
    intro: [
      'If you already know IN7, [in7gaming.co](https://www.in7gaming.co) will feel instantly familiar: same lobby, same ₹777 welcome credit, same 48 MB Android package as the main build. It just runs off a second address, which is handy on the days one domain is slow to resolve in your area.',
      'What actually stands out about the IN7 lobby is how little it makes you do before you can play. No forced tutorial, no 200 MB download bolted onto the APK, no wall of promo pop-ups to click through. You install, register with a phone number, and the daily spin is already waiting on the home screen.',
      'A few things worth knowing before you install: this is a direct APK, not a Play Store listing; the ₹777 credit applies itself once your number is verified, so there\'s no promo code to hunt down; withdrawals go out to a real UPI handle instead of getting stuck in an app wallet; and the whole thing is clearly built mobile-first, so it doesn\'t feel cramped on a 5-inch screen.',
    ],
    features: [
      { title: '₹777 credited on signup', desc: 'The welcome credit applies itself the moment your number is verified. No promo code, no support ticket, no waiting around for it.' },
      { title: 'Daily spin plus a streak counter', desc: 'A free spin lands every day, and the streak bonus grows the longer you keep logging in. Miss a day and the streak resets, not your balance.' },
      { title: '48 MB install footprint', desc: 'Small enough to finish on 4G in well under a minute, and light enough that entry-level Android phones don\'t stutter running it.' },
      { title: 'Hindi and English throughout', desc: 'Interface, help text, support chat, all of it switches cleanly between Hindi and English. Sounds basic, but plenty of operators still skip this.' },
      { title: 'UPI withdrawals, not wallet credit', desc: 'Winnings leave the platform for an actual UPI handle. The minimum withdrawal is low enough that you\'re not forced to stockpile before cashing out.' },
      { title: 'Referral rewards on activity', desc: 'Refer and earn pays out on invited players actually playing, not just on the install, so the reward keeps coming instead of drying up on day one.' },
    ],
    steps: [
      'Open [in7gaming.co](https://www.in7gaming.co) in Chrome on your Android phone.',
      'Tap the download button on the hero section. The 48 MB APK starts saving right away.',
      'Chrome will flag the file type. Choose Download anyway, this warning shows up for every APK served outside the Play Store.',
      'Head to Settings, then Security or Apps, and allow installs from your browser for this one file.',
      'Tap the downloaded file, install it, then register with your mobile number and confirm the OTP. The ₹777 credit shows up on the home screen right after.',
    ],
    pros: [
      'Welcome credit applies itself, no code hunting required',
      'Small download that installs cleanly on budget Android hardware',
      'Genuinely full Hindi interface rather than a half-translated one',
      'Withdrawals land in a UPI handle instead of a locked-in app wallet',
      'The daily spin and login streak give you an actual reason to come back',
    ],
    cons: [
      'Android only, so iPhone owners are stuck with the mobile browser',
      'Not on the Play Store, which means updates are a manual job',
      'The spin wheel and streak mechanic wear thin after a few weeks',
    ],
    faqs: [
      { q: 'in7gaming.co aur in7co.in me kya difference hai?', a: 'Koi functional difference nahi hai. Dono IN7 ke official addresses hain, same lobby aur same ₹777 bonus dete hain. Jo domain aapke area me fast khule wahi use kar lo.' },
      { q: 'IN7 Gaming ka APK size kitna hai?', a: 'Lagbhag 48 MB. 4G par ek minute se kam me download ho jaata hai aur entry-level Android phones par bhi theek-thaak chalta hai.' },
      { q: 'Bonus claim karne ke liye promo code chahiye?', a: 'Nahi. Number verify hote hi ₹777 credit apne aap apply ho jaata hai, koi code enter karne ki zarurat nahi.' },
      { q: 'Withdrawal kitni der me aata hai?', a: 'UPI withdrawals normally minutes me settle ho jaate hain. Pehli baar KYC verify karna padta hai, uske baad process kaafi fast ho jaata hai.' },
      { q: 'Play Store par IN7 Gaming milega?', a: 'Nahi. Real-money gaming apps Play Store policy me allowed nahi hain, isliye APK official site se hi download karna padta hai.' },
      { q: 'iPhone par chalega?', a: 'Native iOS app abhi nahi hai. iPhone users mobile browser se site khol sakte hain, lekin experience Android app jitna smooth nahi milega.' },
    ],
    alternatives: ['xx7', 'ie777', 'fn7', 'ind9'],
    anchors: ['IN7 Gaming', 'in7gaming.co', 'the IN7 Gaming lobby', 'IN7 Gaming APK', 'IN7 on its .co address'],
  },

  {
    key: 'xx7',
    slug: 'xx7-game-review',
    name: 'XX7 Game',
    domain: 'xx7game.com',
    url: 'https://xx7game.com',
    live: true,
    tagline: 'A 30 MB package that leans hard into slots and fishing arcade modes.',
    blurbHi: 'Sabse halka APK. Slots aur fishing games ka bada collection.',
    bonus: 'Welcome bonus on first registration',
    apkSize: '30 MB',
    version: '2026 release',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Slots', 'Fishing arcade', 'Card games', 'Lucky spin'],
    usp: 'At 30 MB it\'s the smallest install in this entire network, and somehow still ships the widest slots catalogue.',
    intro: [
      'When someone\'s phone is already full, [XX7 Game](https://xx7game.com) is the one I point them to. The Android package comes in at 30 MB, roughly a third of what a typical app in this category asks for, and the compression doesn\'t cost the catalogue anything.',
      'The lobby is built around two pillars. Slots are the obvious one, with a large reel collection running from classic three-reel layouts up through multi-line themed machines. The second is fishing arcade, a category that barely exists on Indian gaming apps outside a handful of platforms, and XX7 actually gives it real shelf space instead of three token titles thrown in to check a box.',
      'Everything about the build reads as deliberately aimed at the Indian market. Rupee denominations everywhere, UPI as the default cash-out route rather than an afterthought, load times tuned for patchy mobile data instead of assuming you\'re on Wi-Fi.',
    ],
    features: [
      { title: '30 MB download', desc: 'The lightest install of anything covered on this site. Worth knowing if your phone only has 16 GB or 32 GB of storage.' },
      { title: 'Deep slots catalogue', desc: 'Classic three-reel machines through to multi-line themed reels, grouped sensibly so you\'re not scrolling past the same game five times.' },
      { title: 'Fishing arcade modes', desc: 'Fast, target-based arcade play with a rhythm that\'s genuinely different from card games. Few Indian apps treat it as a first-class category the way XX7 does.' },
      { title: 'Fast UPI cash-outs', desc: 'Withdrawal requests go to UPI and clear quickly once your account is verified.' },
      { title: 'Built for Indian data speeds', desc: 'Assets stream in progressively, so the lobby is usable before every graphic has finished loading. Matters more than you\'d think on 4G.' },
      { title: 'Welcome bonus on registration', desc: 'A first-registration bonus lands in your balance so you can try the reels before deciding whether to deposit a rupee.' },
    ],
    steps: [
      'Visit [xx7game.com](https://xx7game.com) on an Android phone.',
      'Tap the download button. The 30 MB file saves in seconds on most connections.',
      'Accept the browser warning about downloading an APK.',
      'Enable install permission for your browser under Settings, then Security.',
      'Install, register with your mobile number, verify the OTP and claim the welcome bonus.',
    ],
    pros: [
      'Smallest install in the category, roughly 30 MB',
      'Slots collection is genuinely broad, not padded with lookalike clones',
      'Fishing arcade is properly built out here, not just decorative',
      'Loads usefully fast on 4G, no need to wait for Wi-Fi',
      'Rupee-first interface with UPI withdrawals as the default',
    ],
    cons: [
      'Card game selection is thinner than the slots-heavy focus suggests',
      'No iOS build at all',
      'Fishing arcade takes some getting used to if you\'ve only ever played card games',
    ],
    faqs: [
      { q: 'XX7 Game APK ka size kitna hai?', a: 'Lagbhag 30 MB. Is network me sabse chhota download yahi hai, isliye kam storage wale phones ke liye best option hai.' },
      { q: 'XX7 me kaunse games hain?', a: 'Mainly slots aur fishing arcade. Iske saath card games aur lucky spin bhi milte hain, lekin slots ka collection sabse bada hai.' },
      { q: 'Fishing game kaise khelte hain?', a: 'Screen par moving targets aate hain aur aap unhe shoot karte ho. Card games se bilkul different rhythm hai, thoda practice lagta hai lekin seekhna easy hai.' },
      { q: 'XX7 withdrawal UPI par aata hai?', a: 'Haan. Withdrawal request UPI par jaati hai aur account ek baar verify hone ke baad jaldi clear ho jaati hai.' },
      { q: 'XX7 Game safe hai?', a: 'Site HTTPS par chalti hai aur APK official domain xx7game.com se hi milta hai. Third-party mirror sites se download mat karo, wahi asli risk hai.' },
      { q: 'Purana Android phone chalega?', a: 'Android 5.0 aur usse upar chalta hai. 30 MB size ki wajah se purane aur entry-level phones par bhi performance theek rehti hai.' },
    ],
    alternatives: ['mast79', 'in7gaming', 'inr360', 'is7'],
    anchors: ['XX7 Game', 'xx7game.com', 'the XX7 APK', 'XX7 Game download', 'XX7'],
  },

  {
    key: 'ie777',
    slug: 'ie777-game-review',
    name: 'IE777 Game',
    domain: 'ie777s.com',
    url: 'https://ie777s.com',
    live: true,
    tagline: 'A million-plus install base built largely on its refer and earn structure.',
    blurbHi: '1M+ downloads. Refer and earn system iska sabse strong part hai.',
    bonus: 'Signup bonus plus referral earnings',
    apkSize: 'Approx 40 MB',
    version: 'Latest 2026 version',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Slots', 'Card games', 'Lottery', 'Live tables'],
    usp: 'The referral programme is the most developed of any platform in this network, and it\'s the actual reason this one reached a million installs.',
    intro: [
      'IE777\'s growth story is unusual for this category, because it isn\'t really about the games at all. It\'s about referrals. [IE777](https://ie777s.com) crossed a million downloads on the back of a refer and earn structure that pays out on downstream activity rather than a flat one-time bounty, and that changes how people actually use it.',
      'The lobby itself is conventional in the best sense: slots, card games, lottery draws and live table formats, all organised sensibly, all in rupees. Anyone who\'s used a platform in this space already knows how to navigate it. The install is around 40 MB, and the Android package is served directly from the site.',
      'The site is also worth a look purely as a reference. Its download page walks through the Android install-permission flow step by step with screenshots, more care than most operators put into the one part of the process that actually confuses new users.',
    ],
    features: [
      { title: 'Multi-level refer and earn', desc: 'Referral income keeps coming as invited players stay active, rather than stopping at the install. This is the platform\'s defining feature, full stop.' },
      { title: 'Over a million installs', desc: 'A user base large enough that lobbies fill quickly and multiplayer table formats don\'t sit empty.' },
      { title: 'Slots, cards, lottery and live tables', desc: 'Four distinct categories rather than one padded out to look like four. Lottery draws run on a fixed schedule you can actually plan around.' },
      { title: 'Documented install flow', desc: 'The official download page shows the Android unknown-sources permission flow with screenshots, which cuts down on failed installs.' },
      { title: 'Signup bonus', desc: 'A welcome bonus lands on registration, so there\'s room to look around the lobby before committing any money.' },
      { title: 'Rupee denominations throughout', desc: 'No currency-conversion guesswork anywhere. Stakes, balances and withdrawals are all in rupees.' },
    ],
    steps: [
      'Open [ie777s.com](https://ie777s.com) on your Android device.',
      'Tap the APK download button in the hero area.',
      'Confirm the download when Chrome flags the file.',
      'Follow the on-page permission guide, or go to Settings, Security, and allow your browser to install apps.',
      'Install, register, verify your number, and claim the signup bonus. Grab your referral link from the profile section if you plan on inviting anyone.',
    ],
    pros: [
      'Best developed referral programme anywhere in this network',
      'Large install base keeps multiplayer tables populated',
      'Four genuinely distinct game categories, not one stretched thin',
      'Install instructions on the site are clear and screenshot-led',
      'Scheduled lottery draws give the week some structure',
    ],
    cons: [
      'The referral-heavy design means a fair bit of promotional messaging inside the app',
      'APK runs a little larger than the lightest options in this category',
      'Android only',
    ],
    faqs: [
      { q: 'IE777 ka refer and earn kaise kaam karta hai?', a: 'Aapko profile section me ek referral link milta hai. Jo log us link se join karke khelte hain, unki activity par aapko commission milta rehta hai, sirf install par one-time payment nahi hota.' },
      { q: 'IE777 APK kahan se download karein?', a: 'Sirf official site ie777s.com se. Download page par install steps screenshots ke saath diye hain, wahi follow karo.' },
      { q: '555casino.in bhi IE777 hai?', a: 'Filhaal 555casino.in ka traffic IE777 par redirect hota hai, isliye dono ek hi platform par le jaate hain. Aage 555 Casino apna separate lobby launch kar raha hai.' },
      { q: 'IE777 me kaunse games hain?', a: 'Slots, card games, lottery draws aur live table formats. Lottery draws fixed schedule par chalte hain.' },
      { q: 'IE777 game real hai ya fake?', a: 'Platform 1M+ downloads ke saath actively chal raha hai aur UPI withdrawals process karta hai. Risk sirf tab hai jab aap kisi third-party mirror se APK download karo.' },
      { q: 'Bonus withdraw kar sakte hain directly?', a: 'Signup bonus normally playthrough ke baad withdrawable hota hai. Exact condition app ke promotions section me likhi hoti hai, install ke baad wahan check kar lo.' },
    ],
    alternatives: ['c555', 'raja7', 'mmy', 'xx7'],
    anchors: ['IE777 Game', 'ie777s.com', 'the IE777 APK', 'IE777', 'IE777 game download'],
  },

  {
    key: 'c555',
    slug: '555-casino-review',
    name: '555 Casino',
    domain: '555casino.in',
    url: 'https://555casino.in',
    live: false,
    tagline: 'A casino-first lobby: live tables, Andar Bahar and roulette rather than arcade modes.',
    blurbHi: 'Casino-style lobby. Live tables, Andar Bahar aur roulette par focus.',
    bonus: '₹555 welcome offer',
    apkSize: 'Approx 42 MB',
    version: 'Launch build',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Live casino', 'Andar Bahar', 'Teen Patti', 'Roulette', 'Slots'],
    usp: 'The only platform in this network built casino-first, with live dealer tables as the centrepiece instead of an add-on.',
    intro: [
      '[555 Casino](https://555casino.in) sits apart from the rest of this network because it isn\'t an arcade app with a casino section bolted on. It\'s the reverse. Live dealer tables, Andar Bahar, Teen Patti and roulette are the main event, and the slots catalogue plays a supporting role.',
      'That matters if you actually prefer table games. On most Indian gaming apps, table formats amount to three or four titles buried under a wall of reels. Here the lobby opens on tables, the stake tiers are structured for table play, and the ₹555 welcome offer is sized to buy you a handful of real hands rather than a couple of spins.',
      'At the time of writing, 555casino.in points to the IE777 platform while its own lobby is being finished, so typing the address today still lands you on a working gaming app either way. The dedicated 555 Casino build is the one worth watching if live tables are your reason for installing in the first place.',
    ],
    features: [
      { title: 'Live dealer tables first', desc: 'Real dealer streams for the main table formats rather than software-only versions, the whole reason to pick a casino-first app over anything else here.' },
      { title: 'Andar Bahar and Teen Patti done properly', desc: 'Multiple stake tiers and table sizes for both, instead of one table you either fit into or don\'t.' },
      { title: 'Roulette', desc: 'European and standard layouts, a format most Indian gaming apps skip entirely.' },
      { title: '₹555 welcome offer', desc: 'Sized deliberately for table play, where a handful of hands costs more than a handful of slot spins.' },
      { title: 'Slots as the support act', desc: 'A reel catalogue is there for when you want a break, but it\'s clearly not what the lobby is organised around.' },
      { title: 'UPI cash-out', desc: 'Withdrawals settle to UPI handles and bank accounts in rupees.' },
    ],
    steps: [
      'Open [555casino.in](https://555casino.in) on your Android phone.',
      'Tap the download button for the current build.',
      'Approve the APK download when your browser asks.',
      'Allow installs from your browser in Settings, then Security.',
      'Install, register with your number, verify the OTP and claim the ₹555 welcome offer before you sit at a table.',
    ],
    pros: [
      'Genuinely casino-first, not an arcade app with tables tacked on',
      'Live dealer streams cover the main formats',
      'Carries roulette, which most competitors here skip entirely',
      'Multiple stake tiers, so low and mid stakes both get real tables',
      'Welcome offer is sized for table play, not for spins',
    ],
    cons: [
      'The dedicated lobby is still rolling out, so the address currently forwards elsewhere',
      'Live tables need a stable connection, so patchy 4G is genuinely a problem',
      'Slots catalogue is smaller than what slots-led competitors offer',
    ],
    faqs: [
      { q: '555casino.in abhi kaam kar raha hai?', a: 'Abhi address IE777 platform par forward hota hai jab tak 555 Casino ka apna lobby live nahi hota. Type karne par aapko ek working gaming app to milega hi.' },
      { q: '555 Casino me kya khaas hai?', a: 'Yeh casino-first app hai. Live dealer tables, Andar Bahar, Teen Patti aur roulette main focus hain, slots side me hain. Baaki apps me ulta hota hai.' },
      { q: '₹555 bonus kaise milta hai?', a: 'Registration aur number verification ke baad welcome offer apply hota hai. Table games me stake zyada lagta hai isliye bonus bhi usi hisaab se rakha gaya hai.' },
      { q: 'Roulette milega?', a: 'Haan, roulette 555 Casino ke lobby ka part hai. Indian gaming apps me yeh format kam milta hai.' },
      { q: 'Live tables ke liye internet kitna chahiye?', a: 'Live dealer streams ke liye stable connection zaruri hai. Weak 4G par stream buffer karega, isliye Wi-Fi ya strong signal better rehta hai.' },
      { q: 'Minimum deposit kitna hai?', a: 'Table games ke liye entry tiers rakhe gaye hain taaki low stake players bhi khel sakein. Exact figure app ke deposit page par install ke baad dikhta hai.' },
    ],
    alternatives: ['ie777', 'in7gaming', 's1', 'mast179'],
    anchors: ['555 Casino', '555casino.in', 'the 555 Casino lobby', '555 Casino APK', '555casino'],
  },

  {
    key: 'g112',
    slug: '112-game-apk-guide',
    name: '112 Game',
    domain: '112gameapps.com',
    url: 'https://112gameapps.com',
    live: true,
    tagline: 'Less a lobby, more the best written install and troubleshooting guide in this space.',
    blurbHi: 'Install aur login problems ka sabse detailed guide. v2.0.2, 35 MB.',
    bonus: 'Platform dependent',
    apkSize: '35 MB',
    version: '2.0.2',
    android: 'Android 5.0+',
    payout: 'UPI',
    categories: ['Install guide', 'Login troubleshooting', 'Version tracking'],
    usp: 'It\'s the only site in this network that documents what to do when the install or the OTP fails, which is where most new players actually get stuck.',
    intro: [
      'Instead of another hero banner and a download button, [112gameapps.com](https://112gameapps.com) does something genuinely different from everything else in this network: it\'s a full install, login and troubleshooting guide for the 112 Game APK on Android.',
      'Here\'s why that matters. Almost nobody in this category writes about failure states. Every operator explains how to download an APK. Almost none explain what to do when the install gets blocked by Play Protect, when the OTP never shows up, when the app crashes on first launch, or when a version mismatch stops the login screen from loading. This site covers all four.',
      'It also does the unglamorous, boring thing of publishing hard version facts: version 2.0.2, 35 MB, Android 5.0 and above. Being able to check whether the build on your phone matches the current release is a small thing, but it saves a lot of pointless reinstalling.',
    ],
    features: [
      { title: 'OTP failure troubleshooting', desc: 'What to actually do when the verification SMS doesn\'t arrive, which is the single most common reason people abandon a registration halfway.' },
      { title: 'Play Protect and blocked install fixes', desc: 'Step by step handling of the Android warnings that stop APK installs, without pretending those warnings are meaningless.' },
      { title: 'Published version facts', desc: 'Version 2.0.2, 35 MB, Android 5.0+. You get to check your build against the current one instead of guessing.' },
      { title: 'Login problem walkthroughs', desc: 'Covers stuck login screens, session timeouts and password-reset paths, roughly in order of how often they actually happen.' },
      { title: 'Compatibility notes', desc: 'Clear about which Android versions are supported, rather than claiming universal compatibility and hoping.' },
      { title: '18+ notice front and centre', desc: 'The age restriction is stated plainly instead of buried in a footer somewhere, and that\'s worth crediting.' },
    ],
    steps: [
      'Open [112gameapps.com](https://112gameapps.com) and read the compatibility section first to confirm your Android version.',
      'Follow the download steps on the page. The current build is 35 MB.',
      'If the install is blocked, use the Play Protect section rather than repeatedly retrying the file.',
      'Register and verify. If the OTP doesn\'t arrive, work through the OTP troubleshooting section instead of hammering resend ten times.',
      'Bookmark the version section so you can check your build number the next time something stops working.',
    ],
    pros: [
      'Only site here that actually documents install and login failure states',
      'Publishes real version, size and compatibility numbers',
      'The OTP troubleshooting page alone is the most useful thing in this network',
      'Honest about what the Android security warnings actually mean',
      'Age restriction stated clearly, right up front',
    ],
    cons: [
      'It\'s a guide site, so there\'s no lobby to browse on the page itself',
      'Less useful once you\'re past setup and already playing',
      'Bonus details depend on the platform build rather than being fixed here',
    ],
    faqs: [
      { q: '112 Game APK ka current version kaunsa hai?', a: 'Version 2.0.2, size 35 MB, aur Android 5.0 ya usse upar chahiye. Ye numbers site par published hain, guess karne ki zarurat nahi.' },
      { q: 'OTP nahi aa raha, kya karein?', a: '112gameapps.com par ek pura OTP troubleshooting section hai. Baar baar resend dabane se kuch nahi hota, us section ke steps follow karo.' },
      { q: 'Install block ho raha hai, Play Protect warning aa rahi hai. Kya karein?', a: 'Yeh warning har APK par aati hai jo Play Store ke bahar se aata hai. Site par iska step-by-step fix diya hua hai, wahi follow karo.' },
      { q: '112 Game app kis kaam ka hai?', a: '112gameapps.com khud ek install aur troubleshooting guide hai 112 Game APK ke liye. Setup, login aur version issues yahan cover hote hain.' },
      { q: 'App crash ho raha hai first launch par. Fix kya hai?', a: 'Usually version mismatch ya incomplete download ki wajah se hota hai. Site ke version section me apna build check karo aur zarurat pade to clean reinstall karo.' },
      { q: 'Kya 112 Game Play Store par hai?', a: 'Nahi. Is category ke apps Play Store policy me allowed nahi hote, isliye APK direct download hi hota hai. Isi wajah se install guide itna useful hai.' },
    ],
    alternatives: ['is7', 'mmy', 'x89', 'in7gaming'],
    anchors: ['112 Game', '112gameapps.com', 'the 112 Game APK guide', '112 Game install guide', '112gameapps'],
  },

  {
    key: 'inr360',
    slug: '360inr-game-review',
    name: '360INR Game',
    domain: '360-inr.com',
    url: 'https://360-inr.com',
    live: true,
    tagline: 'Two million players, a ₹200 instant bonus, and a skill-based framing throughout.',
    blurbHi: '2M+ players. ₹200 instant bonus registration ke turant baad.',
    bonus: '₹200 instant cash bonus',
    apkSize: 'Approx 38 MB',
    version: 'Latest 2026 build',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Skill games', 'Card games', 'Slots', 'Prediction'],
    usp: 'The ₹200 bonus is credited instantly on registration rather than after a deposit, a meaningfully different offer from what most competitors run.',
    intro: [
      'Register, and ₹200 lands in your balance instantly. That\'s the clearest offer of any platform in this network. Not after a first deposit, not after clearing a playthrough threshold, not as bonus credit locked to one game. [360INR Game](https://360-inr.com) is worth understanding for that distinction alone, because most welcome offers in this category are deposit-matched, meaning they actually cost you money to unlock.',
      'The platform positions itself around skill-based play and carries roughly two million players. The catalogue mixes card games, slots and prediction formats, and the interface runs on rupee stakes with UPI cash-outs, which by now is table stakes for anything serious in the Indian market.',
      'The site itself is one of the better built ones covered here, with a clean app information table, real screenshots, and a "more games to download" section instead of pretending it\'s the only app you\'ll ever need. That last part is unusually honest for the category.',
    ],
    features: [
      { title: '₹200 credited on registration', desc: 'No deposit needed to trigger it. Probably the single strongest reason to try this platform before the others on this list.' },
      { title: 'Around two million players', desc: 'Large enough that multiplayer formats actually have opponents and leaderboards mean something.' },
      { title: 'Skill-based framing', desc: 'The catalogue leans toward formats where decisions matter more than pure chance, and the platform is upfront about that.' },
      { title: 'Published app information table', desc: 'Size, version and requirements are laid out right on the homepage, not something you discover after installing.' },
      { title: 'Real screenshots', desc: 'The gallery shows the actual lobby, not rendered mockups, so you know exactly what you\'re installing.' },
      { title: 'Fast UPI withdrawals', desc: 'Cash-outs settle to UPI in rupees once your account is verified.' },
    ],
    steps: [
      'Open [360-inr.com](https://360-inr.com) on Android and check the app information table for your device compatibility.',
      'Tap the download button for the current APK.',
      'Approve the download when the browser warns about the file.',
      'Allow installs from your browser under Settings, then Security.',
      'Install, register, verify your number, and the ₹200 bonus appears in your balance immediately.',
    ],
    pros: [
      'Instant ₹200 bonus, no deposit requirement attached',
      'Two million player base means lobbies actually fill up',
      'App size, version and requirements published openly',
      'Screenshots show the real lobby, not staged renders',
      'Site links out to alternatives instead of pretending to be the only option',
    ],
    cons: [
      'The hyphen in the domain makes the address easy to mistype',
      'Prediction formats sit a little uneasily with the skill-based positioning',
      'Android only',
    ],
    faqs: [
      { q: '360INR ka ₹200 bonus deposit ke baad milta hai?', a: 'Nahi, registration ke turant baad milta hai. Deposit ki koi condition nahi hai, isliye yeh offer baaki deposit-match bonuses se better hai.' },
      { q: '360INR Game download kaise karein?', a: '360-inr.com kholo, download button dabao, browser warning accept karo, aur Settings me apne browser ko install permission do. Address me hyphen dhyan se type karo.' },
      { q: '360 INR game real hai?', a: 'Platform 2M+ players ke saath chal raha hai aur UPI withdrawals process karta hai. App size, version aur requirements site par openly published hain, jo ek accha sign hai.' },
      { q: '360INR me kaunse games hain?', a: 'Card games, slots aur prediction formats. Platform khud ko skill-based games ke around position karta hai.' },
      { q: 'Withdrawal minimum kitna hai?', a: 'Withdrawal UPI par jaata hai. Minimum amount app ke wallet section me dikhta hai, aur pehli withdrawal se pehle account verify karna padta hai.' },
      { q: 'Domain 360-inr.com hai ya 360inr.com?', a: 'Official address 360-inr.com hai, hyphen ke saath. Bina hyphen wale addresses official nahi hain, wahan se download mat karo.' },
    ],
    alternatives: ['fn7', 'ind9', 'xx7', 'x89'],
    anchors: ['360INR Game', '360-inr.com', 'the 360INR APK', '360INR', '360 INR game'],
  },

  {
    key: 'fn7',
    slug: 'fn7-game-review',
    name: 'FN7 Game',
    domain: 'fn7gameng.com',
    url: 'https://fn7gameng.com',
    live: true,
    tagline: 'The most thoroughly documented platform here: login, register, spin, bonus and withdrawal all covered.',
    blurbHi: '₹200 bonus. Login se withdrawal tak har step ka guide.',
    bonus: '₹200 welcome bonus',
    apkSize: 'Approx 40 MB',
    version: 'Latest APK',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Spin games', 'Card games', 'Slots', 'Skill games'],
    usp: 'Every stage of the player journey has its own documented section, which makes this the easiest platform here to start on without help.',
    intro: [
      'Most platforms in this category publish a download button and a bonus figure and leave you to work out the rest yourself. [FN7 Game](https://fn7gameng.com) wins on documentation instead: a written section for the login flow, one for registration, one for the spin game, one for the bonus structure and one for the withdrawal process, all sitting right there on the front page.',
      'The ₹200 welcome bonus is credited on signup. The spin game is the mechanic FN7 is best known for, a daily spin that gives you a reason to open the app without spending anything, and one of the more generous versions of that pattern anywhere in this network.',
      'The catalogue itself covers card games, slots and skill formats. Nothing exotic there, but the spin layer sitting on top gives the daily loop a shape that platforms without it just lack. If you\'re new to this whole category and want the shallowest learning curve, this is the one to try first.',
    ],
    features: [
      { title: 'Daily spin and win', desc: 'The mechanic FN7 is known for. A free daily spin that gives you something to do without depositing a rupee.' },
      { title: '₹200 welcome bonus', desc: 'Credited on signup, so you get a few rounds in before deciding whether to fund the account at all.' },
      { title: 'Documented login and register flows', desc: 'Both processes get their own written guide, which cuts out most of the confusion new players run into.' },
      { title: 'Documented withdrawal process', desc: 'The cash-out flow is explained before you even sign up, not something you have to discover when you try to leave.' },
      { title: 'Card games, slots and skill formats', desc: 'A conventional catalogue, competently organised, with the spin layer adding daily structure on top of it.' },
      { title: 'Hindi coverage in the guides', desc: 'The written sections cover common Hindi search phrasings, so the guidance is actually findable in the language players search in.' },
    ],
    steps: [
      'Open [fn7gameng.com](https://fn7gameng.com) on Android.',
      'Read the register section, then tap the download button for the latest APK.',
      'Accept the APK download warning in your browser.',
      'Allow installs from your browser under Settings, then Security.',
      'Install, register, verify your number, claim the ₹200 bonus and take your first daily spin.',
    ],
    pros: [
      'Best documented player journey of any platform in this network',
      '₹200 bonus on signup, no deposit trigger attached',
      'Daily spin gives a genuine reason to return without spending',
      'Withdrawal process explained before you commit anything',
      'Guides cover Hindi search phrasings, not just English',
    ],
    cons: [
      'The domain spelling, fn7gameng.com, is easy to get wrong',
      'Catalogue is conventional rather than distinctive',
      'Android only',
    ],
    faqs: [
      { q: 'FN7 game kya hai?', a: 'FN7 ek Android gaming platform hai jisme card games, slots aur skill formats hain, aur uske upar ek daily spin game chalta hai. ₹200 welcome bonus signup par milta hai.' },
      { q: 'FN7 game kaise download kare?', a: 'fn7gameng.com kholo, latest APK download karo, browser warning accept karo, aur Settings me install permission do. Domain spelling dhyan se: fn7gameng.com.' },
      { q: 'FN7 spin game kaise kaam karta hai?', a: 'Har din ek free spin milta hai. Isse aap bina paisa lagaye rewards jeet sakte ho. Yahi FN7 ka sabse popular feature hai.' },
      { q: 'FN7 withdrawal kaise karte hain?', a: 'App ke wallet section se withdrawal request lagti hai aur UPI par settle hoti hai. Poora process site ke withdrawal section me pehle se likha hua hai.' },
      { q: 'FN7 real or fake?', a: 'Platform live hai, bonus credit karta hai aur withdrawal process documented hai. Sirf official domain fn7gameng.com se hi APK lena, mirror sites se nahi.' },
      { q: 'FN7 login nahi ho raha, kya karein?', a: 'Site par login ka dedicated section hai jisme common issues cover hain. Pehle wahan dekho, phir bhi na chale to in-app support se contact karo.' },
    ],
    alternatives: ['inr360', 'ind9', 'mmy', 'in7gaming'],
    anchors: ['FN7 Game', 'fn7gameng.com', 'the FN7 APK', 'FN7', 'FN7 game download'],
  },
];
