import type { Brand } from './types';

/** Batch 2 of the partner network registry. */
export const brands2: Brand[] = [
  {
    key: 'ind9',
    slug: 'ind9-game-review',
    name: 'IND9 Game',
    domain: 'ind9game.com',
    url: 'https://ind9game.com',
    live: true,
    tagline: 'One app instead of five: 100+ titles under a single login and a single wallet.',
    blurbHi: '100+ games ek hi app me. ₹199 welcome bonus.',
    bonus: '₹199 welcome bonus',
    apkSize: 'Approx 45 MB',
    version: 'Latest IND9 APK',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Card games', 'Slots', 'Arcade', 'Prediction', 'Lottery'],
    usp: 'It is explicitly built as the answer to having five gaming apps installed, each with its own wallet and its own minimum withdrawal.',
    intro: [
      '[IND9 Game](https://ind9game.com) makes an argument the rest of this category mostly avoids: that having five gaming apps on your phone is the actual problem. Five apps means five wallets, five minimum withdrawal thresholds, five sets of KYC, and money stranded in balances too small to cash out. IND9 puts 100+ titles behind one login and one wallet.',
      'Whether that argument lands depends on how you play. If you use one platform and stick to two or three games, the pitch is irrelevant. If you have been collecting apps chasing signup bonuses, it is the most sensible thing on this page, because consolidated balance is the difference between money you can withdraw and money you cannot.',
      'The welcome bonus is ₹199, the download is around 45 MB, and the catalogue spans card games, slots, arcade titles, prediction formats and lottery draws. The site also publishes player testimonials and a category breakdown, so you can see what you are getting before installing.',
    ],
    features: [
      { title: '100+ games, one wallet', desc: 'The core pitch. Your balance is shared across every category instead of being fragmented across separate apps.' },
      { title: '₹199 welcome bonus', desc: 'Credited on registration so you can sample several categories before deciding where to spend time.' },
      { title: 'Five distinct categories', desc: 'Cards, slots, arcade, prediction and lottery. Enough breadth that the single-app pitch actually holds up.' },
      { title: 'One KYC for everything', desc: 'Verify once and every game in the catalogue is unlocked, rather than repeating verification per platform.' },
      { title: 'Published category breakdown', desc: 'The site explains what sits in each category rather than just claiming a headline title count.' },
      { title: 'UPI withdrawals from a single balance', desc: 'Because everything shares one wallet, you hit the withdrawal minimum faster than you would across several apps.' },
    ],
    steps: [
      'Open [ind9game.com](https://ind9game.com) on your Android phone.',
      'Tap the download button to save the IND9 APK, around 45 MB.',
      'Confirm the download when your browser flags the file type.',
      'Enable install permission for your browser in Settings, then Security.',
      'Install, register, verify your number and the ₹199 welcome bonus is credited. Complete KYC once to unlock withdrawals across the whole catalogue.',
    ],
    pros: [
      'Single wallet across 100+ titles, which genuinely solves stranded balances',
      'One KYC instead of one per platform',
      'Five real categories rather than a padded title count',
      '₹199 bonus on registration with no deposit trigger',
      'Site publishes an honest category breakdown',
    ],
    cons: [
      'A larger install than single-category apps at around 45 MB',
      'Breadth means no single category is as deep as a specialist app',
      'Android only',
    ],
    faqs: [
      { q: 'IND9 me sach me 100+ games hain?', a: 'Haan, catalogue paanch categories me bata hua hai: cards, slots, arcade, prediction aur lottery. Site par har category ka breakdown diya hua hai.' },
      { q: 'Ek wallet ka fayda kya hai?', a: 'Paanch alag apps me aapka paisa paanch alag balances me bat jaata hai, aur har ek ka apna minimum withdrawal hota hai. IND9 me sab ek wallet me rehta hai isliye withdrawal minimum jaldi cross hota hai.' },
      { q: 'IND9 ka bonus kitna hai?', a: '₹199 welcome bonus registration ke baad milta hai. Deposit karne ki condition nahi hai.' },
      { q: 'KYC har game ke liye alag karni padti hai?', a: 'Nahi. Ek baar KYC complete karo aur poora catalogue unlock ho jaata hai.' },
      { q: 'IND9 Game download size kitna hai?', a: 'Around 45 MB. Single-category apps se thoda bada hai kyunki catalogue kaafi broad hai.' },
      { q: 'ind9game.com aur ind9win.com me kya farq hai?', a: 'Dono IND9 ke addresses hain. ind9game.com download aur catalogue par focus karta hai, ind9win.com withdrawal aur winnings side par. Account dono jagah same rehta hai.' },
    ],
    alternatives: ['ind9win', 'fn7', 'inr360', 'mmy'],
    anchors: ['IND9 Game', 'ind9game.com', 'the IND9 APK', 'IND9', 'IND9 game download'],
  },

  {
    key: 'ind9win',
    slug: 'ind9-win-withdrawal-guide',
    name: 'IND9 Win',
    domain: 'ind9win.com',
    url: 'https://ind9win.com',
    live: false,
    tagline: 'The IND9 companion address focused on winnings, withdrawal limits and payout timing.',
    blurbHi: 'IND9 ka withdrawal side. Payout timing aur limits yahan cover hote hain.',
    bonus: 'Shared with the IND9 account',
    apkSize: 'Approx 45 MB',
    version: 'Latest IND9 APK',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Withdrawals', 'Winnings tracking', 'Payout guides'],
    usp: 'It covers the half of the experience operators usually hide: how much you can take out, how fast, and what blocks it.',
    intro: [
      '[IND9 Win](https://ind9win.com) exists to cover the part of the player journey that almost every gaming site in this category skips. Not how to deposit, not how to claim a bonus, but how to get money out: withdrawal minimums, daily limits, verification requirements and realistic payout timing.',
      'That focus is more valuable than it sounds. The most common complaint about any platform in this space is not that the games are unfair, it is that a player deposited without knowing the withdrawal threshold and then found their balance sitting below it. Publishing those numbers before signup prevents the entire problem.',
      'The account is shared with [ind9game.com](https://ind9game.com), so this is not a second platform to register on. Same login, same wallet, same catalogue of 100+ titles. This address is simply the reference you use when you want to know what happens at cash-out.',
    ],
    features: [
      { title: 'Withdrawal minimums stated up front', desc: 'Published before registration rather than discovered when you first try to cash out.' },
      { title: 'Realistic payout timing', desc: 'Honest ranges for how long UPI settlement actually takes, including the slower first withdrawal after KYC.' },
      { title: 'KYC requirements explained', desc: 'What documents are needed and why the first withdrawal is the one that takes longest.' },
      { title: 'Shared IND9 account', desc: 'No separate registration. Same login and same wallet as the main IND9 platform.' },
      { title: 'Daily and per-transaction limits', desc: 'The numbers that decide whether a large win comes out in one go or across several days.' },
      { title: 'Common rejection reasons', desc: 'Why a withdrawal request gets held, and what to fix, which saves a support ticket.' },
    ],
    steps: [
      'Install the IND9 app from [ind9game.com](https://ind9game.com) if you have not already.',
      'Read the withdrawal limits and timing published on [ind9win.com](https://ind9win.com) before you deposit anything.',
      'Complete KYC once, early, rather than at the moment you want to cash out.',
      'Make sure the UPI handle you register matches the name on your KYC documents.',
      'Request the withdrawal from the wallet section and track it against the published timing rather than reraising it.',
    ],
    pros: [
      'Publishes withdrawal limits before signup instead of after',
      'Honest about first-withdrawal delays caused by KYC',
      'No separate account needed, it shares the IND9 login',
      'Explains rejection reasons so you can fix them yourself',
      'Useful reference even if you play mainly on another platform',
    ],
    cons: [
      'The site is a reference rather than a lobby, so there is nothing to play on it',
      'Currently being rebuilt, so some sections may be incomplete',
      'Only covers IND9 policy, not other platforms',
    ],
    faqs: [
      { q: 'ind9win.com par alag account banana padta hai?', a: 'Nahi. Same IND9 login aur same wallet chalta hai. Yeh address sirf withdrawal aur winnings ki information ke liye hai.' },
      { q: 'IND9 withdrawal kitni der leta hai?', a: 'Normal UPI withdrawal minutes me settle hota hai. Pehli withdrawal sabse slow hoti hai kyunki uske saath KYC verify hota hai. Site par realistic timing di gayi hai.' },
      { q: 'Withdrawal reject kyu ho jaata hai?', a: 'Sabse common reason: UPI handle ka naam KYC documents ke naam se match nahi karta. Site par baaki rejection reasons bhi listed hain.' },
      { q: 'Minimum withdrawal kitna hai?', a: 'Exact figure site par published hai. Deposit karne se pehle wahi check karna sabse smart move hai, taaki balance minimum se neeche na atke.' },
      { q: 'KYC kab karni chahiye?', a: 'Jitna jaldi ho sake. Withdrawal ke waqt KYC karne se hi delay hota hai. Register karne ke turant baad kar lo.' },
      { q: 'Bada amount ek saath nikal sakte hain?', a: 'Daily aur per-transaction limits hoti hain. Bada win kabhi kabhi do ya teen days me split hota hai. Limits site par di gayi hain.' },
    ],
    alternatives: ['ind9', 'fn7', 'mast179', 's1'],
    anchors: ['IND9 Win', 'ind9win.com', 'the IND9 withdrawal guide', 'IND9 Win withdrawal limits', 'ind9win'],
  },

  {
    key: 'mast79',
    slug: 'mast79-game-review',
    name: 'Mast79 Game',
    domain: 'mast79game.com',
    url: 'https://mast79game.com',
    live: false,
    tagline: 'Slots and fishing arcade in a 45 MB package, with PhonePe as a first-class payout route.',
    blurbHi: 'Slots aur fishing arcade. PhonePe aur UPI dono se withdrawal.',
    bonus: '₹500 signup offer',
    apkSize: '45 MB',
    version: '2.0.7',
    android: 'Android 5.0+',
    payout: 'UPI, PhonePe, Paytm, bank transfer',
    categories: ['Slots', 'Fishing arcade', 'Card games'],
    usp: 'It names its payout rails specifically, PhonePe and Paytm alongside UPI, instead of vaguely promising fast withdrawals.',
    intro: [
      '[Mast79 Game](https://mast79game.com) is a slots and fishing arcade platform on a 45 MB Android build, currently at version 2.0.7. The two categories it leads with are the two that reward short sessions, which suits how most people actually play on a phone: five minutes in a queue rather than an hour at a table.',
      'The detail that separates it from its neighbours is payout specificity. Rather than the usual "fast withdrawals" line, it names the rails: UPI, PhonePe, Paytm and direct bank transfer. Naming the rail matters because it tells you whether your preferred app is supported before you deposit, not after.',
      'Support is listed as 24/7, the minimum Android version is 5.0, and the signup offer is ₹500. A companion address, [mast179games.com](https://mast179games.com), covers the rummy side of the same family for players who want structured card play instead of reels.',
    ],
    features: [
      { title: 'Named payout rails', desc: 'UPI, PhonePe, Paytm and bank transfer, stated individually rather than hidden behind a generic promise.' },
      { title: 'Version 2.0.7 published', desc: 'A real version number you can check your install against, at 45 MB, Android 5.0 and up.' },
      { title: 'Themed slots catalogue', desc: 'Reel games across multiple themes and layouts, which is the platform\'s biggest category by some distance.' },
      { title: 'Fishing arcade modes', desc: 'Fast, target-based play with moving targets. Short sessions by design.' },
      { title: '₹500 signup offer', desc: 'One of the larger welcome offers in this network, credited after registration.' },
      { title: '24/7 support', desc: 'Round the clock in-app support rather than business hours only.' },
    ],
    steps: [
      'Open [mast79game.com](https://mast79game.com) on Android and check that your phone runs 5.0 or later.',
      'Download the 45 MB APK, version 2.0.7.',
      'Accept the browser warning about installing outside the Play Store.',
      'Grant install permission to your browser under Settings, then Security.',
      'Install, register, verify your number and claim the ₹500 signup offer.',
    ],
    pros: [
      'Payout rails named specifically, including PhonePe and Paytm',
      'Published version number and size so you can verify your build',
      'Slots catalogue is deep and properly themed',
      'Fishing arcade suits short mobile sessions',
      '24/7 support rather than limited hours',
    ],
    cons: [
      'Card games are the weakest category here',
      'Domain is easy to confuse with the Mast179 rummy sibling',
      'Android only',
    ],
    faqs: [
      { q: 'Mast79 game ka APK version kaunsa hai?', a: 'Version 2.0.7, size 45 MB, aur Android 5.0 ya usse upar chahiye.' },
      { q: 'Mast79 se PhonePe par paisa aa sakta hai?', a: 'Haan. Mast79 UPI, PhonePe, Paytm aur direct bank transfer, chaaron rails support karta hai aur inhe naam se list karta hai.' },
      { q: 'Mast79 me kaunse games hain?', a: 'Mainly slots aur fishing arcade. Card games bhi hain lekin unka collection sabse chhota hai.' },
      { q: 'Mast79 aur Mast179 same hain?', a: 'Ek hi family ke do platforms hain. Mast79 slots aur fishing par focus karta hai, Mast179 rummy aur card play par. Domains alag hain, dhyan se type karo.' },
      { q: 'Mast79 signup bonus kitna hai?', a: '₹500 ka signup offer hai, jo is network ke bade welcome offers me se ek hai.' },
      { q: 'Support kab available hai?', a: '24/7 in-app support hai, sirf business hours nahi.' },
    ],
    alternatives: ['mast179', 'xx7', 'is7', 'iw7'],
    anchors: ['Mast79 Game', 'mast79game.com', 'the Mast79 APK', 'Mast79', 'Mast79 game download'],
  },

  {
    key: 'mast179',
    slug: 'mast179-games-review',
    name: 'Mast179 Games',
    domain: 'mast179games.com',
    url: 'https://mast179games.com',
    live: false,
    tagline: 'The rummy-first sibling of Mast79: tournaments, points rummy and structured card play.',
    blurbHi: 'Rummy par focus. Tournaments aur points rummy dono milte hain.',
    bonus: 'Tournament entry credits on signup',
    apkSize: 'Approx 42 MB',
    version: 'Latest build',
    android: 'Android 5.0+',
    payout: 'UPI, PhonePe, bank transfer',
    categories: ['Rummy', 'Points rummy', 'Tournaments', 'Card games'],
    usp: 'Rummy tournaments with a real structure, which is a different proposition from casual card tables.',
    intro: [
      '[Mast179 Games](https://mast179games.com) is the card-focused half of the Mast family, and rummy is the whole point of it. Where [Mast79](https://mast79game.com) leads with slots and fishing arcade, Mast179 is built around structured rummy: points rummy, pool formats and scheduled tournaments with real brackets.',
      'That is a meaningfully different kind of play. Slots and arcade modes are designed for a five minute session. Rummy tournaments are designed for a sitting, with progression through rounds and an outcome that depends substantially on how well you play rather than what the reels do. If you want a game where decisions compound, this is the branch of the family to install.',
      'Signup credits come as tournament entries rather than a flat cash bonus, which fits the format. Payouts run over UPI and PhonePe, and the account is separate from the Mast79 one, so treat this as its own platform rather than a second door into the same lobby.',
    ],
    features: [
      { title: 'Points rummy tables', desc: 'The standard fast format, with stake tiers from low entry upward so beginners are not seated against high rollers.' },
      { title: 'Scheduled tournaments', desc: 'Bracketed events on a published schedule, which gives the week structure in a way casual tables do not.' },
      { title: 'Pool rummy formats', desc: 'Longer form games for players who prefer sustained sessions over quick hands.' },
      { title: 'Tournament entry credits on signup', desc: 'The welcome offer arrives as entries rather than cash, which is the right shape for a tournament platform.' },
      { title: 'Skill-weighted outcomes', desc: 'Rummy rewards card counting and discard reading, so results track player ability more than chance formats do.' },
      { title: 'UPI and PhonePe payouts', desc: 'Same named-rail approach as its Mast79 sibling.' },
    ],
    steps: [
      'Open [mast179games.com](https://mast179games.com) on your Android phone.',
      'Download the APK from the official download section.',
      'Accept the browser warning for the file.',
      'Allow installs from your browser under Settings, then Security.',
      'Install, register, verify your number and use the signup tournament entries on a low-stake bracket first.',
    ],
    pros: [
      'Genuine rummy tournament structure rather than casual tables only',
      'Multiple formats: points, pool and bracketed events',
      'Outcomes track skill more closely than reel or prediction formats',
      'Stake tiers separate beginners from high rollers',
      'Named payout rails, UPI and PhonePe',
    ],
    cons: [
      'Narrow catalogue if you want slots or arcade variety',
      'Tournaments need a longer sitting than a five minute session',
      'Separate account from Mast79 despite the shared branding',
    ],
    faqs: [
      { q: 'Mast179 me sirf rummy hai?', a: 'Focus rummy par hai: points rummy, pool formats aur tournaments. Kuch aur card games bhi hain, lekin platform rummy ke around bana hai.' },
      { q: 'Mast179 aur Mast79 ka account same hai?', a: 'Nahi, dono ke accounts alag hain. Ek hi family hai lekin platforms alag chalte hain, isliye dono par alag register karna padega.' },
      { q: 'Tournament kaise join karte hain?', a: 'Tournament section me schedule dikhta hai. Entry credit ya fee ke saath bracket join karo. Signup par jo entries milti hain unse shuru karna best hai.' },
      { q: 'Points rummy aur pool rummy me farq kya hai?', a: 'Points rummy fast hota hai, har deal ka result turant. Pool rummy lamba chalta hai aur elimination par based hota hai. Pool me sitting zyada time leti hai.' },
      { q: 'Rummy skill game hai ya luck?', a: 'Rummy me card counting aur discard reading se result kaafi badal jaata hai, isliye yeh chance-based formats se zyada skill-weighted hai. Luck phir bhi factor rehta hai.' },
      { q: 'Mast179 se withdrawal kaise hota hai?', a: 'UPI aur PhonePe par withdrawal jaata hai, wahi named-rail approach jo Mast79 use karta hai.' },
    ],
    alternatives: ['mast79', 's1', 'c555', 'ind9'],
    anchors: ['Mast179 Games', 'mast179games.com', 'the Mast179 rummy app', 'Mast179', 'Mast179 games download'],
  },

  {
    key: 'iw7',
    slug: 'iw7-apps-review',
    name: 'IW7 Apps',
    domain: 'iw7apps.com',
    url: 'https://iw7apps.com',
    live: false,
    tagline: 'Aviator-style crash play alongside rummy tournaments, slots and casino formats.',
    blurbHi: 'Aviator-style crash game, rummy tournaments aur slots ek saath.',
    bonus: 'Welcome bonus on registration',
    apkSize: 'Approx 40 MB',
    version: 'Latest 2026 APK',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Aviator / crash', 'Rummy tournaments', 'Slots', 'Casino'],
    usp: 'Crash games are its signature format, and very few platforms in this network carry them at all.',
    intro: [
      '[IW7 Apps](https://iw7apps.com) is the crash game platform of this network. Aviator-style formats, where a multiplier climbs until it stops and you have to cash out before it does, are the thing it is known for, and they are almost absent from the other platforms covered here.',
      'Crash play is worth understanding before you try it because the rhythm is unlike anything else in this category. There is no hand to play out and no reel to watch resolve. There is one decision, repeated: when to leave. Rounds last seconds, which makes it the most compressed format in this entire list and the one where a session can get away from you fastest.',
      'Around the crash games sit rummy tournaments, a slots catalogue and casino-style table formats, so the app is not a one-trick build. The install is roughly 40 MB and payouts run over UPI. If you have played crash formats elsewhere and want them on an app that also carries the rest, this is the one to look at.',
    ],
    features: [
      { title: 'Aviator-style crash games', desc: 'The platform\'s signature format. A climbing multiplier and a single cash-out decision per round.' },
      { title: 'Rummy tournaments', desc: 'Bracketed card play for sessions where you want something slower than crash rounds.' },
      { title: 'Slots catalogue', desc: 'A conventional reel collection filling out the middle ground between crash and tournaments.' },
      { title: 'Casino table formats', desc: 'Standard table games rounding out the four categories.' },
      { title: 'Lightweight build', desc: 'Around 40 MB, which keeps it comfortable on mid-range Android hardware.' },
      { title: 'UPI cash-out', desc: 'Withdrawals settle to UPI in rupees after one-time verification.' },
    ],
    steps: [
      'Open [iw7apps.com](https://iw7apps.com) on your Android phone.',
      'Download the latest IW7 APK from the official download section.',
      'Approve the download when your browser warns about the file.',
      'Enable install permission for your browser under Settings, then Security.',
      'Install, register, verify your number, and try the crash format at the smallest stake first to learn the rhythm.',
    ],
    pros: [
      'Carries crash formats, which most platforms in this network do not',
      'Four distinct categories rather than crash alone',
      'Rummy tournaments give a slower option in the same app',
      'Around 40 MB, comfortable on mid-range phones',
      'Standard UPI cash-out',
    ],
    cons: [
      'Crash rounds are extremely fast, which makes losing track of a session easy',
      'The format has a real learning curve if you have only played cards or slots',
      'Android only',
    ],
    faqs: [
      { q: 'IW7 me aviator jaisa game hai?', a: 'Haan, crash format IW7 ka signature game hai. Multiplier upar jaata hai aur aapko crash hone se pehle cash out karna hota hai.' },
      { q: 'Crash game kaise khelte hain?', a: 'Har round me ek hi decision hota hai: kab nikalna hai. Multiplier climb karta rehta hai aur kabhi bhi ruk sakta hai. Round seconds me khatam hota hai, isliye chhoti stake se practice karo.' },
      { q: 'IW7 me aur kya games hain?', a: 'Rummy tournaments, slots aur casino table formats. Crash ke alawa teen aur categories hain.' },
      { q: 'IW7 APK download kahan se karein?', a: 'Official domain iw7apps.com se. Third-party mirrors se APK lena hi asli risk hai.' },
      { q: 'Crash game beginners ke liye theek hai?', a: 'Rounds bahut fast hote hain isliye session par control rakhna mushkil ho sakta hai. Beginners ko sabse chhoti stake par shuru karna chahiye aur pehle rhythm samajhna chahiye.' },
      { q: 'IW7 withdrawal UPI par aata hai?', a: 'Haan, UPI par settle hota hai. Pehli baar verification complete karna padta hai.' },
    ],
    alternatives: ['raja7', 'mmy', 'mast79', 'x89'],
    anchors: ['IW7 Apps', 'iw7apps.com', 'the IW7 APK', 'IW7', 'IW7 game download'],
  },

  {
    key: 'raja7',
    slug: 'raja7-game-download-guide',
    name: 'Raja7 Game',
    domain: 'raja7gamedownload.com',
    url: 'https://raja7gamedownload.com',
    live: false,
    tagline: 'Colour prediction, Wingo and lottery draws with genuinely multilingual support.',
    blurbHi: 'Colour prediction, Wingo aur lottery. Hindi, Tamil, Telugu sab me chalta hai.',
    bonus: 'Welcome bonus plus gift code',
    apkSize: 'Approx 38 MB',
    version: 'Latest APK',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Colour prediction', 'Wingo', 'Lottery', 'Card games'],
    usp: 'Language support that goes past Hindi and English into Tamil and Telugu, which almost nothing else in this category bothers with.',
    intro: [
      '[Raja7 Game](https://raja7gamedownload.com) is built around the prediction and lottery family: colour prediction, Wingo rounds and scheduled draws. These are the formats that drove a lot of this category\'s growth in India, and Raja7 runs them with a cleaner interface than most.',
      'The genuinely distinguishing feature is language. Most platforms in this network offer Hindi and English and call it done. Raja7 extends into Tamil and Telugu as well, which matters enormously if those are the languages you are comfortable making financial decisions in. Reading stake terms in your second language is how people misread stake terms.',
      'Access works through Android, mobile browser and desktop rather than Android alone, so the platform is reachable even on a device where you cannot or do not want to install an APK. Welcome offers arrive as a combination of a bonus and a gift code.',
    ],
    features: [
      { title: 'Colour prediction rounds', desc: 'The format the platform is best known for, running on a fixed timer so rounds are predictable.' },
      { title: 'Wingo', desc: 'Fast interval-based rounds, a close cousin of colour prediction with a different payout table.' },
      { title: 'Scheduled lottery draws', desc: 'Draws on a published schedule so you can plan around them rather than checking constantly.' },
      { title: 'Hindi, Tamil, Telugu and English', desc: 'Four languages, not two. The clearest advantage this platform has over its neighbours.' },
      { title: 'Android, browser and desktop access', desc: 'You do not need to install an APK to reach it, which is useful on shared or work devices.' },
      { title: 'Bonus plus gift code welcome', desc: 'A combined welcome offer rather than a single flat credit.' },
    ],
    steps: [
      'Open [raja7gamedownload.com](https://raja7gamedownload.com) on Android, or in any browser if you would rather not install.',
      'Set your language before registering. Doing it first means the stake terms are in your language from the start.',
      'Download the APK if you want the app, then approve the browser warning.',
      'Enable install permission for your browser under Settings, then Security.',
      'Install, register, verify your number and apply the gift code with the welcome bonus.',
    ],
    pros: [
      'Four language interface including Tamil and Telugu',
      'Prediction and Wingo formats run on predictable timers',
      'Lottery draws on a published schedule',
      'Works in a browser, so no install is strictly required',
      'Welcome offer combines a bonus and a gift code',
    ],
    cons: [
      'Prediction formats are chance-based, so no amount of study changes the odds',
      'Fast round timers make it easy to play more rounds than you meant to',
      'Long domain name that is easy to mistype',
    ],
    faqs: [
      { q: 'Raja7 me colour prediction kaise chalta hai?', a: 'Fixed timer par rounds chalte hain. Har round me aap colour choose karte ho aur result timer khatam hone par declare hota hai. Yeh pura chance-based format hai.' },
      { q: 'Raja7 kaunsi languages support karta hai?', a: 'Hindi, English, Tamil aur Telugu. Is category me chaar languages dena kaafi rare hai, zyadatar apps sirf do dete hain.' },
      { q: 'Wingo aur colour prediction me farq kya hai?', a: 'Dono interval-based rounds hain lekin payout table alag hoti hai. Wingo ke rounds aur bhi fast chalte hain.' },
      { q: 'Bina APK install kiye khel sakte hain?', a: 'Haan. Raja7 mobile browser aur desktop dono par chalta hai, isliye APK install karna zaruri nahi hai.' },
      { q: 'Raja7 game download kahan se karein?', a: 'Official address raja7gamedownload.com se. Domain lamba hai isliye type karte waqt dhyan rakho.' },
      { q: 'Prediction game me jeetne ki koi trick hai?', a: 'Nahi. Yeh chance-based format hai, koi pattern ya trick odds nahi badalti. Jo log guaranteed tricks bechte hain wo scam karte hain.' },
    ],
    alternatives: ['mmy', 'iw7', 'ie777', 'x89'],
    anchors: ['Raja7 Game', 'raja7gamedownload.com', 'the Raja7 APK', 'Raja7', 'Raja7 game download'],
  },
];
