import type { Brand } from './types';

/**
 * Batch 1 of the partner network registry.
 * Facts here were taken from each platform's own live homepage / APK listing
 * at the time of review. Where a domain was unreachable it is marked
 * `live: false` and the entry describes the platform, not uptime.
 */
export const brands1: Brand[] = [
  {
    key: 'in7gaming',
    slug: 'in7-gaming-co-review',
    name: 'IN7 Gaming',
    domain: 'in7gaming.co',
    url: 'https://www.in7gaming.co',
    live: true,
    tagline: 'The IN7 platform on its .co address, with the same ₹777 welcome credit.',
    blurbHi: 'IN7 ka doosra official address. Wahi ₹777 bonus, wahi 48 MB APK.',
    bonus: '₹777 welcome credit',
    apkSize: '48 MB',
    version: 'Latest 2026 build',
    android: 'Android 5.0+',
    payout: 'UPI, PhonePe, Google Pay, Paytm, bank transfer',
    categories: ['Teen Patti', 'Andar Bahar', 'Slots', 'Spin wheel', 'Card games'],
    usp: 'Registration takes about 60 seconds and the welcome credit lands before you open your first table.',
    intro: [
      'If you already know IN7, [in7gaming.co](https://www.in7gaming.co) will feel immediately familiar. It runs the same lobby, the same ₹777 welcome credit and the same 48 MB Android package as the main IN7 build, served from a second address so players in regions where one domain resolves slowly still get a fast page.',
      'What makes the IN7 lobby different from most Android gaming packages is how little it asks of you before you can play. There is no forced tutorial, no 200 MB asset download on first launch, and no wall of promotional modals. You install, register with a phone number, and the daily spin is already sitting on the home screen.',
      'The four things worth knowing before you install: the download is a direct APK rather than a Play Store listing, the welcome credit is auto applied instead of needing a promo code, withdrawals settle to UPI rather than an in-app wallet you cannot empty, and the whole thing is built mobile-first so it behaves correctly on a 5-inch screen.',
    ],
    features: [
      { title: '₹777 credited on signup', desc: 'The welcome credit is applied automatically once your number is verified. No promo code, no support ticket, no waiting period.' },
      { title: 'Daily spin plus a streak counter', desc: 'A free spin every day, and a streak bonus that grows the longer you keep logging in. Missing a day resets the streak, not your balance.' },
      { title: '48 MB install footprint', desc: 'Small enough that the download finishes on a 4G connection in well under a minute, and light enough for entry-level Android phones.' },
      { title: 'Hindi and English throughout', desc: 'The interface, the help text and the support chat all switch between Hindi and English, which matters more than most operators seem to think.' },
      { title: 'UPI withdrawals, not wallet credit', desc: 'Winnings leave the platform to a real UPI handle. Minimum withdrawal is low enough that you are not forced to accumulate before cashing out.' },
      { title: 'Referral rewards on activity', desc: 'The refer and earn structure pays on invited players actually playing rather than only on the install, which keeps the reward flowing longer.' },
    ],
    steps: [
      'Open [in7gaming.co](https://www.in7gaming.co) in Chrome on your Android phone.',
      'Tap the download button on the hero section. The 48 MB APK starts saving immediately.',
      'When Chrome warns about the file type, choose Download anyway. This warning appears for every APK served outside the Play Store.',
      'Open Settings, then Security or Apps, and allow installs from your browser for this one file.',
      'Tap the downloaded file, install, then register with your mobile number and confirm the OTP. The ₹777 credit appears on the home screen.',
    ],
    pros: [
      'Welcome credit is applied automatically with no code hunting',
      'Small download that installs cleanly on budget Android hardware',
      'Full Hindi interface rather than a half translated one',
      'Withdrawals go out to UPI handles instead of a locked in-app wallet',
      'Daily spin and login streak give a reason to return without spending',
    ],
    cons: [
      'Android only, so iPhone users have to use the mobile browser',
      'Not on the Play Store, which means manual APK updates',
      'The spin wheel and streak mechanics can feel repetitive after a few weeks',
    ],
    faqs: [
      { q: 'in7gaming.co aur in7co.in me kya difference hai?', a: 'Koi functional difference nahi hai. Dono IN7 ke official addresses hain, same lobby aur same ₹777 bonus. Jo domain aapke area me fast khulta hai wahi use karo.' },
      { q: 'IN7 Gaming ka APK size kitna hai?', a: 'Around 48 MB. 4G par ek minute se kam me download ho jaata hai aur entry-level Android phones par bhi theek chalta hai.' },
      { q: 'Bonus claim karne ke liye promo code chahiye?', a: 'Nahi. Number verify hone ke baad ₹777 credit apne aap apply ho jaata hai. Koi code enter karne ki zarurat nahi.' },
      { q: 'Withdrawal kitni der me aata hai?', a: 'UPI withdrawals normally minutes me settle hote hain. Pehli baar KYC verify karna padta hai, uske baad process fast rehta hai.' },
      { q: 'Play Store par IN7 Gaming milega?', a: 'Nahi. Real-money gaming apps Play Store ki policy me allowed nahi hain, isliye APK official site se hi download karna padta hai.' },
      { q: 'iPhone par chalega?', a: 'Native iOS app nahi hai. iPhone users mobile browser se site khol sakte hain lekin experience Android app jitna smooth nahi hoga.' },
    ],
    alternatives: ['xx7', 'ie777', 'fn7', 'ind9'],
    anchors: ['IN7 Gaming', 'in7gaming.co', 'the IN7 Gaming lobby', 'IN7 Gaming APK', 'IN7 on its .co address'],
  },

  {
    key: 'xx7',
    slug: 'xx7-game-review',
    name: 'XX7 Game',
    domain: 'xx7game.com',
    url: 'https://xx7game.com',
    live: true,
    tagline: 'A 30 MB package that leans hard into slots and fishing arcade modes.',
    blurbHi: 'Sabse halka APK. Slots aur fishing games ka bada collection.',
    bonus: 'Welcome bonus on first registration',
    apkSize: '30 MB',
    version: '2026 release',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Slots', 'Fishing arcade', 'Card games', 'Lucky spin'],
    usp: 'At 30 MB it is the smallest install in this entire network, and it still ships the widest slots catalogue.',
    intro: [
      '[XX7 Game](https://xx7game.com) is the one I point people to when their phone is already full. The Android package is 30 MB, which is roughly a third of what a typical gaming app of this type asks for, and the compression does not come at the cost of the catalogue.',
      'The lobby is organised around two pillars. Slots are the obvious one, with a large reel collection spanning classic three-reel layouts through to multi-line themed machines. The second is fishing arcade, a category that barely exists on Indian gaming apps outside of a handful of platforms, and XX7 gives it real shelf space rather than three token titles.',
      'Everything about the build reads as deliberately aimed at the Indian market: rupee denominations everywhere, UPI as the default cash-out route rather than an afterthought, and load times tuned for patchy mobile data instead of assuming Wi-Fi.',
    ],
    features: [
      { title: '30 MB download', desc: 'The lightest install across every platform covered on this site. Useful on phones with 16 GB or 32 GB of storage.' },
      { title: 'Deep slots catalogue', desc: 'Classic three-reel machines through to multi-line themed reels, grouped so you are not scrolling past the same game repeatedly.' },
      { title: 'Fishing arcade modes', desc: 'Fast, target-based arcade play. A genuinely different rhythm from card games, and one of the few Indian apps that treats it as a first-class category.' },
      { title: 'Fast UPI cash-outs', desc: 'Withdrawal requests go to UPI and clear quickly once your account is verified once.' },
      { title: 'Built for Indian data speeds', desc: 'Assets stream in progressively so the lobby is usable before every graphic has loaded, which matters on 4G.' },
      { title: 'Welcome bonus on registration', desc: 'A first-registration bonus lands in your balance so you can try the reels before deciding whether to deposit anything.' },
    ],
    steps: [
      'Visit [xx7game.com](https://xx7game.com) on an Android phone.',
      'Tap the download button. The 30 MB file saves in seconds on most connections.',
      'Accept the browser warning about downloading an APK.',
      'Enable install permission for your browser under Settings, then Security.',
      'Install, register with your mobile number, verify the OTP and claim the welcome bonus.',
    ],
    pros: [
      'Smallest install in the category at roughly 30 MB',
      'Slots collection is genuinely broad rather than padded with clones',
      'Fishing arcade category is properly built out, not decorative',
      'Loads usefully fast on 4G rather than needing Wi-Fi',
      'Rupee-first interface with UPI withdrawals as the default',
    ],
    cons: [
      'Card game selection is thinner than slots-heavy focus suggests',
      'No iOS build',
      'Fishing arcade has a learning curve if you have only played card games before',
    ],
    faqs: [
      { q: 'XX7 Game APK ka size kitna hai?', a: 'Around 30 MB. Is network me sabse chhota download yahi hai, isliye kam storage wale phones ke liye best option hai.' },
      { q: 'XX7 me kaunse games hain?', a: 'Mainly slots aur fishing arcade. Iske saath card games aur lucky spin bhi milte hain. Slots ka collection sabse bada hai.' },
      { q: 'Fishing game kaise khelte hain?', a: 'Screen par moving targets aate hain, aap unhe shoot karte ho. Card games se bilkul different rhythm hai, thoda practice lagta hai lekin seekhna easy hai.' },
      { q: 'XX7 withdrawal UPI par aata hai?', a: 'Haan. Withdrawal request UPI par jaati hai aur ek baar account verify hone ke baad jaldi clear hoti hai.' },
      { q: 'XX7 Game safe hai?', a: 'Site HTTPS par chalti hai aur APK official domain xx7game.com se hi milta hai. Third-party mirror sites se download mat karo, wahi asli risk hai.' },
      { q: 'Purana Android phone chalega?', a: 'Android 5.0 aur usse upar chalta hai. 30 MB size ki wajah se purane aur entry-level phones par bhi performance theek rehti hai.' },
    ],
    alternatives: ['mast79', 'in7gaming', 'inr360', 'is7'],
    anchors: ['XX7 Game', 'xx7game.com', 'the XX7 APK', 'XX7 Game download', 'XX7'],
  },

  {
    key: 'ie777',
    slug: 'ie777-game-review',
    name: 'IE777 Game',
    domain: 'ie777s.com',
    url: 'https://ie777s.com',
    live: true,
    tagline: 'A million-plus install base built largely on its refer and earn structure.',
    blurbHi: '1M+ downloads. Refer and earn system iska sabse strong part hai.',
    bonus: 'Signup bonus plus referral earnings',
    apkSize: 'Approx 40 MB',
    version: 'Latest 2026 version',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Slots', 'Card games', 'Lottery', 'Live tables'],
    usp: 'The referral programme is the most developed of any platform in this network, which is how it reached a million installs.',
    intro: [
      '[IE777](https://ie777s.com) is unusual in this category because its growth story is not really about the games. It is about referrals. The platform crossed a million downloads on the back of a refer and earn structure that pays out on downstream activity rather than a flat one-time bounty, and that changes how players use it.',
      'The lobby itself is conventional in the best sense: slots, card games, lottery draws and live table formats, all organised sensibly, all in rupees. If you have used any platform in this space you will not need to learn anything new. The install is around 40 MB and the Android package is served directly from the site.',
      'The site is also worth a look purely as a reference. Its download page walks through the Android install permission flow step by step with screenshots, which is more care than most operators put into the one part of the process that actually confuses new users.',
    ],
    features: [
      { title: 'Multi-level refer and earn', desc: 'Referral income continues as invited players stay active rather than stopping at the install. This is the platform\'s defining feature.' },
      { title: 'Over a million installs', desc: 'A large enough user base that lobbies fill quickly and multiplayer table formats are not sitting empty.' },
      { title: 'Slots, cards, lottery and live tables', desc: 'Four distinct categories rather than one padded out. Lottery draws in particular run on a fixed schedule you can plan around.' },
      { title: 'Documented install flow', desc: 'The official download page shows the Android unknown-sources permission flow with screenshots, which cuts down on failed installs.' },
      { title: 'Signup bonus', desc: 'A welcome bonus lands on registration so you can look around the lobby before committing money.' },
      { title: 'Rupee denominations throughout', desc: 'No currency conversion guesswork. Stakes, balances and withdrawals are all in rupees.' },
    ],
    steps: [
      'Open [ie777s.com](https://ie777s.com) on your Android device.',
      'Tap the APK download button in the hero area.',
      'Confirm the download when Chrome flags the file.',
      'Follow the on-page permission guide, or go to Settings, Security, and allow your browser to install apps.',
      'Install, register, verify your number, and claim the signup bonus. Grab your referral link from the profile section if you plan to invite anyone.',
    ],
    pros: [
      'Best developed referral programme in this network',
      'Large install base keeps multiplayer tables populated',
      'Four genuinely distinct game categories',
      'Install instructions on the site are clear and screenshot-led',
      'Scheduled lottery draws give the week some structure',
    ],
    cons: [
      'Referral-heavy design means a lot of promotional messaging in the app',
      'APK is slightly larger than the lightest options in this category',
      'Android only',
    ],
    faqs: [
      { q: 'IE777 ka refer and earn kaise kaam karta hai?', a: 'Aapko profile section me ek referral link milta hai. Jo log us link se join karke khelte hain, unki activity par aapko commission milta rehta hai. Sirf install par one-time payment nahi hai.' },
      { q: 'IE777 APK kahan se download karein?', a: 'Sirf official site ie777s.com se. Wahan download page par install steps screenshots ke saath diye hain.' },
      { q: '555casino.in bhi IE777 hai?', a: 'Filhaal 555casino.in ka traffic IE777 par redirect hota hai, isliye dono ek hi platform par le jaate hain. Aage 555 Casino apna separate lobby launch kar raha hai.' },
      { q: 'IE777 me kaunse games hain?', a: 'Slots, card games, lottery draws aur live table formats. Lottery draws fixed schedule par chalte hain.' },
      { q: 'IE777 game real hai ya fake?', a: 'Platform 1M+ downloads ke saath actively chal raha hai aur UPI withdrawals process karta hai. Risk sirf tab hai jab aap kisi third-party mirror se APK download karo.' },
      { q: 'Bonus withdraw kar sakte hain directly?', a: 'Signup bonus normally playthrough ke baad withdrawable hota hai. Exact condition app ke promotions section me likhi hoti hai, install ke baad wahan check kar lo.' },
    ],
    alternatives: ['c555', 'raja7', 'mmy', 'xx7'],
    anchors: ['IE777 Game', 'ie777s.com', 'the IE777 APK', 'IE777', 'IE777 game download'],
  },

  {
    key: 'c555',
    slug: '555-casino-review',
    name: '555 Casino',
    domain: '555casino.in',
    url: 'https://555casino.in',
    live: false,
    tagline: 'A casino-first lobby: live tables, Andar Bahar and roulette rather than arcade modes.',
    blurbHi: 'Casino-style lobby. Live tables, Andar Bahar aur roulette par focus.',
    bonus: '₹555 welcome offer',
    apkSize: 'Approx 42 MB',
    version: 'Launch build',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Live casino', 'Andar Bahar', 'Teen Patti', 'Roulette', 'Slots'],
    usp: 'The only platform in this network built casino-first, with live dealer tables as the centrepiece instead of an add-on.',
    intro: [
      '[555 Casino](https://555casino.in) sits apart from the rest of this network because it is not an arcade app with a casino section bolted on. It is the reverse. Live dealer tables, Andar Bahar, Teen Patti and roulette are the main event, and the slots catalogue is the supporting act.',
      'That matters if you actually prefer table games. On most Indian gaming apps, table formats are three or four titles buried under a wall of reels. Here the lobby opens on tables, the stake tiers are structured for table play, and the ₹555 welcome offer is sized to give you a handful of real hands rather than a couple of spins.',
      'At the time of writing 555casino.in points to the IE777 platform while its own lobby is being finished, so anyone typing the address today lands on a working gaming app either way. The dedicated 555 Casino build is the one to watch if live tables are your reason for installing.',
    ],
    features: [
      { title: 'Live dealer tables first', desc: 'Real dealer streams for the main table formats rather than software-only versions, which is the whole reason to pick a casino-first app.' },
      { title: 'Andar Bahar and Teen Patti done properly', desc: 'Multiple stake tiers and table sizes for both, instead of one table you either fit into or you do not.' },
      { title: 'Roulette', desc: 'European and standard layouts, a format most Indian gaming apps skip entirely.' },
      { title: '₹555 welcome offer', desc: 'Sized deliberately for table play, where a handful of hands costs more than a handful of slot spins.' },
      { title: 'Slots as the support act', desc: 'A reel catalogue is there when you want a break, but it is not what the lobby is organised around.' },
      { title: 'UPI cash-out', desc: 'Withdrawals settle to UPI handles and bank accounts in rupees.' },
    ],
    steps: [
      'Open [555casino.in](https://555casino.in) on your Android phone.',
      'Tap the download button for the current build.',
      'Approve the APK download when your browser asks.',
      'Allow installs from your browser in Settings, then Security.',
      'Install, register with your number, verify the OTP and claim the ₹555 welcome offer before you sit at a table.',
    ],
    pros: [
      'Genuinely casino-first rather than an arcade app with tables attached',
      'Live dealer streams for the main formats',
      'Roulette, which most competitors in this space do not carry',
      'Multiple stake tiers so low and mid stakes both have real tables',
      'Welcome offer sized for table play rather than spins',
    ],
    cons: [
      'The dedicated lobby is still rolling out, so the address currently forwards elsewhere',
      'Live tables need a stable connection, so patchy 4G is a problem',
      'Slots catalogue is smaller than slots-led competitors',
    ],
    faqs: [
      { q: '555casino.in abhi kaam kar raha hai?', a: 'Abhi address IE777 platform par forward hota hai jab tak 555 Casino ka apna lobby live nahi hota. Type karne par aapko ek working gaming app to milega hi.' },
      { q: '555 Casino me kya khaas hai?', a: 'Yeh casino-first app hai. Live dealer tables, Andar Bahar, Teen Patti aur roulette main focus hain, slots side me hain. Baaki apps me ulta hota hai.' },
      { q: '₹555 bonus kaise milta hai?', a: 'Registration aur number verification ke baad welcome offer apply hota hai. Table games me stake zyada lagta hai isliye bonus bhi usi hisaab se rakha gaya hai.' },
      { q: 'Roulette milega?', a: 'Haan, roulette 555 Casino ke lobby ka part hai. Indian gaming apps me yeh format kam milta hai.' },
      { q: 'Live tables ke liye internet kitna chahiye?', a: 'Live dealer streams ke liye stable connection zaruri hai. Weak 4G par stream buffer karega, isliye Wi-Fi ya strong signal better rehta hai.' },
      { q: 'Minimum deposit kitna hai?', a: 'Table games ke liye entry tiers rakhe gaye hain taaki low stake players bhi khel sakein. Exact figure app ke deposit page par install ke baad dikhta hai.' },
    ],
    alternatives: ['ie777', 'in7gaming', 's1', 'mast179'],
    anchors: ['555 Casino', '555casino.in', 'the 555 Casino lobby', '555 Casino APK', '555casino'],
  },

  {
    key: 'g112',
    slug: '112-game-apk-guide',
    name: '112 Game',
    domain: '112gameapps.com',
    url: 'https://112gameapps.com',
    live: true,
    tagline: 'Less a lobby, more the best written install and troubleshooting guide in this space.',
    blurbHi: 'Install aur login problems ka sabse detailed guide. v2.0.2, 35 MB.',
    bonus: 'Platform dependent',
    apkSize: '35 MB',
    version: '2.0.2',
    android: 'Android 5.0+',
    payout: 'UPI',
    categories: ['Install guide', 'Login troubleshooting', 'Version tracking'],
    usp: 'It is the only site in this network that documents what to do when the install or the OTP fails, which is where most new players actually get stuck.',
    intro: [
      '[112gameapps.com](https://112gameapps.com) is doing something different from everything else in this network, and it is genuinely useful. Instead of another hero banner and a download button, it is a full install, login and troubleshooting guide for the 112 Game APK on Android.',
      'The reason that matters: almost nobody in this category writes about failure states. Every operator explains how to download an APK. Almost none explain what to do when the install is blocked by Play Protect, when the OTP never arrives, when the app crashes on first launch, or when a version mismatch stops the login screen from loading. This site covers all four.',
      'It also does the boring, unglamorous thing of publishing hard version facts: version 2.0.2, 35 MB, Android 5.0 and above. Being able to check whether the build on your phone matches the current release is a small thing that saves a lot of pointless reinstalling.',
    ],
    features: [
      { title: 'OTP failure troubleshooting', desc: 'What to actually do when the verification SMS does not arrive, which is the single most common reason people abandon a registration.' },
      { title: 'Play Protect and blocked install fixes', desc: 'Step by step handling of the Android warnings that stop APK installs, explained without pretending the warnings are meaningless.' },
      { title: 'Published version facts', desc: 'Version 2.0.2, 35 MB, Android 5.0+. You can check your build against the current one instead of guessing.' },
      { title: 'Login problem walkthroughs', desc: 'Covers stuck login screens, session timeouts and password reset paths in order of likelihood.' },
      { title: 'Compatibility notes', desc: 'Clear about which Android versions are supported rather than claiming universal compatibility.' },
      { title: '18+ notice front and centre', desc: 'The age restriction is stated plainly rather than buried in a footer, which is worth crediting.' },
    ],
    steps: [
      'Open [112gameapps.com](https://112gameapps.com) and read the compatibility section first to confirm your Android version.',
      'Follow the download steps on the page. The current build is 35 MB.',
      'If the install is blocked, use the Play Protect section rather than repeatedly retrying the file.',
      'Register and verify. If the OTP does not arrive, work through the OTP troubleshooting section instead of requesting the code ten times.',
      'Bookmark the version section so you can check your build number when something stops working later.',
    ],
    pros: [
      'The only site here that documents install and login failure states',
      'Publishes real version, size and compatibility numbers',
      'OTP troubleshooting is genuinely the most useful page in this network',
      'Honest about what the Android security warnings mean',
      'Age restriction stated clearly up front',
    ],
    cons: [
      'It is a guide site, so there is no lobby to browse on the page itself',
      'Less useful once you are past setup and playing',
      'Bonus details depend on the platform build rather than being fixed',
    ],
    faqs: [
      { q: '112 Game APK ka current version kaunsa hai?', a: 'Version 2.0.2, size 35 MB, aur Android 5.0 ya usse upar chahiye. Ye numbers site par published hain, guess karne ki zarurat nahi.' },
      { q: 'OTP nahi aa raha, kya karein?', a: '112gameapps.com par ek pura OTP troubleshooting section hai. Baar baar resend dabane se kuch nahi hota, us section ke steps follow karo.' },
      { q: 'Install block ho raha hai, Play Protect warning aa rahi hai. Kya karein?', a: 'Yeh warning har APK par aati hai jo Play Store ke bahar se aata hai. Site par iska step-by-step fix diya hua hai, wahi follow karo.' },
      { q: '112 Game app kis kaam ka hai?', a: '112gameapps.com khud ek install aur troubleshooting guide hai 112 Game APK ke liye. Setup, login aur version issues yahan cover hote hain.' },
      { q: 'App crash ho raha hai first launch par. Fix kya hai?', a: 'Usually version mismatch ya incomplete download ki wajah se hota hai. Site ke version section me apna build check karo aur zarurat pade to clean reinstall karo.' },
      { q: 'Kya 112 Game Play Store par hai?', a: 'Nahi. Is category ke apps Play Store policy me allowed nahi hote, isliye APK direct download hi hota hai. Isi wajah se install guide itna useful hai.' },
    ],
    alternatives: ['is7', 'mmy', 'x89', 'in7gaming'],
    anchors: ['112 Game', '112gameapps.com', 'the 112 Game APK guide', '112 Game install guide', '112gameapps'],
  },

  {
    key: 'inr360',
    slug: '360inr-game-review',
    name: '360INR Game',
    domain: '360-inr.com',
    url: 'https://360-inr.com',
    live: true,
    tagline: 'Two million players, a ₹200 instant bonus, and a skill-based framing throughout.',
    blurbHi: '2M+ players. ₹200 instant bonus registration ke turant baad.',
    bonus: '₹200 instant cash bonus',
    apkSize: 'Approx 38 MB',
    version: 'Latest 2026 build',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Skill games', 'Card games', 'Slots', 'Prediction'],
    usp: 'The ₹200 bonus is credited instantly on registration rather than after a deposit, which is a meaningfully different offer.',
    intro: [
      '[360INR Game](https://360-inr.com) has the clearest offer of any platform in this network: register, and ₹200 lands in your balance instantly. Not after a first deposit, not after a playthrough threshold, not as bonus credit you can only use on one game. That distinction is worth understanding because most welcome offers in this category are deposit-matched, which means they cost you money to unlock.',
      'The platform positions itself around skill-based play and carries roughly two million players. The catalogue mixes card games, slots and prediction formats, and the interface is built around rupee stakes with UPI cash-outs, which by now is table stakes for anything serious in the Indian market.',
      'The site itself is one of the better built ones here, with a clean app information table, real screenshots, and a "more games to download" section rather than pretending it is the only app you will ever install. That last part is unusually honest for the category.',
    ],
    features: [
      { title: '₹200 credited on registration', desc: 'No deposit needed to trigger it. This is the single strongest reason to try the platform before others in this list.' },
      { title: 'Around two million players', desc: 'Large enough that multiplayer formats have opponents and leaderboards mean something.' },
      { title: 'Skill-based framing', desc: 'The catalogue leans toward formats where decisions matter rather than pure chance, and the platform is explicit about it.' },
      { title: 'Published app information table', desc: 'Size, version and requirements are laid out on the homepage instead of being something you find out after installing.' },
      { title: 'Real screenshots', desc: 'The gallery shows the actual lobby, not rendered mockups, so you know what you are installing.' },
      { title: 'Fast UPI withdrawals', desc: 'Cash-outs settle to UPI in rupees once your account is verified.' },
    ],
    steps: [
      'Open [360-inr.com](https://360-inr.com) on Android and check the app information table for your device compatibility.',
      'Tap the download button for the current APK.',
      'Approve the download when the browser warns about the file.',
      'Allow installs from your browser under Settings, then Security.',
      'Install, register, verify your number, and the ₹200 bonus appears in your balance immediately.',
    ],
    pros: [
      'Instant ₹200 bonus with no deposit requirement',
      'Two million player base means populated lobbies',
      'App size, version and requirements published openly',
      'Screenshots are of the real lobby',
      'Site links out to alternatives rather than pretending to be the only option',
    ],
    cons: [
      'The domain hyphen makes the address easy to mistype',
      'Prediction formats sit uneasily with the skill-based positioning',
      'Android only',
    ],
    faqs: [
      { q: '360INR ka ₹200 bonus deposit ke baad milta hai?', a: 'Nahi, registration ke turant baad milta hai. Deposit ki koi condition nahi hai, isliye yeh offer baaki deposit-match bonuses se better hai.' },
      { q: '360INR Game download kaise karein?', a: '360-inr.com kholo, download button dabao, browser warning accept karo, aur Settings me apne browser ko install permission do. Address me hyphen dhyan se type karo.' },
      { q: '360 INR game real hai?', a: 'Platform 2M+ players ke saath chal raha hai aur UPI withdrawals process karta hai. App size, version aur requirements site par openly published hain, jo ek accha sign hai.' },
      { q: '360INR me kaunse games hain?', a: 'Card games, slots aur prediction formats. Platform khud ko skill-based games ke around position karta hai.' },
      { q: 'Withdrawal minimum kitna hai?', a: 'Withdrawal UPI par jaata hai. Minimum amount app ke wallet section me dikhta hai, aur pehli withdrawal se pehle account verify karna padta hai.' },
      { q: 'Domain 360-inr.com hai ya 360inr.com?', a: 'Official address 360-inr.com hai, hyphen ke saath. Bina hyphen wale addresses official nahi hain, wahan se download mat karo.' },
    ],
    alternatives: ['fn7', 'ind9', 'xx7', 'x89'],
    anchors: ['360INR Game', '360-inr.com', 'the 360INR APK', '360INR', '360 INR game'],
  },

  {
    key: 'fn7',
    slug: 'fn7-game-review',
    name: 'FN7 Game',
    domain: 'fn7gameng.com',
    url: 'https://fn7gameng.com',
    live: true,
    tagline: 'The most thoroughly documented platform here: login, register, spin, bonus and withdrawal all covered.',
    blurbHi: '₹200 bonus. Login se withdrawal tak har step ka guide.',
    bonus: '₹200 welcome bonus',
    apkSize: 'Approx 40 MB',
    version: 'Latest APK',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Spin games', 'Card games', 'Slots', 'Skill games'],
    usp: 'Every stage of the player journey has its own documented section, which makes it the easiest platform here to start on without help.',
    intro: [
      '[FN7 Game](https://fn7gameng.com) wins on documentation. Most platforms in this category publish a download button and a bonus figure and leave you to work out the rest. FN7 has a written section for the login flow, one for registration, one for the spin game, one for the bonus structure and one for the withdrawal process, all on the front page.',
      'The ₹200 welcome bonus is credited on signup. The spin game is the mechanic the platform is best known for: a daily spin that gives you a reason to open the app without spending, and one of the more generous versions of that pattern in this network.',
      'The catalogue itself covers card games, slots and skill formats. Nothing exotic, but the spin layer sitting on top of it gives the daily loop a shape that platforms without it lack. If you are new to this whole category and want the platform with the shallowest learning curve, this is the one.',
    ],
    features: [
      { title: 'Daily spin and win', desc: 'The mechanic FN7 is known for. A free daily spin that gives you something to do without depositing.' },
      { title: '₹200 welcome bonus', desc: 'Credited on signup, so you can play a few rounds before deciding whether to fund the account.' },
      { title: 'Documented login and register flows', desc: 'Both processes have their own written guide, which cuts out most of the confusion new players hit.' },
      { title: 'Documented withdrawal process', desc: 'The cash-out flow is explained before you sign up rather than being something you discover when you try to leave.' },
      { title: 'Card games, slots and skill formats', desc: 'A conventional catalogue, competently organised, with the spin layer adding daily structure on top.' },
      { title: 'Hindi coverage in the guides', desc: 'The written sections cover the common Hindi search phrasings, so the guidance is findable in the language players actually search in.' },
    ],
    steps: [
      'Open [fn7gameng.com](https://fn7gameng.com) on Android.',
      'Read the register section, then tap the download button for the latest APK.',
      'Accept the APK download warning in your browser.',
      'Allow installs from your browser under Settings, then Security.',
      'Install, register, verify your number, claim the ₹200 bonus and take your first daily spin.',
    ],
    pros: [
      'Best documented player journey of any platform in this network',
      '₹200 bonus on signup with no deposit trigger',
      'Daily spin gives a genuine reason to return without spending',
      'Withdrawal process explained before you commit',
      'Guides cover Hindi search phrasings, not just English',
    ],
    cons: [
      'The domain spelling, fn7gameng.com, is easy to get wrong',
      'Catalogue is conventional rather than distinctive',
      'Android only',
    ],
    faqs: [
      { q: 'FN7 game kya hai?', a: 'FN7 ek Android gaming platform hai jisme card games, slots aur skill formats hain, aur uske upar ek daily spin game chalta hai. ₹200 welcome bonus signup par milta hai.' },
      { q: 'FN7 game kaise download kare?', a: 'fn7gameng.com kholo, latest APK download karo, browser warning accept karo, aur Settings me install permission do. Domain spelling dhyan se: fn7gameng.com.' },
      { q: 'FN7 spin game kaise kaam karta hai?', a: 'Har din ek free spin milta hai. Isse aap bina paisa lagaye rewards jeet sakte ho. Yahi FN7 ka sabse popular feature hai.' },
      { q: 'FN7 withdrawal kaise karte hain?', a: 'App ke wallet section se withdrawal request lagti hai aur UPI par settle hoti hai. Poora process site ke withdrawal section me pehle se likha hua hai.' },
      { q: 'FN7 real or fake?', a: 'Platform live hai, bonus credit karta hai aur withdrawal process documented hai. Sirf official domain fn7gameng.com se hi APK lena, mirror sites se nahi.' },
      { q: 'FN7 login nahi ho raha, kya karein?', a: 'Site par login ka dedicated section hai jisme common issues cover hain. Pehle wahan dekho, phir bhi na chale to in-app support se contact karo.' },
    ],
    alternatives: ['inr360', 'ind9', 'mmy', 'in7gaming'],
    anchors: ['FN7 Game', 'fn7gameng.com', 'the FN7 APK', 'FN7', 'FN7 game download'],
  },
];
