import type { Brand } from './types';

/** Batch 3 of the partner network registry. */
export const brands3: Brand[] = [
  {
    key: 'mmy',
    slug: 'mmy-game-download-review',
    name: 'MMY Game',
    domain: 'mmydownload.com',
    url: 'https://mmydownload.com',
    live: false,
    tagline: 'Wingo, TRX Hash, Ludo and 5D Lotre in one app, including a provably fair format.',
    blurbHi: 'Wingo, TRX Hash, Ludo aur 5D Lotre. Hash game verify kar sakte ho.',
    bonus: '₹300 signup bonus',
    apkSize: 'Approx 36 MB',
    version: 'Latest MMY APK',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Wingo', 'TRX Hash', 'Ludo', '5D Lotre', 'Slots'],
    usp: 'TRX Hash is a verifiable format: the result derives from a blockchain hash you can check yourself after the round.',
    intro: [
      '[MMY Game](https://mmydownload.com) carries the most interesting format in this entire network, and hardly anybody talks about it. TRX Hash games derive their result from a Tron blockchain hash, which means the outcome of a round can be independently verified after the fact. You are not taking the operator\'s word for the number.',
      'That is a real difference from every other chance format on this page. In standard colour prediction or Wingo, you have no way to audit a result. In a hash-based game, the input is public. Whether that changes your odds is a separate question, it does not, but it does change whether you have to trust anyone about what happened.',
      'The rest of the catalogue is broad: Wingo rounds, Ludo, 5D Lotre draws and a slots collection, on a roughly 36 MB build with a ₹300 signup bonus. Ludo in particular is a genuine outlier here, since almost no other platform in this network carries it.',
    ],
    features: [
      { title: 'TRX Hash, independently verifiable', desc: 'Round results derive from a public blockchain hash, so you can audit the outcome yourself rather than trusting a server.' },
      { title: 'Ludo', desc: 'Real multiplayer Ludo, which almost nothing else in this network offers. Familiar rules, structured stakes.' },
      { title: 'Wingo rounds', desc: 'Fast interval-based prediction on a fixed timer.' },
      { title: '5D Lotre draws', desc: 'Five-digit lottery draws on a schedule, a different rhythm from timed rounds.' },
      { title: '₹300 signup bonus', desc: 'Credited on registration, enough to sample several of the formats before depositing.' },
      { title: 'Around 36 MB', desc: 'A small build for the breadth of catalogue it carries.' },
    ],
    steps: [
      'Open [mmydownload.com](https://mmydownload.com) on your Android phone.',
      'Download the MMY APK, roughly 36 MB.',
      'Approve the download when your browser flags the APK.',
      'Allow installs from your browser under Settings, then Security.',
      'Install, register, verify your number and claim the ₹300 signup bonus. Try a TRX Hash round and verify the hash afterwards to see how it works.',
    ],
    pros: [
      'TRX Hash results are independently verifiable, which nothing else here offers',
      'Ludo is a genuine point of difference in this category',
      'Four distinct formats plus slots on a small build',
      '₹300 signup bonus with no deposit trigger',
      'Compact 36 MB install',
    ],
    cons: [
      'Verifiability improves transparency but does not improve your odds',
      'Wingo and 5D Lotre are pure chance formats',
      'Android only',
    ],
    faqs: [
      { q: 'TRX Hash game kya hota hai?', a: 'Iska result Tron blockchain ke hash se nikalta hai. Matlab round ke baad aap khud verify kar sakte ho ki result kya tha. Operator par bharosa karne ki zarurat nahi.' },
      { q: 'Hash game me jeetne ke chances zyada hote hain?', a: 'Nahi. Verifiability se transparency badhti hai, odds nahi. Result verify kar sakte ho, lekin game phir bhi chance-based hai.' },
      { q: 'MMY me Ludo real multiplayer hai?', a: 'Haan, Ludo real multiplayer format me hai. Is network me Ludo dene wala yeh almost ek hi platform hai.' },
      { q: 'MMY ka signup bonus kitna hai?', a: '₹300 registration ke baad credit hota hai. Deposit ki condition nahi hai.' },
      { q: '5D Lotre kaise chalta hai?', a: 'Paanch digit ka lottery draw hota hai jo schedule par chalta hai. Timed rounds se different rhythm hai.' },
      { q: 'MMY APK kahan se download karein?', a: 'Official domain mmydownload.com se. Baaki mirror sites se APK lene ka koi reason nahi hai.' },
    ],
    alternatives: ['raja7', 'iw7', 'ind9', 'g112'],
    anchors: ['MMY Game', 'mmydownload.com', 'the MMY APK', 'MMY', 'MMY game download'],
  },

  {
    key: 'x89',
    slug: 'x89-app-review',
    name: 'X89 App',
    domain: 'x89app.in',
    url: 'https://x89app.in',
    live: false,
    tagline: 'Deposits from ₹100 with immediate processing, and wallet support beyond bare UPI.',
    blurbHi: '₹100 se deposit shuru. Paytm aur wallets bhi chalte hain, sirf UPI nahi.',
    bonus: 'Welcome reward plus daily bonuses',
    apkSize: 'Approx 34 MB',
    version: 'Latest X89 APK',
    android: 'Android 5.0+',
    payout: 'UPI, Paytm, debit card, major Indian wallets',
    categories: ['Slots', 'Card games', 'Prediction', 'Tournaments'],
    usp: 'The widest payment support in this network: UPI, Paytm, debit cards and wallets, with a ₹100 entry point.',
    intro: [
      '[X89 App](https://x89app.in) competes on payments rather than on games, and for a lot of players that is the more useful axis. UPI, Paytm, debit cards and major Indian wallets are all supported, with deposits starting at ₹100 and processing immediately. Most platforms in this network support UPI and stop there.',
      'That breadth matters in two situations. If your bank\'s UPI is having a bad day, which happens more than anyone admits, an alternative rail means you are not locked out. And if you deliberately keep gaming money separate from your main bank account through a wallet, X89 lets you do that cleanly.',
      'The catalogue covers slots, card games, prediction formats and tournaments, with a rewards structure built on three layers: a welcome reward, daily bonuses, and referral plus leaderboard earnings for regular players. The build is around 34 MB, which keeps it on the lighter end of this list.',
    ],
    features: [
      { title: 'Four payment rails', desc: 'UPI, Paytm, debit card and major wallets. The broadest payment support of any platform covered here.' },
      { title: '₹100 minimum deposit', desc: 'A low entry point with immediate processing, so you are not committing a large amount to try the platform.' },
      { title: 'Three-layer rewards', desc: 'Welcome reward, daily bonuses, and referral plus leaderboard earnings. Designed to reward returning rather than only signing up.' },
      { title: 'Leaderboard competition', desc: 'Ranked play with periodic payouts, which gives regular players something beyond individual sessions.' },
      { title: 'Fast prediction formats', desc: 'Short round prediction games alongside the slots and card catalogue.' },
      { title: 'Around 34 MB', desc: 'Light enough for budget Android hardware.' },
    ],
    steps: [
      'Open [x89app.in](https://x89app.in) on your Android phone.',
      'Download the X89 APK from the official download button.',
      'Approve the browser warning about the APK file.',
      'Enable install permission for your browser under Settings, then Security.',
      'Install, register, verify your number, then pick whichever payment rail suits you. The minimum deposit is ₹100.',
    ],
    pros: [
      'Widest payment support in this network, not UPI only',
      '₹100 minimum deposit with immediate processing',
      'Rewards structure pays returning players, not just new ones',
      'Leaderboards add competitive structure',
      'Light 34 MB build',
    ],
    cons: [
      'Card and debit rails can carry processing conditions UPI does not',
      'Leaderboard chasing encourages longer sessions than planned',
      'Android only',
    ],
    faqs: [
      { q: 'X89 me minimum deposit kitna hai?', a: '₹100. Processing immediate hoti hai, isliye chhoti amount se try kar sakte ho.' },
      { q: 'X89 kaunse payment methods leta hai?', a: 'UPI, Paytm, debit card aur major Indian wallets. Is network me sabse broad payment support X89 ka hai.' },
      { q: 'X89 app download kaise karein?', a: 'x89app.in kholo, APK download karo, browser warning accept karo, aur Settings me install permission do.' },
      { q: 'X89 me daily bonus milta hai?', a: 'Haan. Rewards teen layers me hain: welcome reward, daily bonuses, aur referral plus leaderboard earnings.' },
      { q: 'Leaderboard kaise kaam karta hai?', a: 'Ranked play hoti hai aur periodic payouts milte hain. Regular players ke liye yeh individual sessions se aage ka incentive hai.' },
      { q: 'X89 game real hai ya fake?', a: 'Official domain x89app.in hai. Is naam par bahut se unofficial sites chalti hain, isliye sirf official address se hi APK lo.' },
    ],
    alternatives: ['inr360', 's1', 'iw7', 'mg7'],
    anchors: ['X89 App', 'x89app.in', 'the X89 APK', 'X89', 'X89 game download'],
  },

  {
    key: 's1',
    slug: 's1-games-review',
    name: 'S1 Games',
    domain: 's1games.in',
    url: 'https://s1games.in',
    live: false,
    tagline: 'Teen Patti and rummy with 128-bit SSL, strict KYC and instant UPI cash-out.',
    blurbHi: 'Teen Patti aur rummy. 128-bit SSL aur proper KYC norms follow karta hai.',
    bonus: 'Welcome bonus on registration',
    apkSize: '38 MB',
    version: 'Latest S1 APK',
    android: 'Android 5.0+',
    payout: 'Instant UPI, bank transfer',
    categories: ['Teen Patti', 'Rummy', 'Card games'],
    usp: 'It is the most explicit platform here about security specifics: 128-bit SSL, encrypted payment gateways and stated KYC compliance.',
    intro: [
      '[S1 Games](https://s1games.in) is the security-forward option in this network. Rather than a generic claim that your data is safe, it names specifics: 128-bit SSL on all data, encrypted payment gateways, and a stated commitment to following KYC norms. Naming the mechanism is a better signal than promising the outcome.',
      'The catalogue is deliberately narrow. Teen Patti and rummy are the focus, and the platform does not pretend to be a hundred-game arcade. For players who only ever open a gaming app to play cards, a narrow catalogue is a feature: the tables you want are on the first screen instead of four scrolls down past reels you will never touch.',
      'The build is 38 MB, withdrawals are instant to UPI, and the site is unusually direct about responsible play, recommending you treat deposits as an entertainment expense rather than an investment. That is the correct framing, and it is rare enough in this category to be worth pointing out.',
    ],
    features: [
      { title: '128-bit SSL on all data', desc: 'A named encryption standard rather than a vague security claim.' },
      { title: 'Encrypted payment gateways', desc: 'Payment handling goes through encrypted gateways, so card and UPI details are not sitting in the clear.' },
      { title: 'Stated KYC compliance', desc: 'The platform says it follows KYC norms and applies them, which is what makes withdrawals reliable later.' },
      { title: 'Teen Patti and rummy focus', desc: 'A narrow catalogue, deliberately. The tables you came for are on the first screen.' },
      { title: 'Instant UPI withdrawals', desc: 'Cash-outs settle to UPI quickly once your one-time verification is complete.' },
      { title: 'Honest responsible-play framing', desc: 'The site recommends treating deposits as an entertainment expense, not an investment. It is the right advice.' },
    ],
    steps: [
      'Open [s1games.in](https://s1games.in) on your Android phone.',
      'Tap the download button for the 38 MB S1 APK.',
      'Accept the browser warning about installing outside the Play Store.',
      'Allow installs from your browser under Settings, then Security.',
      'Install, register, complete KYC early rather than at cash-out time, and claim the welcome bonus.',
    ],
    pros: [
      'Names its security mechanisms instead of making vague claims',
      'Narrow card-focused catalogue means less noise',
      'Instant UPI withdrawals after one-time verification',
      'Explicit and correct responsible-play framing',
      'Applies KYC properly, which is what makes payouts dependable',
    ],
    cons: [
      'No slots, arcade or prediction formats at all',
      'KYC is enforced, so you cannot skip verification',
      'Android only',
    ],
    faqs: [
      { q: 'S1 Games me kaunse games hain?', a: 'Sirf Teen Patti, rummy aur card games. Slots, arcade ya prediction formats nahi hain. Catalogue jaan-boojh kar narrow rakha gaya hai.' },
      { q: 'S1 Games safe hai?', a: 'Platform 128-bit SSL, encrypted payment gateways aur KYC norms specifically mention karta hai. Mechanism naam se batana ek accha sign hai.' },
      { q: 'S1 ka APK size kitna hai?', a: '38 MB, aur Android 5.0 ya usse upar chahiye.' },
      { q: 'KYC skip kar sakte hain?', a: 'Nahi. S1 KYC properly enforce karta hai. Isi wajah se withdrawals reliable rehte hain, isliye register karne ke turant baad KYC kar lo.' },
      { q: 'S1 se withdrawal kitni der me aata hai?', a: 'Verification complete hone ke baad UPI withdrawals instant settle hote hain.' },
      { q: 'Kitna paisa lagana chahiye?', a: 'Site khud kehti hai ki deposit ko entertainment expense samjho, investment nahi. Sirf utna hi lagao jo aap comfortably lose kar sakte ho.' },
    ],
    alternatives: ['mast179', 'c555', 'x89', 'in7gaming'],
    anchors: ['S1 Games', 's1games.in', 'the S1 Game APK', 'S1 Game', 'S1 games download'],
  },

  {
    key: 'mg7',
    slug: 'mg7-app-review',
    name: 'MG7 App',
    domain: 'mg7app.co.in',
    url: 'https://mg7app.co.in',
    live: false,
    tagline: 'A compact multi-game build aimed squarely at entry-level Android phones.',
    blurbHi: 'Chhota build, purane phones ke liye. Slots aur card games dono.',
    bonus: 'Signup bonus on registration',
    apkSize: 'Approx 32 MB',
    version: 'Latest MG7 APK',
    android: 'Android 5.0+',
    payout: 'UPI, bank transfer',
    categories: ['Slots', 'Card games', 'Prediction', 'Lucky spin'],
    usp: 'Explicitly built for low-end hardware, which is a real and underserved constraint for a large share of Indian Android users.',
    intro: [
      '[MG7 App](https://mg7app.co.in) is built around a constraint nobody else in this network designs for: the phone most people actually own. Entry-level Android hardware with 2 GB or 3 GB of RAM, 32 GB of storage that is already three quarters full, and a 4G connection that is honest about being 4G.',
      'The result is a roughly 32 MB build that does not assume a flagship. Animations are lighter, the lobby loads progressively, and the game selection is chosen for titles that run at a usable frame rate on modest silicon rather than titles that look best in a screenshot. That is a legitimate engineering choice, not a compromise.',
      'The catalogue is a conventional mix: slots, card games, prediction formats and a lucky spin. Payouts go over UPI. If you have tried other platforms in this list and found them sluggish or crash-prone on your phone, this is the one to try next.',
    ],
    features: [
      { title: 'Built for entry-level hardware', desc: 'Tuned for 2 GB and 3 GB RAM phones rather than assuming recent flagship specs.' },
      { title: 'Around 32 MB', desc: 'One of the smallest builds here, which matters on a 32 GB phone that is already nearly full.' },
      { title: 'Progressive lobby loading', desc: 'The lobby becomes usable before every asset has downloaded, which is the right behaviour on slow connections.' },
      { title: 'Games chosen for performance', desc: 'Title selection weighted toward what runs smoothly on modest hardware rather than what looks best in marketing.' },
      { title: 'Conventional four-category mix', desc: 'Slots, card games, prediction and lucky spin. Familiar ground, competently built.' },
      { title: 'UPI payouts', desc: 'Standard UPI cash-out in rupees after one-time verification.' },
    ],
    steps: [
      'Open [mg7app.co.in](https://mg7app.co.in) on your Android phone.',
      'Download the MG7 APK, roughly 32 MB.',
      'Approve the browser warning for the APK.',
      'Allow installs from your browser under Settings, then Security.',
      'Install, register, verify your number and claim the signup bonus.',
    ],
    pros: [
      'Genuinely designed for the phones most Indian players own',
      'Very small install footprint at around 32 MB',
      'Lobby is usable before assets finish loading',
      'Games picked for frame rate on modest hardware',
      'Standard UPI cash-out',
    ],
    cons: [
      'Lighter graphics than flagship-targeted competitors',
      'Catalogue is conventional with no standout category',
      'Android only',
    ],
    faqs: [
      { q: 'MG7 purane phone par chalega?', a: 'Haan, isi ke liye bana hai. 2 GB aur 3 GB RAM wale entry-level phones ko target karke build kiya gaya hai.' },
      { q: 'MG7 APK ka size kitna hai?', a: 'Around 32 MB. Is network ke sabse chhote builds me se ek hai.' },
      { q: 'MG7 me kaunse games hain?', a: 'Slots, card games, prediction formats aur lucky spin. Selection aisi hai jo modest hardware par smooth chale.' },
      { q: 'Graphics kaise hain?', a: 'Flagship-targeted apps se lighter hain, kyunki priority smooth performance hai. Yeh trade-off jaan-boojh kar liya gaya hai.' },
      { q: 'MG7 app official domain kya hai?', a: 'mg7app.co.in. Address me .co.in hai, sirf .in nahi, isliye type karte waqt dhyan rakho.' },
      { q: 'MG7 se withdrawal kaise hota hai?', a: 'UPI par, rupees me. Pehli withdrawal se pehle ek baar verification complete karna padta hai.' },
    ],
    alternatives: ['x89', 'is7', 'xx7', 'g112'],
    anchors: ['MG7 App', 'mg7app.co.in', 'the MG7 APK', 'MG7', 'MG7 app download'],
  },

  {
    key: 'is7',
    slug: 'is7-game-apk-guide',
    name: 'IS7 Game',
    domain: 'is7gameapks.com',
    url: 'https://is7gameapks.com',
    live: false,
    tagline: 'An APK version library: build history, checksums and which release to actually install.',
    blurbHi: 'APK versions ka record. Kaunsa build install karna hai, yahan pata chalta hai.',
    bonus: 'Platform dependent',
    apkSize: 'Varies by release',
    version: 'Multiple tracked releases',
    android: 'Android 5.0+',
    payout: 'UPI',
    categories: ['APK versions', 'Build history', 'Install verification'],
    usp: 'It tracks which build is current and which are stale, which is the one thing you cannot work out from an app alone.',
    intro: [
      '[IS7 Game](https://is7gameapks.com) solves a problem specific to apps that live outside the Play Store: version drift. When there is no store handling updates, your phone will happily run a build from four months ago until something breaks, and you will have no way to tell that the build is the reason.',
      'This site tracks releases: which version is current, what changed, and how to confirm that the file you downloaded is the file that was published. That last part is the one that actually protects you, because the real risk with APK distribution is not the format, it is downloading a repackaged file from a mirror.',
      'Treat it as a reference rather than a lobby. You use it when the app stops behaving, when you want to know whether an update exists, or when you want to confirm a download before installing it. Its companion in this network is [112gameapps.com](https://112gameapps.com), which covers install and login failures.',
    ],
    features: [
      { title: 'Tracked release history', desc: 'Which build is current and which are superseded, so you can tell whether your problem is a stale version.' },
      { title: 'Download verification guidance', desc: 'How to confirm the file you downloaded matches the published release, which is the real defence against repackaged APKs.' },
      { title: 'Change notes per release', desc: 'What actually changed between builds instead of a generic bug-fixes line.' },
      { title: 'Compatibility per version', desc: 'Which Android versions each build supports, useful if you are on an older phone.' },
      { title: 'Manual update guidance', desc: 'How to update without losing your session, since there is no store to do it for you.' },
      { title: 'Pairs with the 112 Game guide', desc: 'Version tracking here, install and login troubleshooting on [112gameapps.com](https://112gameapps.com).' },
    ],
    steps: [
      'Open [is7gameapks.com](https://is7gameapks.com) and find the current release listing.',
      'Check the version on your phone under Settings, then Apps, against the current release.',
      'If you are behind, download the current APK from the official source rather than a mirror.',
      'Verify the download against the published details before you install it.',
      'Install over the top of your existing build so your session and account are preserved.',
    ],
    pros: [
      'Tracks version history, which nothing else in this network does',
      'Explains download verification, the genuine security step',
      'Real change notes rather than boilerplate',
      'Per-version Android compatibility',
      'Pairs cleanly with the 112 Game install guide',
    ],
    cons: [
      'A reference site, so there is nothing to play here',
      'Only useful once you already have the app installed',
      'The site is being rebuilt, so some listings may lag the current release',
    ],
    faqs: [
      { q: 'Apna app version kaise check karein?', a: 'Phone ki Settings, phir Apps me jao aur app select karo. Wahan version number dikhta hai. Usko is7gameapks.com par listed current release se compare karo.' },
      { q: 'Purana version chalu rakhne me kya problem hai?', a: 'Play Store update nahi karta, isliye purana build months tak chalta reh sakta hai. Phir jab kuch break hota hai to samajh nahi aata ki version hi reason hai.' },
      { q: 'APK verify kaise karte hain?', a: 'Download ke baad file ki details published release se match karo. Asli risk APK format nahi hai, risk mirror site se repackaged file download karna hai.' },
      { q: 'Update karne par account chala jaayega?', a: 'Nahi. Existing build ke upar install karo to session aur account preserve rehte hain.' },
      { q: 'is7gameapks.com par game khel sakte hain?', a: 'Nahi, yeh reference site hai. Yahan version history aur verification info milti hai, lobby nahi.' },
      { q: 'Install fail ho raha hai to kahan dekhein?', a: 'Install aur login failures ke liye 112gameapps.com dekho. Wahan Play Protect, OTP aur crash issues cover hain.' },
    ],
    alternatives: ['g112', 'mg7', 'mast79', 'xx7'],
    anchors: ['IS7 Game', 'is7gameapks.com', 'the IS7 APK library', 'IS7 Game APK', 'is7gameapks'],
  },

  {
    key: 'in7co',
    slug: 'in7-game-platform-overview',
    name: 'IN7 Game',
    domain: 'in7co.in',
    url: 'https://www.in7co.in',
    live: true,
    tagline: 'The platform this site is published on: ₹777 credit, 48 MB build, instant UPI payouts.',
    blurbHi: 'Yahi site jis par aap ho. ₹777 bonus aur instant UPI withdrawal.',
    bonus: '₹777 welcome bonus',
    apkSize: '48 MB',
    version: 'Latest 2026 build',
    android: 'Android 5.0+',
    payout: 'Instant UPI, PhonePe, Google Pay, Paytm, bank transfer',
    categories: ['Teen Patti', 'Andar Bahar', 'Slots', 'Spin wheel', 'Card games'],
    usp: 'The largest welcome credit in this network at ₹777, on the platform with the longest continuous operating record here.',
    intro: [
      'IN7 Game is the platform this site is published on, so treat this page as disclosure rather than a review. It carries a ₹777 welcome credit, a 48 MB Android build, and instant UPI payouts, and it is the platform every comparison on this site is written from experience with.',
      'The lobby covers Teen Patti, Andar Bahar, a slots catalogue, a daily spin wheel and general card games. What it is genuinely good at is the boring part: registration takes about a minute, the bonus applies without a promo code, and withdrawals leave for a real UPI handle rather than sitting in an in-app balance.',
      'If you want the full detail there are dedicated pages for the [download process](/in7-game-download), [registration](/how-to-register), the [app itself](/in7-game-app) and an [honest look at whether it is legitimate](/in7-game-real-or-fake). The sister address is [in7gaming.co](https://www.in7gaming.co), which runs the same lobby.',
    ],
    features: [
      { title: '₹777 welcome credit', desc: 'The largest signup credit across this whole network, applied automatically after number verification.' },
      { title: 'Instant UPI withdrawals', desc: 'Payouts to PhonePe, Google Pay, Paytm and bank accounts, typically settling within minutes.' },
      { title: '48 MB build', desc: 'Mid-sized install covering five game categories.' },
      { title: 'Daily spin and streak rewards', desc: 'A free daily spin plus a login streak that grows, so returning has value without spending.' },
      { title: 'Full Hindi interface', desc: 'Interface, help content and support all available in Hindi as well as English.' },
      { title: '24/7 in-app support', desc: 'Live chat inside the app rather than a phone number, available round the clock.' },
    ],
    steps: [
      'Open the [IN7 download page](/in7-game-download) on your Android phone.',
      'Tap the download button for the 48 MB APK.',
      'Approve the browser warning about the file.',
      'Allow installs from your browser under Settings, then Security.',
      'Install, then follow the [registration guide](/how-to-register). The ₹777 credit applies once your number is verified.',
    ],
    pros: [
      'Largest welcome credit in this network at ₹777',
      'Withdrawals go out to real UPI handles, typically within minutes',
      'Full Hindi interface rather than a partial translation',
      '24/7 in-app live chat support',
      'Longest continuous operating record of the platforms covered here',
    ],
    cons: [
      'Android only, with no native iOS build',
      'Not on the Play Store, so updates are manual',
      'This is the host platform of this site, so read the comparisons with that in mind',
    ],
    faqs: [
      { q: 'IN7 Game ka bonus kitna hai?', a: '₹777 welcome credit, jo number verify hone ke baad apne aap apply ho jaata hai. Koi promo code nahi chahiye.' },
      { q: 'IN7 se withdrawal kitni der me aata hai?', a: 'UPI withdrawals normally minutes me settle hote hain. PhonePe, Google Pay, Paytm aur bank transfer sab supported hain.' },
      { q: 'in7co.in aur in7gaming.co me farq?', a: 'Koi farq nahi. Dono official addresses hain aur same lobby chalate hain. Jo fast khule wahi use karo.' },
      { q: 'IN7 Game real hai ya fake?', a: 'IN7 live platform hai jo bonus credit karta hai aur UPI par payouts karta hai. Detail me poori honest breakdown /in7-game-real-or-fake page par hai.' },
      { q: 'IN7 APK ka size kitna hai?', a: '48 MB. Android 5.0 ya usse upar chahiye.' },
      { q: 'Support se kaise contact karein?', a: 'App ke andar Profile, phir Help ya Support me jaao aur live chat shuru karo. 24/7 available hai. Official support sirf app ke andar hai, WhatsApp ya Telegram par nahi.' },
    ],
    alternatives: ['in7gaming', 'ind9', 'inr360', 'xx7'],
    anchors: ['IN7 Game', 'in7co.in', 'the IN7 platform', 'IN7', 'IN7 Game APK'],
  },
];
