import type { TechArticle } from './tech-types';

/** Batch 1: site auditing, performance, SEO, security, accessibility, backlinks. */
export const tech1: TechArticle[] = [
  {
    slug: 'website-audit-checklist',
    title: 'Website Audit Checklist 2026 – 9 Things to Check First',
    h1: 'A website audit checklist that starts with what actually breaks',
    description: 'A practical website audit checklist covering crawling, speed, security, accessibility and backlinks, ordered by what causes the most damage.',
    excerpt: 'Most audit checklists are 80 items long and unordered. These nine come first, because they are what actually costs you traffic.',
    date: '2026-07-24',
    cat: 'SEO',
    readTime: '7 min',
    keywords: ['website audit checklist', 'seo audit 2026', 'site audit tool', 'website health check', 'free website audit'],
    targets: ['siteiq', 'seochecklist', 'speed', 'seo', 'home'],
    blocks: [
      { t: 'p', text: 'Website audit checklists have an inflation problem. Search for one and you get 80 items with no indication which of them matter, so people work top to bottom, fix seven trivial things, and never reach the one issue that was actually costing them traffic.' },
      { t: 'p', text: 'This is the short version, ordered by damage. If you only do the first three, you will have found most of what is wrong with a typical site.' },
      { t: 'h2', text: '1. Can Google actually crawl and index the pages?' },
      { t: 'p', text: 'Everything else is decorative if this is broken. A single misplaced line in robots.txt or a stray noindex tag left over from staging can remove an entire section from search, and nothing about the site will look wrong to you.' },
      { t: 'ul', items: [
        'Check robots.txt for blanket disallow rules that outlived their purpose.',
        'Search your templates for `noindex`. Staging leftovers are the classic cause.',
        'Confirm canonical tags point at the URL you want indexed, and not at a redirect.',
        'Compare your sitemap URL count against what Search Console reports as indexed.',
      ] },
      { t: 'note', kind: 'warn', text: 'A canonical tag pointing at a URL that then redirects is one of the most common and most invisible SEO faults. It looks correct in the source and quietly wastes crawl budget.' },
      { t: 'h2', text: '2. How slow is it, on a phone, on mobile data?' },
      { t: 'p', text: 'Not on your laptop on office wifi. Speed problems are almost always mobile problems, and the usual culprit is boring: oversized images. A 4000 pixel photo displayed in an 800 pixel slot wastes 80 percent of its bytes on every single visit.' },
      { t: 'p', text: '[CodeAiMan\'s website speed guide](https://codaiman.com/blog/how-to-improve-website-speed) works through the diagnosis properly, and [siteIQ](https://codaiman.com/siteiq) runs the performance test and tells you which assets are responsible rather than just handing you a score.' },
      { t: 'h2', text: '3. Is HTTPS correct everywhere, not just on the homepage?' },
      { t: 'p', text: 'Mixed content is the trap here. The page loads over HTTPS but pulls an image or a script over HTTP, and browsers either block it or flag the page as not fully secure. Users notice the warning long before you do.' },
      { t: 'h2', text: '4. Do the same page and its variants resolve to one URL?' },
      { t: 'p', text: 'A site reachable at four addresses is four sites as far as a crawler is concerned. Pick one canonical form and 301 the rest.' },
      { t: 'table', head: ['Variant', 'Should'], rows: [
        ['http://example.com', '301 to the canonical form'],
        ['http://www.example.com', '301 to the canonical form'],
        ['https://example.com', 'One of these is canonical'],
        ['https://www.example.com', 'The other 301s to it'],
        ['Trailing slash variants', 'Redirect consistently, one way'],
      ] },
      { t: 'h2', text: '5. Are titles and meta descriptions being truncated?' },
      { t: 'p', text: 'Titles get cut around 60 characters and descriptions around 155 to 160. Over the limit is not an error, it is silent truncation, usually mid-sentence in the search result where it does the most damage to your click-through rate.' },
      { t: 'h2', text: '6. Does it work with a keyboard?' },
      { t: 'p', text: 'Tab through the site without touching the mouse. If you cannot reach the navigation, submit the form, or see where focus currently is, the site is unusable for a real group of people and increasingly a legal exposure. Accessibility reporting is part of what [siteIQ](https://codaiman.com/siteiq) checks automatically.' },
      { t: 'h2', text: '7. What is linking to you, and is any of it toxic?' },
      { t: 'p', text: 'Backlinks are worth auditing in both directions. Losing a link that was driving traffic matters, and so does accumulating links from sites you would not want to be associated with. Automated [backlink analysis](https://codaiman.com/siteiq) makes this a five-minute job rather than a spreadsheet exercise.' },
      { t: 'h2', text: '8. Is structured data present and valid?' },
      { t: 'p', text: 'Invalid structured data is worse than none, because it can suppress the rich results you added it for. Validate rather than assume. The full list of what to check is in [CodeAiMan\'s technical SEO checklist](https://codaiman.com/blog/technical-seo-checklist-2026).' },
      { t: 'h2', text: '9. Are you measuring anything?' },
      { t: 'p', text: 'A surprising number of sites have analytics installed twice, or installed on the homepage only, or firing before consent in a way that invalidates the data. Verify that what you are looking at is real before you make decisions from it.' },
      { t: 'h2', text: 'Doing this without a spreadsheet' },
      { t: 'p', text: 'All nine can be checked by hand and it takes a couple of hours per site. Running them automatically takes minutes, which is the entire argument for using an audit tool: not that it finds things you could not, but that you will actually re-run it next month.' },
      { t: 'p', text: '[siteIQ](https://codaiman.com/siteiq) covers SEO analysis, performance testing, security checks, accessibility reports, backlink analysis and infrastructure insights in one pass. It is built by [CodeAiMan](https://codaiman.com), who also do this as a service through their [technical SEO practice](https://codaiman.com/services/seo-digital-marketing) if you would rather hand it over.' },
    ],
    faqs: [
      { q: 'Website audit me sabse pehle kya check karna chahiye?', a: 'Crawling aur indexing. Agar Google aapke pages crawl hi nahi kar pa raha to baaki sab fixes bekaar hain. robots.txt aur noindex tags pehle dekho.' },
      { q: 'Site slow hai, sabse common reason kya hota hai?', a: 'Almost hamesha oversized images. 4000 pixel ki photo jo 800 pixel me dikhti hai, wo 80 percent bytes waste karti hai, har visit par.' },
      { q: 'Canonical tag me kya galti common hai?', a: 'Canonical us URL par point karta hai jo phir redirect ho jaata hai. Source me sahi lagta hai lekin crawl budget waste karta hai. Ye sabse invisible fault hai.' },
      { q: 'Audit manually karein ya tool se?', a: 'Manually kar sakte ho, par per site do ghante lagte hain. Tool ka asli faayda ye hai ki aap next month dobara chala paoge. siteIQ ek pass me nau checks kar deta hai.' },
      { q: 'Backlink audit kyu zaruri hai?', a: 'Dono direction me. Jo link traffic de raha tha wo khona bura hai, aur aise sites se links jama hona bhi bura hai jinke saath aap associate nahi hona chahte.' },
      { q: 'Accessibility check kaise karein, sabse fast tarika?', a: 'Mouse chhodo aur sirf Tab se poori site navigate karo. Navigation reach nahi hui, form submit nahi hua, ya focus kahan hai pata nahi chala, to problem hai.' },
    ],
  },

  {
    slug: 'core-web-vitals-guide',
    title: 'Core Web Vitals Explained 2026 – LCP, INP, CLS in Plain English',
    h1: 'Core Web Vitals without the jargon: what each one measures and how to fix it',
    description: 'LCP, INP and CLS explained plainly, with the actual causes of each and the fixes that work. Thresholds and how to measure on real devices.',
    excerpt: 'Three metrics, three causes, three fixes. Once you know what each one is measuring, the fixes are surprisingly boring.',
    date: '2026-07-21',
    cat: 'Performance',
    readTime: '7 min',
    keywords: ['core web vitals', 'lcp inp cls', 'improve page speed', 'web vitals 2026', 'website performance'],
    targets: ['siteiq', 'speed', 'web', 'home', 'cloud'],
    blocks: [
      { t: 'p', text: 'Core Web Vitals get treated as a mysterious Google requirement, and they are not. They are three measurements of things users genuinely complain about: the page took too long to show anything, it did not respond when I tapped, and it moved while I was reading it.' },
      { t: 'p', text: 'Understand what each one is actually measuring and the fixes become obvious and quite dull.' },
      { t: 'h2', text: 'LCP: how long until the main thing appears' },
      { t: 'p', text: 'Largest Contentful Paint measures when the biggest element in the viewport finishes rendering. Usually that is a hero image or a block of heading text. It is the closest metric to "did the page feel like it loaded".' },
      { t: 'p', text: 'The cause is nearly always one of three things: an oversized hero image, a slow server response, or a render-blocking resource in the head. In that order of likelihood.' },
      { t: 'ul', items: [
        '**Oversized hero image.** Resize it to display dimensions, convert to WebP, and preload it. This alone fixes most LCP failures.',
        '**Slow server response.** If the HTML takes 800ms to arrive, nothing you do in the browser saves you. This is an infrastructure problem.',
        '**Render-blocking CSS or fonts.** Inline critical CSS and let fonts swap rather than block.',
      ] },
      { t: 'h2', text: 'INP: how long until the page responds to a tap' },
      { t: 'p', text: 'Interaction to Next Paint replaced First Input Delay and measures something more honest: across the whole visit, how long does the page take to visibly respond when the user interacts. A page can load fast and still fail this badly.' },
      { t: 'p', text: 'The cause is almost always JavaScript occupying the main thread. Too much of it, running for too long, in one uninterrupted block. Splitting long tasks and deferring work that does not need to happen during load is the fix.' },
      { t: 'h2', text: 'CLS: how much the page moves while you read it' },
      { t: 'p', text: 'Cumulative Layout Shift measures unexpected movement. Everyone has experienced this: you go to tap a link, an ad or an image finishes loading above it, everything jumps, and you tap the wrong thing.' },
      { t: 'p', text: 'The fix is genuinely simple and widely skipped: **reserve space for anything that loads late.** Width and height attributes on images. Fixed dimensions for ad slots and embeds. Never insert content above existing content after load.' },
      { t: 'table', head: ['Metric', 'Good', 'Needs work', 'Usual cause'], rows: [
        ['LCP', 'Under 2.5s', 'Over 4s', 'Oversized hero image'],
        ['INP', 'Under 200ms', 'Over 500ms', 'Too much JavaScript on the main thread'],
        ['CLS', 'Under 0.1', 'Over 0.25', 'Images and ads without reserved space'],
      ] },
      { t: 'h2', text: 'Lab data versus real users' },
      { t: 'p', text: 'This distinction matters and trips people up. A synthetic test runs on one machine on one connection and gives you a repeatable number you can debug against. Field data comes from actual visitors on actual devices, and it is what Google uses.' },
      { t: 'p', text: 'You need both. Lab data to iterate quickly, field data to know whether it mattered. [siteIQ](https://codaiman.com/siteiq) runs the performance testing side and identifies which specific assets are hurting each metric, which is the part a bare score never tells you.' },
      { t: 'note', kind: 'ok', text: 'If you do exactly two things: resize and convert your images, and add width and height attributes to every image tag, you will fix most LCP and most CLS problems on a typical site. Neither requires a rebuild.' },
      { t: 'h2', text: 'When it is not a front-end problem' },
      { t: 'p', text: 'Sometimes the HTML itself is slow to arrive, and no amount of image optimisation helps. That points at hosting, database queries, or missing caching, and it needs infrastructure work rather than front-end work. [CodeAiMan\'s cloud and DevOps practice](https://codaiman.com/services/cloud-devops) handles that end, and their [website speed guide](https://codaiman.com/blog/how-to-improve-website-speed) covers the diagnosis.' },
      { t: 'p', text: 'For sites being built rather than fixed, getting this right from the start is far cheaper. [CodeAiMan\'s web development team](https://codaiman.com/services/web-development) builds in Next.js and React with these constraints assumed rather than retrofitted.' },
    ],
    faqs: [
      { q: 'LCP kharab hai, sabse pehle kya theek karun?', a: 'Hero image. Usko display size par resize karo, WebP me convert karo, aur preload karo. Zyadatar LCP failures isi se theek ho jaate hain.' },
      { q: 'INP kya hai, FID se kya farq hai?', a: 'FID sirf pehle interaction ka delay dekhta tha. INP poori visit ke interactions dekhta hai, jo zyada honest measurement hai. Cause usually main thread par bahut zyada JavaScript hota hai.' },
      { q: 'CLS fix karne ka sabse aasan tarika?', a: 'Har image tag par width aur height attributes lagao, aur ads ya embeds ke liye fixed dimensions reserve karo. Late load hone wali cheez ke liye jagah pehle se rakho.' },
      { q: 'Lab data aur field data me kaunsa important hai?', a: 'Dono. Lab data se aap fast iterate karte ho, field data batata hai ki asli users ko farq pada ya nahi. Google field data use karta hai.' },
      { q: 'Images optimize kar li phir bhi slow hai. Kya karun?', a: 'HTML khud slow aa raha hoga. Wo hosting, database queries ya missing caching ka issue hai, front-end ka nahi. Infrastructure side dekho.' },
      { q: 'Good LCP kitna hona chahiye?', a: '2.5 seconds se kam good hai, 4 seconds se zyada poor. INP 200ms se kam, aur CLS 0.1 se kam.' },
    ],
  },

  {
    slug: 'technical-seo-basics',
    title: 'Technical SEO Basics 2026 – The Foundation Before Content',
    h1: 'Technical SEO: the foundation that makes content work',
    description: 'Technical SEO explained from the ground up: crawling, indexing, site structure, canonicals, sitemaps and structured data, with the common faults.',
    excerpt: 'Content cannot rank on pages Google will not index. Technical SEO is the part that has to be right first.',
    date: '2026-07-19',
    cat: 'SEO',
    readTime: '7 min',
    keywords: ['technical seo', 'seo basics 2026', 'crawling and indexing', 'sitemap seo', 'canonical tags'],
    targets: ['seochecklist', 'siteiq', 'seo', 'web', 'home'],
    blocks: [
      { t: 'p', text: 'Technical SEO has an unglamorous reputation and an unarguable position: it comes first. You can write the best page on a subject and it will rank nowhere if the page is not indexed, or if it is competing with three duplicate versions of itself, or if it takes nine seconds to load on a phone.' },
      { t: 'p', text: 'None of it is complicated. Most of it is a handful of things being correct and staying correct.' },
      { t: 'h2', text: 'Crawling: can a bot reach the page?' },
      { t: 'p', text: 'A crawler follows links. If a page has no internal links pointing at it and is not in the sitemap, it is effectively invisible regardless of how good it is. Orphan pages are more common than people expect, especially on sites that have been through a redesign.' },
      { t: 'ul', items: [
        'Every page worth ranking needs at least one internal link from a page that is itself indexed.',
        'robots.txt should block admin paths and nothing else, unless you have a specific reason.',
        'Navigation that only exists in JavaScript is riskier than plain links. Use real anchors.',
        'Redirect chains waste crawl budget. Point A directly at C, not at B which points at C.',
      ] },
      { t: 'h2', text: 'Indexing: will Google keep the page?' },
      { t: 'p', text: 'Crawled is not indexed. Google crawls a page, decides whether it is worth storing, and often decides no. The usual reasons are thin content, near-duplication of another page, or contradictory signals about which URL is canonical.' },
      { t: 'note', kind: 'warn', text: 'The most common indexing fault is a canonical tag pointing at a URL that redirects somewhere else. It looks perfectly correct in the page source, which is exactly why it survives for months.' },
      { t: 'h2', text: 'One page, one URL' },
      { t: 'p', text: 'Duplication is usually accidental. The same content reachable with and without www, with and without a trailing slash, with tracking parameters attached, and via a print version, is five URLs for one page. Pick one, canonicalise to it, and 301 the rest.' },
      { t: 'h2', text: 'Site structure: shallow beats deep' },
      { t: 'p', text: 'Important pages should be reachable in a small number of clicks from the homepage. This is not a rule Google published, it is a consequence of how link authority flows: a page buried six levels deep receives very little of it.' },
      { t: 'table', head: ['Depth from homepage', 'Practical effect'], rows: [
        ['1 click', 'Strongest internal authority'],
        ['2 to 3 clicks', 'Fine for most content'],
        ['4 to 5 clicks', 'Noticeably weaker, crawled less often'],
        ['6+ clicks', 'Often ignored entirely'],
      ] },
      { t: 'h2', text: 'Sitemaps: a list, not a magic wand' },
      { t: 'p', text: 'A sitemap tells Google what exists. It does not force indexing and it does not make thin pages rank. What it does do is surface pages that are weakly linked, and reveal a gap when the URL count in your sitemap does not match what Search Console reports as indexed.' },
      { t: 'p', text: 'Keep it clean: only canonical, indexable, 200-status URLs. A sitemap full of redirects and 404s is a signal about how carefully the site is maintained.' },
      { t: 'h2', text: 'Structured data: help Google understand, do not lie to it' },
      { t: 'p', text: 'Structured data describes what a page is: an article, a product, a FAQ, a recipe. Done well, it earns richer search results. Done badly it does nothing, and done dishonestly, marking up reviews that do not exist for instance, it earns a penalty.' },
      { t: 'p', text: 'Validate it rather than trusting that it works. [CodeAiMan\'s technical SEO checklist for 2026](https://codaiman.com/blog/technical-seo-checklist-2026) covers the full list including which schema types are worth the effort.' },
      { t: 'h2', text: 'Keeping it correct over time' },
      { t: 'p', text: 'This is the real problem. A site can be technically clean at launch and broken six months later, because someone added a plugin, changed a template, or migrated a section. Nothing announces itself.' },
      { t: 'p', text: 'That is the argument for automated auditing. [siteIQ](https://codaiman.com/siteiq) covers crawling, indexing, performance, security and accessibility in one pass, so re-checking monthly is realistic instead of aspirational. If you would rather not own it at all, [CodeAiMan\'s SEO practice](https://codaiman.com/services/seo-digital-marketing) does it as a service, and their [web development team](https://codaiman.com/services/web-development) builds sites with these foundations in place from the start.' },
    ],
    faqs: [
      { q: 'Technical SEO pehle karein ya content?', a: 'Technical pehle. Best content bhi rank nahi karega agar page index nahi hai ya apne teen duplicates se compete kar raha hai.' },
      { q: 'Orphan page kya hai aur kaise pata chalega?', a: 'Jis page par koi internal link nahi jaata. Wo crawler ke liye invisible hai. Sitemap URL count ko Search Console ke indexed count se compare karo, gap wahi dikhata hai.' },
      { q: 'Crawled but not indexed ka matlab kya hai?', a: 'Google ne page dekha aur store karne layak nahi samjha. Usually thin content, near-duplicate, ya canonical signals ka conflict hota hai.' },
      { q: 'Sitemap se ranking improve hoti hai?', a: 'Nahi. Sitemap sirf batata hai ki kya exist karta hai. Wo indexing force nahi karta aur thin pages ko rank nahi karata. Usme sirf canonical, indexable, 200-status URLs rakho.' },
      { q: 'Site structure kitni deep honi chahiye?', a: 'Important pages homepage se 2 se 3 clicks me reachable hone chahiye. 6 clicks deep pages aksar ignore ho jaate hain.' },
      { q: 'Structured data galat ho to kya hota hai?', a: 'Invalid structured data kuch nahi karta, aur dishonest structured data (jaise fake reviews mark karna) penalty la sakta hai. Validate karo, assume mat karo.' },
    ],
  },

  {
    slug: 'website-security-basics',
    title: 'Website Security Basics 2026 – The Checks That Actually Matter',
    h1: 'Website security basics: what to check before something goes wrong',
    description: 'Practical website security checks: HTTPS and mixed content, security headers, dependency updates, secrets handling and access control.',
    excerpt: 'Most small-site breaches are not clever attacks. They are outdated dependencies and a leaked key in a repository.',
    date: '2026-07-17',
    cat: 'Security',
    readTime: '6 min',
    keywords: ['website security checklist', 'security headers', 'https mixed content', 'website vulnerability check'],
    targets: ['siteiq', 'cloud', 'home', 'web'],
    blocks: [
      { t: 'p', text: 'Website security discussions tend to jump straight to sophisticated attacks, which is not where the risk is for most sites. The overwhelming majority of small and mid-sized site compromises come from two mundane causes: a dependency that was not updated, and a credential that ended up somewhere public.' },
      { t: 'p', text: 'So this is the boring list, which is the useful one.' },
      { t: 'h2', text: 'HTTPS everywhere, and no mixed content' },
      { t: 'p', text: 'HTTPS on the homepage is not the same as HTTPS on the site. Mixed content, where a secure page pulls an image, script or stylesheet over plain HTTP, either gets blocked by the browser or triggers a security warning users definitely notice.' },
      { t: 'ul', items: [
        'Redirect all HTTP traffic to HTTPS at the server, not in JavaScript.',
        'Search your codebase for `http://` in asset URLs.',
        'Check third-party embeds, which are a common source of mixed content.',
        'Set HSTS once you are confident HTTPS works everywhere.',
      ] },
      { t: 'h2', text: 'Security headers, which cost nothing' },
      { t: 'p', text: 'A handful of response headers meaningfully reduce your exposure and take minutes to add. They are skipped mostly because nobody checks for them.' },
      { t: 'table', head: ['Header', 'What it prevents'], rows: [
        ['Content-Security-Policy', 'Injected scripts running'],
        ['X-Content-Type-Options: nosniff', 'Browsers guessing file types wrongly'],
        ['Strict-Transport-Security', 'Downgrade to HTTP'],
        ['Referrer-Policy', 'Leaking URLs to third parties'],
        ['X-Frame-Options / frame-ancestors', 'Your site being framed for clickjacking'],
      ] },
      { t: 'h2', text: 'Update your dependencies' },
      { t: 'p', text: 'This is the single highest-value security habit and the most commonly neglected. Known vulnerabilities in popular packages get published, then scanned for automatically at scale. You are not being targeted; you are being swept up.' },
      { t: 'note', kind: 'warn', text: 'A site running a two-year-old CMS or an unpatched framework is not at risk of a clever attack. It is at risk of an automated one that requires no skill and finds you within days of a disclosure.' },
      { t: 'h2', text: 'Keep secrets out of the repository' },
      { t: 'p', text: 'API keys, database passwords and tokens committed to a repository are a persistent problem, and deleting them later does not help because git keeps history. Use environment variables and a secrets manager, and if something did get committed, rotate the key rather than just removing the line.' },
      { t: 'p', text: 'Worth restating a related point: Base64 encoding is not encryption. Encoding a secret does not protect it, since anyone can decode it instantly.' },
      { t: 'h2', text: 'Password storage, if you handle accounts' },
      { t: 'p', text: 'Plain hashes are the wrong tool. MD5 and SHA-1 are broken, and even SHA-256 is unsuitable because it is fast, and fast is what an attacker wants when testing billions of guesses. Use bcrypt or Argon2, which are deliberately slow.' },
      { t: 'h2', text: 'Access control and backups' },
      { t: 'p', text: 'Two things people postpone until they matter enormously. Remove accounts for people who have left. Use least privilege rather than giving everyone admin. And test that your backups actually restore, because an untested backup is a belief, not a backup.' },
      { t: 'h2', text: 'Automating the check' },
      { t: 'p', text: 'Every item above can be verified by hand, and none of them will be verified by hand a second time. [siteIQ](https://codaiman.com/siteiq) includes security checks alongside its SEO, performance and accessibility auditing, which makes a monthly re-check realistic.' },
      { t: 'p', text: 'For the infrastructure side, secrets management, hardened deployments, CI/CD that does not leak credentials, [CodeAiMan\'s cloud and DevOps practice](https://codaiman.com/services/cloud-devops) covers it, and [CodeAiMan](https://codaiman.com) builds these defaults into new projects rather than adding them after an incident.' },
    ],
    faqs: [
      { q: 'Chhoti website hack kaise hoti hai usually?', a: 'Clever attack se nahi. Do mundane reasons: outdated dependency, aur repository me leak hui credential. Automated scanners disclosure ke kuch din me hi mil jaate hain.' },
      { q: 'Mixed content kya hai?', a: 'HTTPS page jo koi image, script ya stylesheet HTTP par load karta hai. Browser use block karta hai ya security warning dikhata hai. Codebase me http:// asset URLs search karo.' },
      { q: 'Security headers zaruri hain?', a: 'Haan, aur minutes lagte hain. CSP, nosniff, HSTS, Referrer-Policy aur frame-ancestors. Skip hote hain kyunki koi check nahi karta.' },
      { q: 'API key galti se commit ho gayi, line delete kar dun?', a: 'Kaafi nahi. Git history me rehti hai. Key rotate karo, sirf line hatana bekaar hai.' },
      { q: 'Password SHA-256 se hash karna theek hai?', a: 'Nahi. SHA-256 fast hai, aur attacker ko fast hi chahiye. bcrypt ya Argon2 use karo, jo jaan-boojh kar slow hain.' },
      { q: 'Backup hai, kaafi hai?', a: 'Nahi. Untested backup ek belief hai, backup nahi. Restore karke test karo, warna zarurat ke waqt pata chalega ki kaam nahi karta.' },
    ],
  },

  {
    slug: 'website-accessibility-basics',
    title: 'Website Accessibility Basics – Six Fixes With Real Impact',
    h1: 'Accessibility basics: six fixes that cover most of the problem',
    description: 'Practical web accessibility: keyboard navigation, contrast, alt text, form labels, focus states and heading structure, with how to test each.',
    excerpt: 'Accessibility sounds like a large project. Six specific fixes cover most of what actually blocks people.',
    date: '2026-07-14',
    cat: 'Engineering',
    readTime: '6 min',
    keywords: ['website accessibility', 'wcag basics', 'accessible website checklist', 'keyboard navigation', 'alt text'],
    targets: ['siteiq', 'uiux', 'web', 'home'],
    blocks: [
      { t: 'p', text: 'Accessibility gets treated as a specialist compliance project, and that framing is why it never gets started. In practice, a small number of specific issues account for most of what genuinely blocks people from using a site, and each has a clear fix.' },
      { t: 'p', text: 'Here are six, with how to test each one yourself in a few minutes.' },
      { t: 'h2', text: '1. Keyboard navigation' },
      { t: 'p', text: 'Put the mouse aside and use Tab, Shift-Tab and Enter to get through the site. Can you reach the navigation? Open the menu? Fill and submit the form? Close a modal?' },
      { t: 'p', text: 'Custom components are the usual failure: a div styled as a button is not focusable and does not respond to Enter. Use real `button` and `a` elements, and the behaviour comes free.' },
      { t: 'h2', text: '2. Visible focus states' },
      { t: 'p', text: 'A very common and very damaging fix-that-broke-things: someone removed the focus outline because it looked untidy. Now a keyboard user has no idea where they are on the page. If you do not like the default, replace it with something better. Do not delete it.' },
      { t: 'h2', text: '3. Colour contrast' },
      { t: 'p', text: 'Light grey text on white is the signature of a design that was reviewed on one good monitor in a dim room. It fails outdoors, on cheap screens, and for anyone with reduced vision, which is a large and growing group.' },
      { t: 'table', head: ['Content', 'Minimum contrast ratio'], rows: [
        ['Body text', '4.5 : 1'],
        ['Large text, 18pt and above', '3 : 1'],
        ['Interface components and icons', '3 : 1'],
        ['Decorative only', 'No requirement'],
      ] },
      { t: 'h2', text: '4. Alt text that says something' },
      { t: 'p', text: 'Alt text describes what the image conveys, not what it literally contains. "Chart showing sales doubling between March and June" is useful. "chart.png" is not. And genuinely decorative images should have empty alt text so screen readers skip them rather than announcing noise.' },
      { t: 'h2', text: '5. Form labels' },
      { t: 'p', text: 'Placeholder text is not a label. It disappears the moment someone types, it often fails contrast requirements, and screen readers do not treat it as a label. Use a real `label` element associated with the input. This is also the single most common accessibility fault on business websites.' },
      { t: 'note', kind: 'ok', text: 'Proper labels also help users who are not disabled at all. Everyone has filled a form, been interrupted, and come back to four boxes with no idea what any of them wanted.' },
      { t: 'h2', text: '6. Heading structure' },
      { t: 'p', text: 'Headings are a document outline, not a font size menu. One h1, then h2 for sections, h3 for subsections, in order. Screen reader users navigate by heading, so skipping from h1 to h4 because it looked right removes their primary way of moving through the page.' },
      { t: 'h2', text: 'What automated testing can and cannot tell you' },
      { t: 'p', text: 'Be clear about the limits. Automated tools reliably catch contrast failures, missing alt attributes, missing labels and heading order problems. They cannot tell you whether your alt text is meaningful or whether a custom component makes sense to a screen reader user. Those need a human.' },
      { t: 'p', text: 'So use both. [siteIQ](https://codaiman.com/siteiq) produces accessibility reports as part of its audit pass, which handles the mechanical checks, and then you test the keyboard path yourself. For design work where accessibility is built in rather than retrofitted, [CodeAiMan\'s UI/UX team](https://codaiman.com/services/ui-ux-design) works with contrast and focus requirements as constraints from the start, and their [web development practice](https://codaiman.com/services/web-development) implements them.' },
    ],
    faqs: [
      { q: 'Accessibility test karne ka sabse fast tarika?', a: 'Mouse chhodo aur sirf Tab, Shift-Tab aur Enter se poori site use karo. Navigation, menu, form aur modal, sab reachable hone chahiye.' },
      { q: 'Focus outline hata dena theek hai, ugly lagta hai?', a: 'Nahi. Uske bina keyboard user ko pata hi nahi chalta wo kahan hai. Default pasand nahi to better design karo, delete mat karo.' },
      { q: 'Contrast ratio kitna hona chahiye?', a: 'Body text ke liye 4.5:1, bade text (18pt+) aur interface components ke liye 3:1. Light grey on white almost hamesha fail karta hai.' },
      { q: 'Placeholder ko label ki tarah use kar sakte hain?', a: 'Nahi. Type karte hi gayab ho jaata hai, contrast fail karta hai, aur screen readers use label nahi maante. Business websites par ye sabse common fault hai.' },
      { q: 'Alt text me kya likhna chahiye?', a: 'Image kya convey karti hai, wo. "Chart showing sales doubling between March and June" useful hai, "chart.png" nahi. Decorative images ka alt empty rakho.' },
      { q: 'Automated accessibility tool kaafi hai?', a: 'Nahi. Wo contrast, missing alt, missing labels aur heading order pakad leta hai. Lekin alt text meaningful hai ya nahi, ye insaan hi bata sakta hai.' },
    ],
  },

  {
    slug: 'backlink-audit-guide',
    title: 'Backlink Audit Guide 2026 – What to Keep, Watch and Disavow',
    h1: 'Auditing your backlinks: what to keep, what to watch, what to worry about',
    description: 'How to audit a backlink profile: relevance, anchor text distribution, footprint signals, lost links and when disavowing is the wrong move.',
    excerpt: 'A backlink profile is judged on pattern, not count. Here is what patterns look natural and what does not.',
    date: '2026-07-11',
    cat: 'SEO',
    readTime: '7 min',
    keywords: ['backlink audit', 'toxic backlinks', 'anchor text distribution', 'disavow links', 'backlink analysis tool'],
    targets: ['siteiq', 'seo', 'seochecklist', 'home'],
    blocks: [
      { t: 'p', text: 'Backlink conversations get stuck on volume, and volume is the least interesting property of a link profile. What matters is pattern: where links come from, whether the sources make sense, and whether the whole thing looks like something that happened or something that was manufactured.' },
      { t: 'h2', text: 'Relevance is the first filter' },
      { t: 'p', text: 'A link from a site in your subject area carries weight because it is a plausible recommendation. A link from a site with no topical connection carries much less, and a large number of them from unrelated sources reads as manufactured, because it usually is.' },
      { t: 'p', text: 'This is the reason link building on unrelated properties disappoints people. It is not that the links are ignored, it is that a pattern of irrelevant links is itself a signal.' },
      { t: 'h2', text: 'Anchor text distribution' },
      { t: 'p', text: 'A natural profile has messy anchor text. People link using your brand name, your bare domain, the page title, or something functional like "this guide" and "here". What a natural profile does not have is four hundred links all using the same commercial keyword.' },
      { t: 'table', head: ['Anchor type', 'Roughly what natural looks like'], rows: [
        ['Brand name', 'A large share'],
        ['Bare URL or domain', 'A meaningful share'],
        ['Page title or descriptive phrase', 'A meaningful share'],
        ['Generic: "here", "this guide"', 'A visible share'],
        ['Exact commercial keyword', 'A small minority'],
      ] },
      { t: 'note', kind: 'warn', text: 'Identical anchor text repeated at scale is the single clearest footprint there is. If you are building links deliberately, varying the anchor is not an optimisation, it is the difference between a profile that looks earned and one that does not.' },
      { t: 'h2', text: 'Footprint signals worth checking on your own profile' },
      { t: 'ul', items: [
        '**Site-wide footer links.** A link on every page of another site is one endorsement repeated, and it is discounted accordingly. A handful is normal; a footer full of them is not.',
        '**Same-owner networks.** A cluster of sites on the same hosting, same template and same registration details, all linking to each other, is detectable and is a link scheme.',
        '**Sudden volume spikes.** A profile that gains hundreds of links in a week without a corresponding reason invites scrutiny.',
        '**No editorial context.** Links sitting in a list rather than inside real content read as placements, because they are.',
      ] },
      { t: 'h2', text: 'Lost links matter as much as toxic ones' },
      { t: 'p', text: 'Audits fixate on bad links and ignore the more common problem: links you had and lost. A page that linked to you got rewritten, or 404ed, or the site went down. That is a direct loss of something you already earned, and it is usually recoverable with a polite email.' },
      { t: 'h2', text: 'When to disavow, which is rarely' },
      { t: 'p', text: 'Disavowing is over-recommended. Google is reasonably good at ignoring obvious junk on its own, and disavowing links that were doing nothing achieves nothing while risking removing something that was helping.' },
      { t: 'p', text: 'The genuine cases are narrow: you have a manual action, or you know a previous agency built spam at scale on your behalf. Absent one of those, auditing and ignoring is usually the right call.' },
      { t: 'h2', text: 'Doing the audit' },
      { t: 'p', text: 'Checking relevance, anchor distribution and lost links by hand across a real profile is a spreadsheet exercise measured in hours. [siteIQ](https://codaiman.com/siteiq) includes backlink analysis alongside its SEO, performance, security and accessibility checks, which is what makes re-running the audit quarterly realistic.' },
      { t: 'p', text: 'If you want the strategy rather than the data, [CodeAiMan\'s SEO and digital marketing practice](https://codaiman.com/services/seo-digital-marketing) covers link and content strategy together, and their [technical SEO checklist](https://codaiman.com/blog/technical-seo-checklist-2026) covers the on-site half that a link profile cannot compensate for.' },
    ],
    faqs: [
      { q: 'Backlinks me count important hai ya quality?', a: 'Pattern important hai. Kahan se aa rahe hain, source topically relevant hai ya nahi, aur poora profile earned lagta hai ya manufactured.' },
      { q: 'Anchor text kaisa hona chahiye?', a: 'Messy. Brand name, bare domain, page title aur generic phrases ka mix. Jo natural nahi lagta wo hai: 400 links same commercial keyword par.' },
      { q: 'Site-wide footer links kaam karte hain?', a: 'Heavily discounted hote hain. Ek link har page par ek hi endorsement hai, repeat hua. Thode normal hain, footer bhar ke nahi.' },
      { q: 'Apni hi websites ko aapas me link karna theek hai?', a: 'Same hosting, same template aur same registration wale sites ka cluster jo ek doosre ko link kare, detectable hai aur link scheme me aata hai.' },
      { q: 'Toxic links disavow karne chahiye?', a: 'Aksar nahi. Google obvious junk ignore kar leta hai. Disavow sirf tab jab manual action ho ya pata ho ki kisi agency ne scale par spam banaya tha.' },
      { q: 'Lost backlinks ka kya karein?', a: 'Wo zyada common problem hai. Jo page link kar raha tha wo rewrite ya 404 ho gaya. Ek polite email se aksar recover ho jaata hai.' },
    ],
  },
];
