import type { Tool } from './tool-types';

/** Batch 2: video, audio, text and developer tools. */
export const tools2: Tool[] = [
  {
    slug: 'compress-video',
    name: 'Compress Video',
    cat: 'Video',
    title: 'Compress Video Online Free – Smaller Files, Watchable Quality',
    h1: 'Compressing video: bitrate is the setting that matters',
    description: 'Compress video in the browser. Why bitrate matters more than resolution, realistic size targets, and what to do about WhatsApp limits.',
    excerpt: 'Everyone reaches for resolution first. Bitrate is what actually controls the file size.',
    what: [
      'Video compression confuses people because there are three knobs and only one of them usually needs turning. Resolution is how many pixels. Frame rate is how many images per second. **Bitrate** is how much data is spent per second of video, and it is the one that decides file size.',
      'Drop a 1080p clip from a high bitrate to a moderate one and the file halves with barely any visible difference on a phone screen. Drop the resolution to 480p instead and it looks obviously worse while saving less than you expected. Start with bitrate. The compressor is in [ToolHub](https://codaiman.com/toolhub).',
    ],
    steps: [
      'Note your target size. WhatsApp caps around 16 MB for video, email attachments usually 25 MB.',
      'Open the video compressor in [ToolHub](https://codaiman.com/toolhub).',
      'Reduce bitrate first, keeping the resolution. This is where the saving is.',
      'Only reduce resolution if bitrate alone did not get you there, and only to 720p rather than lower.',
      'Watch ten seconds of the output on the device it is meant for. A phone hides compression that a monitor exposes.',
    ],
    specs: [
      ['Main control', 'Bitrate, not resolution'],
      ['Output format', 'MP4 with H.264, the widest compatibility'],
      ['WhatsApp limit', 'Around 16 MB'],
      ['Screen recordings', 'Compress very well, being mostly static'],
      ['Reversible', 'No. Keep the original'],
    ],
    problems: [
      { q: 'Video compress karne par bahut blurry ho gaya.', a: 'Aapne resolution girayi hai, bitrate nahi. Original se dobara shuru karo, resolution wahi rakho aur bitrate kam karo. Farq bahut kam dikhega aur size aadha ho jaayega.' },
      { q: 'WhatsApp par video nahi ja rahi.', a: 'WhatsApp ka limit around 16 MB hai. Bitrate kam karo aur zarurat pade to 720p par aao. Ya video ko trim karke chhota karo.' },
      { q: 'Screen recording ka size bahut bada hai.', a: 'Screen recordings mostly static hoti hain, isliye ye sabse aasan case hai. Bitrate aggressively kam kar sakte ho, quality par asar minimal rahega.' },
    ],
    tips: [
      'Trim before you compress. Removing ten seconds of nothing beats compressing them.',
      'H.264 MP4 plays everywhere. Fancier codecs save space and then fail to open on someone\'s device.',
      'For anything hosted on a website, video should be served from proper infrastructure rather than uploaded as a file. CodeAiMan\'s [cloud and DevOps team](https://codaiman.com/services/cloud-devops) handles that kind of setup.',
    ],
    related: ['trim-video', 'convert-video-to-mp4', 'video-to-gif'],
    target: 'cloud',
    keywords: ['compress video online', 'reduce video size', 'video compressor free', 'compress mp4', 'video size reducer'],
  },

  {
    slug: 'convert-video-to-mp4',
    name: 'Convert Video to MP4',
    cat: 'Video',
    title: 'Convert Video to MP4 Online Free – The Format That Just Works',
    h1: 'Converting video to MP4, and why it is almost always the right answer',
    description: 'Convert MOV, AVI, MKV and WebM to MP4 in the browser. Container versus codec explained, and why MP4 with H.264 has the widest support.',
    excerpt: 'MOV, AVI, MKV all play somewhere. MP4 with H.264 plays everywhere. That is the whole reason for this conversion.',
    what: [
      'A video file has two parts people conflate: the **container** (MP4, MOV, AVI, MKV) which is the wrapper, and the **codec** (H.264, H.265, VP9) which is how the picture is actually encoded. A file can be an MP4 and still fail to play if the codec inside is unusual.',
      'MP4 with H.264 is the combination with the broadest support anywhere: every browser, every phone, every editor, every upload form. That is why converting to it solves so many playback problems. The converter is in the [ToolHub](https://codaiman.com/toolhub) video section.',
    ],
    steps: [
      'Open the video converter in [ToolHub](https://codaiman.com/toolhub) and upload your file.',
      'Choose MP4 as the output container.',
      'Choose H.264 as the codec if you are offered the choice. H.265 is smaller but less compatible.',
      'Keep the original resolution unless you also need a smaller file.',
      'Test the output where it failed before. That is the only test that matters here.',
    ],
    specs: [
      ['Common inputs', 'MOV, AVI, MKV, WebM, FLV'],
      ['Output', 'MP4'],
      ['Best codec for compatibility', 'H.264'],
      ['Smaller but pickier', 'H.265 / HEVC'],
      ['Quality', 'Re-encoded, so keep the original'],
    ],
    problems: [
      { q: 'File MP4 hai lekin play nahi ho rahi.', a: 'Container MP4 hai lekin andar ka codec unusual hoga. H.264 me re-encode karo, phir har jagah chalegi.' },
      { q: 'iPhone ki MOV file Windows par nahi khulti.', a: 'MOV Apple ka container hai. MP4 me convert karo, Windows par bina kisi extra software ke chal jaayegi.' },
      { q: 'Convert karne se quality girti hai?', a: 'Haan, thodi. Re-encoding lossy hoti hai. Isliye original rakho aur ek hi baar convert karo, baar baar nahi.' },
    ],
    tips: [
      'Convert once, from the original. Converting a converted file compounds the quality loss.',
      'If a file needs to work for someone else, MP4 with H.264 removes the argument.',
      'H.265 is worth it only when you control every device that will play the file.',
    ],
    related: ['compress-video', 'trim-video', 'extract-audio-from-video'],
    target: 'toolhub',
    keywords: ['convert video to mp4', 'mov to mp4', 'avi to mp4 converter', 'mkv to mp4 online free'],
  },

  {
    slug: 'trim-video',
    name: 'Trim Video',
    cat: 'Video',
    title: 'Trim Video Online Free – Cut the Start and End Precisely',
    h1: 'Trimming video: the cheapest way to shrink a file',
    description: 'Trim video start and end points in the browser. Frame accuracy, keyframe limitations, and why trimming beats compressing.',
    excerpt: 'Cutting dead footage reduces file size with zero quality loss. Compression cannot say the same.',
    what: [
      'Trimming is the most underrated video operation because it is the only one that reduces file size without touching quality. Most clips have several seconds of nothing at each end: the fumble before recording starts properly, the reach for the stop button at the end. Cutting those is free.',
      'The one technical wrinkle: fast trimming cuts at keyframes, which occur every few seconds, so your cut may land slightly off from where you asked. Frame-accurate trimming re-encodes that section to hit the exact point. Fast is fine for most purposes. [ToolHub](https://codaiman.com/toolhub) handles both.',
    ],
    steps: [
      'Open the video trimmer in [ToolHub](https://codaiman.com/toolhub) and load your clip.',
      'Set the start point after the dead footage, not at zero.',
      'Set the end point before the fumble at the end.',
      'Preview both edges. Cuts almost always need one adjustment.',
      'Export. Trim before compressing if you plan to do both.',
    ],
    specs: [
      ['Quality loss', 'None, with a fast keyframe trim'],
      ['Cut precision', 'Keyframe-aligned unless re-encoding'],
      ['Order', 'Trim first, then compress'],
      ['Output', 'Same format as the input'],
      ['Multiple segments', 'Trim repeatedly, then join'],
    ],
    problems: [
      { q: 'Cut exactly wahan nahi laga jahan set kiya tha.', a: 'Fast trim keyframes par cut karta hai, jo har kuch seconds me aate hain. Exact point chahiye to frame-accurate mode chuno, wo us hisse ko re-encode karta hai.' },
      { q: 'Trim karne se quality girti hai?', a: 'Fast keyframe trim me nahi, kyunki kuch re-encode nahi hota. Frame-accurate mode me sirf cut ke aas paas ka thoda hissa re-encode hota hai.' },
      { q: 'Beech ka hissa hatana hai, start-end nahi.', a: 'Do trims karo, pehle wala hissa aur baad wala hissa alag alag nikalo, phir dono ko join karo.' },
    ],
    tips: [
      'Always trim before compressing. There is no reason to spend bitrate on footage you are deleting.',
      'For social platforms, check the maximum duration before trimming so you cut to the right length once.',
      'Preview both cut points. Getting a trim right first time is rare.',
    ],
    related: ['compress-video', 'video-to-gif', 'extract-audio-from-video'],
    target: 'toolhub',
    keywords: ['trim video online', 'cut video free', 'video trimmer', 'crop video length online'],
  },

  {
    slug: 'video-to-gif',
    name: 'Video to GIF',
    cat: 'Video',
    title: 'Video to GIF Online Free – Small, Loopable, Watchable',
    h1: 'Video to GIF without producing a 40 MB monster',
    description: 'Convert video clips to GIF in the browser. Why GIFs get huge, the three settings that control size, and when to use video instead.',
    excerpt: 'GIF is a terrible video format that is universally supported. Here is how to keep one small enough to be useful.',
    what: [
      'GIF is technically a bad way to store moving pictures. It has no modern compression and a 256-colour limit, so a five second clip can balloon past 20 MB. It survives because it plays absolutely everywhere and auto-loops without a player, which makes it the format of choice for documentation, bug reports and chat.',
      'Three settings control the size: **duration**, **frame rate** and **dimensions**. Three seconds at 10 frames per second and 480 pixels wide gives a usable, small GIF. Ten seconds at 30 frames per second at full resolution gives something nobody can load. The converter is in [ToolHub](https://codaiman.com/toolhub).',
    ],
    steps: [
      'Trim the clip to the shortest useful segment first. Duration matters most.',
      'Open the video to GIF converter in [ToolHub](https://codaiman.com/toolhub).',
      'Set the frame rate to 10 to 15. Beyond that you are adding size, not smoothness people notice.',
      'Reduce the width to 480 or 640 pixels unless fine detail matters.',
      'Export and check the size. Above 5 MB, cut the duration further.',
    ],
    specs: [
      ['Colour limit', '256, which is why gradients band'],
      ['Sensible frame rate', '10 to 15 fps'],
      ['Sensible width', '480 to 640 px'],
      ['Sensible duration', 'Under 5 seconds'],
      ['Better alternative', 'MP4, where the destination supports it'],
    ],
    problems: [
      { q: 'GIF ka size 30 MB ho gaya.', a: 'Duration sabse bada factor hai, phir frame rate, phir dimensions. 3 second, 10 fps, 480 px wide se shuru karo.' },
      { q: 'GIF me colours banded aur ganda dikh raha hai.', a: 'GIF sirf 256 colours support karta hai, isliye gradients aur skin tones me banding aati hai. Ye format ki limitation hai. Smooth gradients ke liye MP4 use karo.' },
      { q: 'GIF ki jagah video kab use karein?', a: 'Jahan bhi destination video support kare. MP4 same length ke liye kaafi chhota aur better quality deta hai. GIF sirf universal support aur auto-loop ke liye hai.' },
    ],
    tips: [
      'Duration is the biggest lever. A three second GIF is a fraction of a ten second one.',
      'For UI demos, GIF at 10 fps and 640 pixels wide is plenty. Screen content does not need 30 fps.',
      'GIFs are common in design handoff and documentation. CodeAiMan\'s [UI/UX team](https://codaiman.com/services/ui-ux-design) uses the same approach for prototype walkthroughs.',
    ],
    related: ['trim-video', 'compress-video', 'compress-image'],
    target: 'uiux',
    keywords: ['video to gif', 'mp4 to gif converter', 'make gif from video free', 'gif maker online'],
  },

  {
    slug: 'extract-audio-from-video',
    name: 'Extract Audio from Video',
    cat: 'Video',
    title: 'Extract Audio from Video Online Free – MP3 or Lossless',
    h1: 'Pulling the audio track out of a video file',
    description: 'Extract audio from video in the browser as MP3 or WAV. When you can copy the track without re-encoding, and when you cannot.',
    excerpt: 'Sometimes you can copy the audio track out untouched. That is always better than re-encoding it.',
    what: [
      'Extracting audio comes up for lectures, interviews, recorded meetings and any case where you want to listen rather than watch, or where you need the audio for editing. It is also how you make a 200 MB video into a 5 MB file you can actually send.',
      'The distinction worth knowing: if the video\'s audio is already in a format you want, the tool can **copy** the track out with zero quality loss. If you need a different format, it has to re-encode, which loses a little. Copying is always better when it is available. [ToolHub](https://codaiman.com/toolhub) handles both paths.',
    ],
    steps: [
      'Open the audio extractor in [ToolHub](https://codaiman.com/toolhub) and upload the video.',
      'Choose your output. MP3 for listening and sharing, WAV if the audio is going into editing.',
      'If the tool offers a copy or passthrough option and the source format suits you, take it. No quality loss.',
      'For MP3, 128 kbps is fine for speech and 192 kbps or higher for music.',
      'Check the duration of the output matches the video. A short file means the extraction stopped early.',
    ],
    specs: [
      ['Output formats', 'MP3, WAV, AAC, M4A'],
      ['Copy mode', 'Lossless, when the source format is kept'],
      ['Speech bitrate', '128 kbps is plenty'],
      ['Music bitrate', '192 kbps or higher'],
      ['Typical size drop', 'Very large. Video is almost all picture data'],
    ],
    problems: [
      { q: 'Extract kiya audio ki quality kharab hai.', a: 'Bitrate kam set hua hoga, ya double re-encoding hui hai. Agar copy ya passthrough option hai to wo use karo, usme quality loss zero hota hai.' },
      { q: 'Audio file video se chhoti duration ki hai.', a: 'Extraction beech me ruk gayi, usually corrupt ya incomplete video file ki wajah se. Video pehle poori play karke check karo.' },
      { q: 'MP3 ya WAV, kaunsa chuno?', a: 'Sirf sunna hai to MP3, wo kaafi chhota hota hai. Editing me daalna hai to WAV, kyunki wo lossless hai aur baar baar edit karne par degrade nahi hota.' },
    ],
    tips: [
      'Take the copy or passthrough option whenever it is offered. Re-encoding for no reason is pure loss.',
      'Speech does not need high bitrate. 128 kbps mono is smaller and sounds the same.',
      'For lectures, extracting audio makes a 200 MB file into something you can actually keep on a phone.',
    ],
    related: ['convert-audio-to-mp3', 'trim-audio', 'compress-video'],
    target: 'toolhub',
    keywords: ['extract audio from video', 'video to mp3', 'mp4 to mp3 converter free', 'get audio from video'],
  },

  {
    slug: 'convert-audio-to-mp3',
    name: 'Convert Audio to MP3',
    cat: 'Audio',
    title: 'Convert Audio to MP3 Online Free – Bitrate Explained',
    h1: 'Converting audio to MP3 without wasting space or quality',
    description: 'Convert WAV, M4A, FLAC and OGG to MP3 in the browser. Choosing bitrate for speech versus music, and why mono halves the size.',
    excerpt: 'The only decision is bitrate, and speech needs far less of it than people give it.',
    what: [
      'MP3 remains the audio format that plays on everything, including car stereos and old hardware that has never heard of anything newer. Converting to it is what you do when compatibility matters more than fidelity.',
      'The setting that matters is bitrate. For **speech**, 128 kbps is transparent and even 96 kbps mono is perfectly clear, which halves the file again. For **music**, 192 kbps is a reasonable floor and 320 kbps is as good as MP3 gets. Using 320 kbps for a recorded meeting wastes three quarters of the file for nothing. The converter is in [ToolHub](https://codaiman.com/toolhub).',
    ],
    steps: [
      'Open the audio converter in [ToolHub](https://codaiman.com/toolhub) and upload your file.',
      'Choose MP3 as the output.',
      'Set bitrate by content: 128 kbps for speech, 192 kbps or higher for music.',
      'Switch to mono for speech recordings. It halves the size with no meaningful loss.',
      'Listen to a few seconds before you commit to the whole batch.',
    ],
    specs: [
      ['Common inputs', 'WAV, M4A, AAC, FLAC, OGG'],
      ['Speech bitrate', '96 to 128 kbps, mono'],
      ['Music bitrate', '192 to 320 kbps, stereo'],
      ['Compatibility', 'Effectively universal'],
      ['Lossless input', 'Converting FLAC to MP3 is one-way'],
    ],
    problems: [
      { q: 'MP3 me convert karne ke baad awaaz flat lag rahi hai.', a: 'Bitrate bahut kam hai. Music ke liye 192 kbps se neeche na jao. Speech ke liye 128 kbps theek hai.' },
      { q: 'File size kam karna hai, kya karun?', a: 'Speech ho to mono par switch karo, size seedha aadha ho jaayega aur farq nahi sunai dega. Music me mono mat karo.' },
      { q: 'FLAC se MP3 kiya, wapas FLAC kar sakte hain?', a: 'Technically kar sakte ho lekin faayda nahi. Jo data MP3 ne discard kiya wo wapas nahi aata. FLAC original rakho.' },
    ],
    tips: [
      'Mono for speech is the single easiest audio saving there is.',
      'Keep lossless originals for anything you will edit. Convert to MP3 only for distribution.',
      'Voice-based products live and die on audio handling. [Fluenzo](https://codaiman.com/fluenzo) uses speech analysis for English pronunciation, which needs clean input for exactly this reason.',
    ],
    related: ['extract-audio-from-video', 'trim-audio', 'merge-audio'],
    target: 'toolhub',
    keywords: ['convert audio to mp3', 'wav to mp3 converter', 'm4a to mp3 online free', 'flac to mp3'],
  },

  {
    slug: 'trim-audio',
    name: 'Trim Audio',
    cat: 'Audio',
    title: 'Trim Audio Online Free – Cut Clips Precisely',
    h1: 'Trimming audio: precise cuts without the clicks',
    description: 'Trim audio files in the browser. Cutting on silence to avoid clicks, fading edges, and extracting a clip from a long recording.',
    excerpt: 'Cut in silence, not mid-word, and add a short fade. That is the difference between a clean clip and an amateur one.',
    what: [
      'Trimming audio is straightforward with one craft detail that separates a clean result from an obviously amateur one. If you cut in the middle of a waveform rather than at a quiet point, you create an abrupt jump in the signal, and that jump is audible as a click or pop at the edge.',
      'Two fixes: cut during silence or a natural pause, and add a very short fade in and out, a few milliseconds, which smooths the transition inaudibly. Do both and your clip sounds intentional. The trimmer is in the [ToolHub](https://codaiman.com/toolhub) audio section.',
    ],
    steps: [
      'Open the audio trimmer in [ToolHub](https://codaiman.com/toolhub) and load the file.',
      'Find your start and end points on the waveform. Look for the quiet gaps.',
      'Move each cut to the nearest pause rather than cutting mid-word.',
      'Add a short fade in and fade out if the tool offers it.',
      'Listen to both edges specifically. That is where problems live.',
    ],
    specs: [
      ['Formats', 'MP3, WAV, M4A, AAC'],
      ['Quality loss', 'None when trimming WAV; minimal re-encode for MP3'],
      ['Cut placement', 'Aim for silence or a natural pause'],
      ['Fades', 'A few milliseconds is enough'],
      ['Multiple segments', 'Trim separately, then join'],
    ],
    problems: [
      { q: 'Clip ke shuru me click ki awaaz aa rahi hai.', a: 'Cut waveform ke beech me laga hai. Cut ko nearest pause par move karo, aur ek chhota fade in add karo. Dono karne se click gayab ho jaayega.' },
      { q: 'Beech ka hissa nikalna hai.', a: 'Do trims karo, pehla aur doosra hissa alag nikalo, phir join karo. Ek hi step me beech ka hissa nahi nikal sakte.' },
      { q: 'MP3 trim karne se quality girti hai?', a: 'Bahut thodi, kyunki MP3 me cut ke aas paas re-encoding hoti hai. WAV me bilkul nahi girti. Zyada editing karni hai to WAV me kaam karo.' },
    ],
    tips: [
      'Cut in silence. This one habit fixes most audio edge problems.',
      'A few milliseconds of fade is invisible to the listener and removes every click.',
      'Work in WAV if you will make several edits, then convert to MP3 at the end.',
    ],
    related: ['convert-audio-to-mp3', 'merge-audio', 'extract-audio-from-video'],
    target: 'fluenzo',
    keywords: ['trim audio online', 'cut mp3 online free', 'audio trimmer', 'crop audio file'],
  },

  {
    slug: 'merge-audio',
    name: 'Merge Audio',
    cat: 'Audio',
    title: 'Merge Audio Files Online Free – Join Clips Without Gaps',
    h1: 'Joining audio files so the seams do not show',
    description: 'Merge multiple audio files into one in the browser. Matching formats and levels, avoiding gaps, and keeping the join inaudible.',
    excerpt: 'Mismatched levels are what make a merged file sound stitched together. Formats matter less than volume.',
    what: [
      'Joining audio files is common for podcast segments, recorded lessons split across takes, and voice notes you want as one recording. The mechanical part is easy. Making it not sound obviously joined takes one extra consideration.',
      'That consideration is **level matching**. If one file was recorded louder than the next, the listener hears a jump at the seam, and that jump is far more noticeable than any format difference. Normalise the files to a similar level before merging, or the join announces itself. The merge tool is in [ToolHub](https://codaiman.com/toolhub).',
    ],
    steps: [
      'Convert all files to the same format and sample rate first. Mixed inputs cause avoidable problems.',
      'Check the levels. If one recording is noticeably louder, normalise before merging.',
      'Open the audio merge tool in [ToolHub](https://codaiman.com/toolhub) and add the files.',
      'Set the order deliberately. The tool follows your arrangement, not filename order.',
      'Listen to each join specifically. Those are the only places a merge can fail.',
    ],
    specs: [
      ['Inputs', 'MP3, WAV, M4A, AAC'],
      ['Best practice', 'Same format and sample rate for all inputs'],
      ['Main pitfall', 'Mismatched volume between files'],
      ['Order', 'Manual, set before export'],
      ['Gaps', 'Trim silence from the edges first'],
    ],
    problems: [
      { q: 'Join par volume jump kar raha hai.', a: 'Files different levels par record hui hain. Merge se pehle normalise karo. Ye format mismatch se zyada noticeable problem hai.' },
      { q: 'Clips ke beech me lambi silence aa gayi.', a: 'Har file ke edges par pehle se silence tha. Merge se pehle har clip ko trim karo, phir join karo.' },
      { q: 'Different formats merge kar sakte hain?', a: 'Tool handle kar lega lekin pehle sab ek format aur sample rate me convert karna better hai. Mixed inputs se avoidable problems aate hain.' },
    ],
    tips: [
      'Normalise levels first. It is the difference between a clean merge and an obvious one.',
      'Trim each clip before joining, so you control the gaps instead of inheriting them.',
      'Work in WAV through the whole edit, then export MP3 once at the end.',
    ],
    related: ['trim-audio', 'convert-audio-to-mp3', 'extract-audio-from-video'],
    target: 'toolhub',
    keywords: ['merge audio online', 'join mp3 files free', 'combine audio files', 'audio joiner online'],
  },

  {
    slug: 'word-character-counter',
    name: 'Word & Character Counter',
    cat: 'Text',
    title: 'Word and Character Counter Online Free – With SEO Limits',
    h1: 'Counting words and characters against the limits that matter',
    description: 'Count words, characters, sentences and paragraphs in the browser. The character limits for meta titles, descriptions and social posts.',
    excerpt: 'Useful mainly because so many things have hard character limits. Here are the ones worth memorising.',
    what: [
      'A word counter sounds too simple to need a page, until you notice how many hard limits you write against: meta titles, meta descriptions, social posts, form fields, SMS. Going over does not produce a warning, it produces silent truncation, usually mid-word and usually somewhere visible.',
      'The limits worth knowing: meta titles are truncated in search results around 60 characters, meta descriptions around 155 to 160, and an SMS segment is 160. These are the numbers behind most "why does my listing look cut off" questions. The counter is in the [ToolHub](https://codaiman.com/toolhub) text section.',
    ],
    steps: [
      'Open the word counter in [ToolHub](https://codaiman.com/toolhub).',
      'Paste your text. Counts update as you type.',
      'Check characters, not just words, if you are writing against a limit. Limits are almost always in characters.',
      'For meta text, aim slightly under the limit rather than exactly at it.',
      'Watch the character count including spaces, since that is what most limits measure.',
    ],
    specs: [
      ['Counts', 'Words, characters with and without spaces, sentences, paragraphs'],
      ['Meta title limit', 'Around 60 characters'],
      ['Meta description limit', 'Around 155 to 160 characters'],
      ['SMS segment', '160 characters'],
      ['Privacy', 'Runs in the browser; text is not uploaded'],
    ],
    problems: [
      { q: 'Google search result me mera title kat kar dikh raha hai.', a: 'Around 60 characters se zyada hai. Google pixel width par truncate karta hai, isliye thoda under rakhna safe hai.' },
      { q: 'Meta description kitni lambi honi chahiye?', a: '155 se 160 characters ke andar. Isse zyada likhoge to search results me "..." aa jaayega aur aakhir ka message dikhega hi nahi.' },
      { q: 'Word count aur character count me kaunsa dekhna chahiye?', a: 'Almost sabhi hard limits characters me hote hain, words me nahi. Limit ke against likh rahe ho to characters dekho, spaces included.' },
    ],
    tips: [
      'Write the meta description to the limit deliberately rather than letting it be truncated.',
      'Aim a few characters under any limit. Different platforms measure slightly differently.',
      'Getting these limits right across a whole site is tedious by hand. [CodeAiMan\'s technical SEO checklist](https://codaiman.com/blog/technical-seo-checklist-2026) covers what else to audit, and [siteIQ](https://codaiman.com/siteiq) flags truncated titles automatically.',
    ],
    related: ['change-text-case', 'remove-duplicate-lines', 'json-formatter'],
    target: 'seo',
    keywords: ['word counter online', 'character count tool', 'meta description length', 'count words free'],
  },

  {
    slug: 'change-text-case',
    name: 'Change Text Case',
    cat: 'Text',
    title: 'Change Text Case Online Free – Upper, Lower, Title, Sentence',
    h1: 'Changing text case, including the naming conventions developers need',
    description: 'Convert text between upper, lower, title, sentence, camelCase, snake_case and kebab-case in the browser. Fixing caps-lock accidents.',
    excerpt: 'Fixes caps-lock accidents, and converts between the naming conventions code actually uses.',
    what: [
      'The everyday use is rescuing text typed with caps lock on, or received from a system that shouts everything in capitals. Retyping a paragraph because of that is a waste of a few minutes that a case converter removes entirely.',
      'The version developers care about is different: converting between naming conventions. **camelCase** for JavaScript variables, **snake_case** for Python and database columns, **kebab-case** for URLs and CSS classes, **PascalCase** for component names. Converting a list of field names between these by hand is exactly the sort of tedium that produces typos. Both live in [ToolHub](https://codaiman.com/toolhub).',
    ],
    steps: [
      'Open the case converter in [ToolHub](https://codaiman.com/toolhub) and paste your text.',
      'Pick the target case. Sentence case is usually what you want for rescued prose.',
      'For code identifiers, pick camelCase, snake_case, kebab-case or PascalCase as appropriate.',
      'Check proper nouns afterwards. Automatic sentence case will lowercase names it does not recognise.',
      'Copy the result out.',
    ],
    specs: [
      ['Prose cases', 'UPPER, lower, Title Case, Sentence case'],
      ['Code cases', 'camelCase, snake_case, kebab-case, PascalCase'],
      ['Proper nouns', 'Need a manual check after conversion'],
      ['Batch', 'Works on a whole list at once'],
      ['Privacy', 'Runs in the browser'],
    ],
    problems: [
      { q: 'Sentence case karne par naam bhi lowercase ho gaye.', a: 'Converter ko nahi pata kaunsa word proper noun hai. Conversion ke baad naam, jagah aur brand names manually theek karo.' },
      { q: 'Title case me chhote words bhi capital ho gaye.', a: 'Strict title case me "of", "and", "the" lowercase rehte hain. Agar tool sab capital kar raha hai to wo simple title case use kar raha hai, aakhir me manually adjust karo.' },
      { q: 'camelCase aur PascalCase me farq kya hai?', a: 'camelCase pehla letter lowercase rakhta hai (userName), PascalCase capital (UserName). Variables ke liye camelCase, components aur classes ke liye PascalCase.' },
    ],
    tips: [
      'Sentence case is the right target for rescuing all-caps prose, not Title Case.',
      'For code, pick one convention per language and stick to it. Mixed conventions in one codebase cause real bugs.',
      'Naming conventions are one of the first things taught properly on [Code With Squad](https://codaiman.com/cws), because they cause more confusion for beginners than any syntax.',
    ],
    related: ['word-character-counter', 'remove-duplicate-lines', 'json-formatter'],
    target: 'cws',
    keywords: ['change text case', 'uppercase to lowercase converter', 'title case tool', 'camelcase converter online'],
  },

  {
    slug: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    cat: 'Text',
    title: 'Remove Duplicate Lines Online Free – Clean Lists Fast',
    h1: 'Removing duplicate lines from a list',
    description: 'Strip duplicate lines from text in the browser. Case sensitivity, whitespace traps, and cleaning email or URL lists properly.',
    excerpt: 'The traps are invisible: trailing spaces and case differences mean identical-looking lines are not duplicates.',
    what: [
      'Deduplicating a list of lines is one of those tasks that is trivial in principle and annoying in practice, because two lines that look identical often are not. A trailing space, a different capitalisation, or a stray tab makes them distinct as far as any tool is concerned.',
      'So the useful options are **case sensitivity** and **trim whitespace**. With whitespace trimming on and case sensitivity off, "user@example.com " and "User@Example.com" correctly collapse into one entry. Without them, you keep both and wonder why. The tool is in the [ToolHub](https://codaiman.com/toolhub) text section.',
    ],
    steps: [
      'Open the duplicate line remover in [ToolHub](https://codaiman.com/toolhub) and paste your list.',
      'Turn on whitespace trimming. This alone catches most missed duplicates.',
      'Turn off case sensitivity for emails, URLs and names, where case does not signify.',
      'Keep case sensitivity on for anything where case matters, like codes, hashes or identifiers.',
      'Compare the before and after line counts to confirm it did what you expected.',
    ],
    specs: [
      ['Case sensitivity', 'Toggle. Off for emails and URLs'],
      ['Whitespace trim', 'Recommended on'],
      ['Order', 'Usually preserves first occurrence'],
      ['Empty lines', 'Can be removed at the same time'],
      ['Privacy', 'Runs in the browser; nothing uploaded'],
    ],
    problems: [
      { q: 'Duplicates dikh rahe hain lekin tool nahi hata raha.', a: 'Trailing spaces ya invisible tabs honge. Whitespace trimming on karo, ye almost hamesha wahi problem hoti hai.' },
      { q: 'Emails duplicate hain lekin case alag hai.', a: 'Case sensitivity off karo. Email addresses me case signify nahi karta, isliye "User@x.com" aur "user@x.com" same entry hain.' },
      { q: 'Codes wali list me case sensitivity rakhni chahiye?', a: 'Haan. Codes, hashes aur identifiers me case matter karta hai. Wahan case sensitivity on rakho warna genuinely different entries merge ho jaayengi.' },
    ],
    tips: [
      'Whitespace trimming on, case sensitivity off, is the right default for contact lists.',
      'Check the line count before and after. A suspiciously large drop usually means case sensitivity was off when it should not have been.',
      'For anything larger than a few thousand lines, this belongs in a script rather than a browser tool. CodeAiMan\'s [web development team](https://codaiman.com/services/web-development) builds that kind of data cleanup into the app itself.',
    ],
    related: ['word-character-counter', 'change-text-case', 'json-formatter'],
    target: 'web',
    keywords: ['remove duplicate lines', 'dedupe list online', 'delete duplicate text', 'unique lines tool'],
  },

  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    cat: 'Developer',
    title: 'JSON Formatter and Validator Online Free – Find the Error',
    h1: 'Formatting and validating JSON, and finding the one bad character',
    description: 'Format, validate and minify JSON in the browser. The four errors that cause almost every parse failure, and how to locate them.',
    excerpt: 'Four mistakes cause almost every JSON parse error. Trailing commas top the list.',
    what: [
      'A JSON formatter does two jobs. It pretty-prints a minified blob so a human can read it, and it validates the syntax so you find out exactly where the structure is broken instead of staring at an API error.',
      'Almost every JSON parse failure is one of four things: a **trailing comma** after the last item, **single quotes** instead of double, an **unquoted key**, or an unescaped character inside a string. JSON is stricter than JavaScript object literals, which is why code that looks fine to a developer fails to parse. The formatter is in the [ToolHub](https://codaiman.com/toolhub) developer section.',
    ],
    steps: [
      'Open the JSON formatter in [ToolHub](https://codaiman.com/toolhub) and paste your JSON.',
      'Format it. If it is invalid, you get an error position instead.',
      'Go to the reported position, then look at the character just before it. The real problem is usually one character earlier than the error points to.',
      'Check the four usual suspects: trailing comma, single quotes, unquoted key, unescaped character.',
      'Minify before sending JSON over the wire, and format when you need to read it.',
    ],
    specs: [
      ['Functions', 'Format, validate, minify'],
      ['Error reporting', 'Position of the parse failure'],
      ['Top cause of failure', 'Trailing comma'],
      ['Comments', 'Not valid in JSON, despite what editors allow'],
      ['Privacy', 'Runs in the browser; nothing sent to a server'],
    ],
    problems: [
      { q: 'JSON valid lagta hai lekin parse nahi ho raha.', a: 'Chaar cheezein check karo: last item ke baad trailing comma, single quotes ki jagah double, unquoted keys, aur strings ke andar unescaped characters. Trailing comma sabse common hai.' },
      { q: 'Error position par kuch galat nahi dikh raha.', a: 'Parser ko galti wahan pata chalti hai jahan structure tut jaata hai, jo asli galti ke thoda aage hota hai. Reported position se ek character peeche dekho.' },
      { q: 'JSON me comments daal sakte hain?', a: 'Nahi. JSON comments support nahi karta, chahe aapka editor complain na kare. Comments hatao warna parse fail hoga.' },
    ],
    tips: [
      'Trailing comma first. Check it before anything else, it is the most common cause by a wide margin.',
      'Minify for transport, format for reading. Sending pretty-printed JSON wastes bandwidth on every request.',
      'A browser-based formatter keeps the data local, which matters when the JSON contains anything sensitive.',
    ],
    related: ['base64-encoder-decoder', 'url-encoder-decoder', 'hash-generator'],
    target: 'web',
    keywords: ['json formatter', 'json validator online', 'format json free', 'json beautifier', 'minify json'],
  },

  {
    slug: 'base64-encoder-decoder',
    name: 'Base64 Encoder / Decoder',
    cat: 'Developer',
    title: 'Base64 Encoder and Decoder Online Free – And What It Is Not',
    h1: 'Base64: what it is for, and why it is not encryption',
    description: 'Encode and decode Base64 in the browser. What Base64 actually does, the 33 percent size cost, and why it provides no security.',
    excerpt: 'Base64 is encoding, not encryption. Anyone can decode it instantly, which matters more than most people realise.',
    what: [
      'Base64 converts binary data into plain text using 64 safe characters, so binary can travel through channels that only handle text: email attachments, JSON fields, data URIs in CSS, JWT payloads. That is its entire purpose.',
      'The critical thing to be clear about: **Base64 is not encryption and provides no security whatsoever.** Anyone can decode it in one second with no key. If you Base64 a password thinking it is hidden, it is not hidden. The other cost worth knowing is size: Base64 output is about 33 percent larger than the input, which is why embedding large images as data URIs makes pages heavier, not lighter. The tool is in [ToolHub](https://codaiman.com/toolhub).',
    ],
    steps: [
      'Open the Base64 tool in [ToolHub](https://codaiman.com/toolhub).',
      'Pick encode or decode.',
      'Paste your input. For decoding, include the whole string; truncated Base64 fails.',
      'If decoding produces garbage, check whether it is URL-safe Base64, which swaps two characters.',
      'Copy the result. Never treat encoded output as protected.',
    ],
    specs: [
      ['Purpose', 'Carrying binary data through text-only channels'],
      ['Security', 'None. It is encoding, not encryption'],
      ['Size overhead', 'About 33 percent larger than the input'],
      ['URL-safe variant', 'Replaces + and / with - and _'],
      ['Common uses', 'Data URIs, JWT payloads, email attachments'],
    ],
    problems: [
      { q: 'Base64 se data secure ho jaata hai?', a: 'Bilkul nahi. Ye encoding hai, encryption nahi. Koi bhi ek second me decode kar sakta hai, bina kisi key ke. Passwords ya secrets ke liye kabhi use na karo.' },
      { q: 'Decode karne par garbage aa raha hai.', a: 'Do reasons: string truncated hai, ya wo URL-safe Base64 hai jisme + aur / ki jagah - aur _ hote hain. URL-safe mode try karo.' },
      { q: 'Image ko Base64 me embed karna chahiye?', a: 'Chhoti icons ke liye theek hai. Badi images ke liye nahi, kyunki Base64 size 33 percent badha deta hai aur wo bytes cache bhi nahi hote.' },
    ],
    tips: [
      'Say it once more: Base64 is not security. Use TLS and real encryption for anything that needs protecting.',
      'Only embed tiny assets as data URIs. Anything larger loads faster as a separate cached file.',
      'JWT payloads are Base64, which is why you should never put secrets in them. This is standard curriculum material on [CWS](https://codaiman.com/cws).',
    ],
    related: ['url-encoder-decoder', 'json-formatter', 'hash-generator'],
    target: 'cws',
    keywords: ['base64 encode online', 'base64 decoder free', 'base64 converter', 'decode base64 string'],
  },

  {
    slug: 'url-encoder-decoder',
    name: 'URL Encoder / Decoder',
    cat: 'Developer',
    title: 'URL Encoder and Decoder Online Free – Fix Broken Links',
    h1: 'URL encoding: why links break and how to fix them',
    description: 'Encode and decode URLs and query parameters in the browser. Which characters must be escaped, and the double-encoding trap.',
    excerpt: 'Spaces, ampersands and question marks break URLs. Encoding fixes it, and double-encoding breaks it differently.',
    what: [
      'URLs can only safely contain a limited set of characters. Anything else, a space, an ampersand, a question mark, a hash, or any non-Latin character, has to be percent-encoded or it changes the meaning of the URL. An unescaped ampersand inside a parameter value silently starts a new parameter, which is why the value arrives truncated.',
      'The trap on the other side is **double encoding**. If you encode a URL that is already encoded, `%20` becomes `%2520` and the link breaks in a way that is confusing to diagnose because it looks encoded. Decode first, check, then encode once. The tool is in [ToolHub](https://codaiman.com/toolhub).',
    ],
    steps: [
      'Open the URL encoder in [ToolHub](https://codaiman.com/toolhub).',
      'If you are debugging an existing URL, decode it first to see what it actually contains.',
      'Encode parameter **values** individually, not the whole URL. Encoding the whole thing escapes the slashes and colons too.',
      'Watch for `%25` in the output, which signals the input was already encoded.',
      'Test the final URL in a browser before shipping it.',
    ],
    specs: [
      ['Must be encoded', 'Spaces, &, ?, #, =, +, and non-Latin characters'],
      ['Space becomes', '%20, or + in form-encoded data'],
      ['Double-encoding tell', '%2520 appearing where %20 should be'],
      ['Scope', 'Encode parameter values, not the whole URL'],
      ['Privacy', 'Runs in the browser'],
    ],
    problems: [
      { q: 'Parameter ki value aadhi hi pahunch rahi hai.', a: 'Value ke andar unescaped ampersand hai, jo naya parameter shuru kar deta hai. Us value ko encode karo.' },
      { q: 'URL me %2520 dikh raha hai.', a: 'Double encoding hui hai. %25 khud "%" ka encoded form hai. Ek baar decode karo, phir sirf ek baar encode karo.' },
      { q: 'Poori URL encode karni chahiye?', a: 'Nahi. Sirf parameter values encode karo. Poori URL encode karne se slashes aur colons bhi escape ho jaate hain aur URL kaam karna band kar deti hai.' },
    ],
    tips: [
      'Encode values, not whole URLs. This single rule prevents most URL bugs.',
      '`%2520` in a URL always means double encoding. It is a reliable diagnostic.',
      'Broken URLs and redirect chains are a real SEO cost, not just a bug. [CodeAiMan\'s technical SEO checklist](https://codaiman.com/blog/technical-seo-checklist-2026) covers what to look for.',
    ],
    related: ['base64-encoder-decoder', 'json-formatter', 'qr-code-generator'],
    target: 'seochecklist',
    keywords: ['url encoder', 'url decoder online', 'percent encoding tool', 'encode url parameters free'],
  },

  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    cat: 'Developer',
    title: 'Hash Generator Online Free – MD5, SHA-1, SHA-256',
    h1: 'Generating hashes, and knowing which ones are still safe to use',
    description: 'Generate MD5, SHA-1 and SHA-256 hashes in the browser. What hashes are for, why MD5 is broken, and why passwords need something else.',
    excerpt: 'MD5 is fine for checking a download. It is completely unfit for passwords, and so is SHA-256 on its own.',
    what: [
      'A hash turns any input into a fixed-length fingerprint. The same input always gives the same hash, and you cannot work backwards from the hash to the input. That makes hashes useful for verifying that a file downloaded intact, or that two things are identical without comparing them byte by byte.',
      'Where people go wrong is passwords. **MD5 and SHA-1 are cryptographically broken** and should not be used for anything security-related. But even SHA-256 is wrong for passwords, because it is fast, and fast is exactly what an attacker wants when guessing billions of candidates. Passwords need a deliberately slow algorithm like bcrypt or Argon2. The hash generator is in [ToolHub](https://codaiman.com/toolhub).',
    ],
    steps: [
      'Open the hash generator in [ToolHub](https://codaiman.com/toolhub).',
      'Pick the algorithm. SHA-256 for anything current; MD5 only for non-security checksums.',
      'Paste your input or upload the file.',
      'For verifying a download, compare against the published hash character by character, or paste both and diff them.',
      'Never use this to hash passwords for storage. Use bcrypt or Argon2 in your application.',
    ],
    specs: [
      ['Algorithms', 'MD5, SHA-1, SHA-256, SHA-512'],
      ['MD5 and SHA-1', 'Broken. Checksums only, never security'],
      ['SHA-256', 'Current standard for integrity'],
      ['Passwords', 'Need bcrypt or Argon2, not a plain hash'],
      ['Reversible', 'No, by design'],
    ],
    problems: [
      { q: 'MD5 use kar sakte hain?', a: 'Sirf non-security checksums ke liye, jaise file download verify karna. Cryptographically MD5 broken hai, security ke liye kabhi use na karo.' },
      { q: 'Password SHA-256 se hash kar dun?', a: 'Nahi. SHA-256 fast hai, aur attacker ko fast hi chahiye taaki wo arbon guesses kar sake. Passwords ke liye bcrypt ya Argon2 use karo, jo jaan-boojh kar slow hain.' },
      { q: 'Download ka hash publish kiye hash se match nahi kar raha.', a: 'Ya download corrupt hai, ya file badli gayi hai. Dobara download karo. Do baar mismatch aaye to us source se install mat karo.' },
    ],
    tips: [
      'SHA-256 for integrity, bcrypt or Argon2 for passwords. Two different jobs, two different tools.',
      'Verifying a download hash is the one security habit that costs ten seconds and actually works.',
      'Getting this wrong in production is a real incident. CodeAiMan\'s [cloud and DevOps work](https://codaiman.com/services/cloud-devops) covers secrets handling and deployment hardening.',
    ],
    related: ['base64-encoder-decoder', 'json-formatter', 'url-encoder-decoder'],
    target: 'cloud',
    keywords: ['hash generator online', 'md5 generator', 'sha256 hash tool', 'generate checksum free'],
  },

  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    cat: 'Developer',
    title: 'QR Code Generator Online Free – Scannable at Real Sizes',
    h1: 'Generating QR codes that actually scan',
    description: 'Generate QR codes in the browser for URLs, text, WiFi and contacts. Error correction, minimum print size, and why long URLs scan badly.',
    excerpt: 'Most unscannable QR codes are either printed too small or encode a URL that is far too long.',
    what: [
      'QR codes are straightforward to generate and easy to make unusable. The two failure modes are almost always the same: the code is printed too small, or the data encoded is too long, which forces a dense pattern that phone cameras struggle to resolve.',
      'Practical numbers: a printed QR code should be at least 2 by 2 centimetres for close scanning, and considerably larger for anything scanned from a distance. Shorten long URLs before encoding rather than after printing. Also set **error correction** to at least medium, which lets the code still scan when part of it is scuffed, covered or poorly printed. The generator is in [ToolHub](https://codaiman.com/toolhub).',
    ],
    steps: [
      'Shorten your URL first if it is long. Fewer characters means a less dense, more reliable code.',
      'Open the QR generator in [ToolHub](https://codaiman.com/toolhub) and enter your data.',
      'Set error correction to medium or high, especially for anything printed.',
      'Export as PNG or SVG. Use SVG for print, since it scales without blurring.',
      'Test by scanning the final printed or on-screen version with more than one phone.',
    ],
    specs: [
      ['Data types', 'URL, plain text, WiFi credentials, contact card'],
      ['Minimum print size', '2 by 2 cm for close scanning'],
      ['Error correction', 'Medium or high for print'],
      ['Best print format', 'SVG, which scales cleanly'],
      ['Contrast', 'Dark code on a light background. Do not invert'],
    ],
    problems: [
      { q: 'QR code scan nahi ho raha.', a: 'Do common reasons: print size chhota hai (2x2 cm se kam), ya encoded URL bahut lambi hai jisse pattern dense ho gaya. URL shorten karo aur bada print karo.' },
      { q: 'Print me QR blurry aa raha hai.', a: 'PNG ko stretch kiya gaya hai. Print ke liye SVG export karo, wo kisi bhi size par sharp rehta hai.' },
      { q: 'Coloured ya inverted QR code chalega?', a: 'Risky hai. Dark code on light background sabse reliable hai. Inverted ya low-contrast codes kuch scanners par fail karte hain.' },
    ],
    tips: [
      'Test with at least two different phones before printing a thousand copies.',
      'SVG for print, PNG for screen. A stretched PNG is the most common printing mistake.',
      'For anything customer-facing, a QR code should point at a page that works properly on a phone. CodeAiMan\'s [mobile app and web team](https://codaiman.com/services/mobile-app-development) builds for that constraint first.',
    ],
    related: ['url-encoder-decoder', 'base64-encoder-decoder', 'compress-image'],
    target: 'mobile',
    keywords: ['qr code generator', 'create qr code free', 'qr code maker online', 'wifi qr code generator'],
  },
];
