import type { Tool } from './tool-types';

/** Batch 1: PDF and image tools. */
export const tools1: Tool[] = [
  {
    slug: 'merge-pdf',
    name: 'Merge PDF',
    cat: 'PDF',
    title: 'Merge PDF Files Online Free – Combine PDFs in Order (2026)',
    h1: 'How to merge PDF files online without installing anything',
    description: 'Combine multiple PDF files into one document in your browser. Page order, bookmarks, file size limits and the mistakes that corrupt a merged PDF.',
    excerpt: 'Combine several PDFs into one, control the page order, and avoid the two mistakes that produce a broken output file.',
    what: [
      'People usually end up needing this because a portal will only take one upload: a scanned ID, a signed form, three supporting pages, all wanted as a single file instead of six separate attachments.',
      'The good part is that merging does not touch the actual content. It rewrites the document structure and copies the existing page objects across, so nothing gets re-encoded and nothing loses quality in the process. Run it through [ToolHub](https://codaiman.com/toolhub) and it all happens in your browser tab, so the files are not sitting on someone else\'s server once you are done.',
    ],
    steps: [
      'Head to the PDF merge tool on [ToolHub](https://codaiman.com/toolhub).',
      'Add every file you want in the output. Do not add them one at a time and merge repeatedly, that nests the structure and bloats the file.',
      'Drag the thumbnails into the order you actually want. The tool follows your order, not the order you uploaded in.',
      'Check the total page count before you export. A page count that does not match the sum of your inputs means one file failed to parse.',
      'Export, then open the result and scroll to the last page. That is the fastest check that nothing was truncated.',
    ],
    specs: [
      ['Input formats', 'PDF only. Convert images first if you need them in the output'],
      ['Quality loss', 'None. Pages are copied, not re-encoded'],
      ['Order control', 'Manual drag-and-drop before export'],
      ['Password-protected files', 'Must be unlocked first'],
      ['Typical limit', 'Governed by your device memory, not a server quota'],
    ],
    problems: [
      { q: 'Merged PDF ka order galat aa gaya, kya karein?', a: 'Merge tool upload order follow nahi karta, wo aapka arrange kiya hua order follow karta hai. Export se pehle thumbnails ko drag karke sahi sequence me lagao, phir export karo.' },
      { q: 'Ek file merge nahi ho rahi. Reason?', a: 'Do common reasons: file password-protected hai, ya wo actually PDF nahi hai (extension .pdf hai lekin content kuch aur). Pehle unlock karo, ya file dobara properly export karo.' },
      { q: 'Merged file ka size bahut bada ho gaya. Fix?', a: 'Merge se size add hota hai, kam nahi hota. Baad me compress karo. Aur ek galti se bacho: baar baar do-do file merge karne se structure nest hoti hai aur size unnecessarily badhta hai.' },
    ],
    tips: [
      'Merge first, compress second. Compressing each input separately then merging gives a worse result than one compression pass at the end.',
      'If the output has to be under a portal size limit, check the limit before you start, not after.',
      'Scanned pages dominate the file size. If yours is too big, the scans are the problem, not the merge.',
    ],
    related: ['split-pdf', 'compress-pdf', 'jpg-to-pdf'],
    target: 'toolhub',
    keywords: ['merge pdf online', 'combine pdf free', 'pdf merge tool', 'join pdf files', 'merge pdf without watermark'],
  },

  {
    slug: 'split-pdf',
    name: 'Split PDF',
    cat: 'PDF',
    title: 'Split PDF Online Free – Extract Pages or Ranges (2026)',
    h1: 'Splitting a PDF: extract pages, ranges, or break it into single files',
    description: 'Split a PDF in the browser: pull out one page, extract a range, or break a document into individual files. Page numbering traps explained.',
    excerpt: 'Pull out a single page, a range, or break a document apart entirely. Plus the off-by-one trap that catches almost everyone.',
    what: [
      'This is the mirror image of merging, and the reason people reach for it is usually narrower: a 60-page document, but the other person only needs pages 12 to 14. Sending the whole thing is lazy, and sometimes a privacy problem too, since the other 57 pages might have things the recipient has no business seeing.',
      'Under the hood it works the same way merging does: page objects get copied, not re-encoded, so what comes out the other end is pixel-identical to the source. You will find it in [ToolHub](https://codaiman.com/toolhub)\'s PDF section, right next to merge and compress.',
    ],
    steps: [
      'Load your file into the PDF split tool on [ToolHub](https://codaiman.com/toolhub).',
      'Decide which mode you need: extract a range, extract specific pages, or split every page into its own file.',
      'Enter the range using the page numbers shown in the viewer, not the numbers printed on the pages. Those often differ because of cover pages.',
      'Preview the selection. Most split failures are actually correct splits of the wrong range.',
      'Export. Range splits give one file, per-page splits give a set.',
    ],
    specs: [
      ['Modes', 'Range extract, specific pages, split all'],
      ['Numbering basis', 'Viewer page position, 1-indexed'],
      ['Quality loss', 'None'],
      ['Bookmarks', 'Links pointing outside the extracted range will break'],
      ['Encrypted files', 'Unlock before splitting'],
    ],
    problems: [
      { q: 'Galat pages extract ho gaye. Kya galti hui?', a: 'Almost hamesha printed page number aur actual position ka farq. Cover page ya index ke wajah se document ka page 1 aur printed "page 1" alag hote hain. Viewer ke numbers use karo.' },
      { q: 'Split ke baad internal links kaam nahi kar rahe.', a: 'Ye expected hai. Jo bookmark ya link extracted range ke bahar point karta tha, wo ab kahin nahi jaayega. Content safe hai, sirf navigation tuti hai.' },
      { q: 'Har page ki alag file chahiye, ek ek karke karna padega?', a: 'Nahi. "Split all" mode chuno, wo ek hi pass me har page ki separate file bana deta hai.' },
    ],
    tips: [
      'Splitting is the privacy-safe way to share part of a document. Redacting by covering text is not, because the text is still in the file.',
      'If you only need pages for reading, splitting is better than screenshotting. Screenshots lose selectable text.',
      'Name the output before you send it. "document (1).pdf" tells the recipient nothing.',
    ],
    related: ['merge-pdf', 'pdf-to-jpg', 'compress-pdf'],
    target: 'toolhub',
    keywords: ['split pdf online', 'extract pdf pages', 'pdf splitter free', 'separate pdf pages', 'pdf page extract'],
  },

  {
    slug: 'compress-pdf',
    name: 'Compress PDF',
    cat: 'PDF',
    title: 'Compress PDF Online Free – Reduce Size Without Ruining It',
    h1: 'Compressing a PDF: what actually shrinks, and what you lose',
    description: 'Reduce PDF file size in the browser. What compression actually targets, why scanned documents behave differently, and how to hit an upload limit.',
    excerpt: 'Compression targets images, not text. That one fact explains why some PDFs shrink 90 percent and others barely move.',
    what: [
      'Here is the thing almost no compression tool explains: PDF compression mostly works on the images inside the document. Text is already stored efficiently and there is very little to squeeze out of it. So a 40-page text report might shrink by 5 percent, while a 3-page scanned document can drop by 90 percent.',
      'That single fact tells you whether compression will help before you even try it. If your file is large and mostly text, something else is going on, usually an embedded font set or a heavy vector graphic. If it is large because of scans or photos, compression will earn its keep. [ToolHub](https://codaiman.com/toolhub)\'s compressor gives you a quality slider instead of forcing one fixed preset on you, which matters a lot here.',
    ],
    steps: [
      'Pull up the PDF compressor on [ToolHub](https://codaiman.com/toolhub).',
      'Note your target size first. Portal limits are usually 2 MB, 5 MB or 10 MB, and knowing the number stops you over-compressing.',
      'Start with the medium quality setting rather than maximum compression.',
      'Check the output at 100 percent zoom, specifically any small text inside images. That is where over-compression shows first.',
      'If it is still too large, compress the source images before rebuilding the PDF rather than compressing the PDF twice.',
    ],
    specs: [
      ['What shrinks', 'Embedded images, mostly'],
      ['What does not', 'Text, which is already compressed'],
      ['Typical scan reduction', '60 to 90 percent'],
      ['Typical text-only reduction', '2 to 10 percent'],
      ['Reversible', 'No. Keep the original'],
    ],
    problems: [
      { q: 'Compress karne par size kam hi nahi hua. Kyu?', a: 'Aapki file probably mostly text hai. Text pehle se compressed hota hai, usme nikalne ke liye kuch nahi hota. Bada text-only PDF ka reason usually embedded fonts ya heavy vector graphics hote hain.' },
      { q: 'Compress karne ke baad text blurry ho gaya.', a: 'Matlab wo text actually image ke andar tha, scanned document me. Aggressive compression ne usko degrade kar diya. Original se dobara shuru karo aur medium setting use karo.' },
      { q: 'Do baar compress karna chahiye?', a: 'Nahi. Doosri pass se quality girti hai aur size barely kam hota hai. Agar ek pass kaafi nahi hai to source images ko theek karo, PDF ko nahi.' },
    ],
    tips: [
      'Always keep the original. Compression is lossy and there is no undo.',
      'Scanning at 600 dpi and then compressing is worse than scanning at 200 dpi in the first place.',
      'A file that is large for no visible reason is worth investigating rather than compressing. CodeAiMan\'s [website speed guide](https://codaiman.com/blog/how-to-improve-website-speed) makes the same point about images on web pages.',
    ],
    related: ['merge-pdf', 'compress-image', 'pdf-to-jpg'],
    target: 'speed',
    keywords: ['compress pdf online', 'reduce pdf size', 'pdf compressor free', 'shrink pdf file', 'pdf size reducer'],
  },

  {
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    cat: 'PDF',
    title: 'PDF to Word Converter Online Free – Keep the Formatting',
    h1: 'Converting PDF to Word: what survives and what does not',
    description: 'Convert PDF to editable Word documents in the browser. Why layout breaks, which PDFs convert cleanly, and when OCR is needed instead.',
    excerpt: 'Some PDFs convert perfectly and some come out as garbage. The difference is whether the text is real text or a picture of text.',
    what: [
      'PDF to Word conversion has a reputation for producing a mess, and the reason is structural. PDF describes where marks sit on a page. Word describes a flow of paragraphs. Converting between them means guessing which marks form a paragraph, which form a table, and which are a header. Good converters guess well. Nothing guesses perfectly.',
      'The bigger split is whether your PDF actually contains text or is just a picture of text. A PDF exported straight from Word converts back cleanly, almost every time. A scan of a printed page has no text in it at all, only pixels, so it needs OCR before there is anything to convert. Both routes live in [ToolHub](https://codaiman.com/toolhub)\'s document tools.',
    ],
    steps: [
      'Test first: open the PDF and try to select a sentence with your cursor. If it highlights, you have real text and conversion will work well.',
      'If nothing highlights, it is a scan. Use OCR first, then convert.',
      'Then upload the file to the PDF to Word converter on [ToolHub](https://codaiman.com/toolhub).',
      'Open the result in Word and check tables first. Tables are what break most often.',
      'Fix headings and spacing manually. Expect to spend a few minutes on any document with a complex layout.',
    ],
    specs: [
      ['Output format', 'DOCX'],
      ['Best case', 'PDFs originally exported from Word'],
      ['Worst case', 'Multi-column scanned documents'],
      ['Scans', 'Need OCR first'],
      ['What breaks most', 'Tables, then multi-column layouts, then footnotes'],
    ],
    problems: [
      { q: 'Convert karne par pura layout bigad gaya.', a: 'PDF marks ki position store karta hai, Word paragraphs ka flow. Multi-column ya complex layouts me converter ko guess karna padta hai. Simple single-column documents clean convert hote hain.' },
      { q: 'Word file me text edit hi nahi ho raha, images aa gayi.', a: 'Aapka PDF scanned tha. Usme text nahi, pixels the. Pehle OCR chalao taaki text nikle, phir convert karo.' },
      { q: 'Tables poori tuti hui aayi hain. Koi fix?', a: 'Tables sabse pehle tutte hain kyunki PDF me table ki koi concept nahi hoti, sirf lines aur text hote hain. Chhoti tables manually rebuild karna aksar faster hota hai.' },
    ],
    tips: [
      'If you control the source, keep the original Word file. Converting back is always worse than the original.',
      'The select-a-sentence test takes two seconds and tells you exactly how the conversion will go.',
      'For forms you need filled in, converting to Word is usually the wrong path. Fill the PDF directly.',
    ],
    related: ['word-to-pdf', 'image-to-text-ocr', 'pdf-to-jpg'],
    target: 'toolhub',
    keywords: ['pdf to word', 'pdf to docx converter', 'convert pdf to editable word', 'pdf to word free online'],
  },

  {
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    cat: 'PDF',
    title: 'Word to PDF Converter Online Free – Fonts and Layout Intact',
    h1: 'Word to PDF: the direction that actually works reliably',
    description: 'Convert DOCX to PDF in the browser with fonts and layout preserved. Why this direction is reliable and how to stop font substitution.',
    excerpt: 'This direction is the easy one. Here is why, plus the one thing that still goes wrong: fonts.',
    what: [
      'Word to PDF is the reliable direction. You are going from a flexible format to a fixed one, which means the converter only has to decide where things sit and then freeze them. No guessing required. This is exactly why PDF exists: so a document looks the same everywhere.',
      'The one thing that still trips people up is fonts. If your document uses a font the converter does not have, it swaps in something similar and your line breaks shift as a result. Embedding fonts prevents that, and it is the whole difference between a PDF that looks right only on your machine and one that looks right on everyone\'s. Grab the converter from [ToolHub](https://codaiman.com/toolhub)\'s document tools when you need it.',
    ],
    steps: [
      'Finalise the document in Word first. Editing after conversion means converting again.',
      'Upload your DOCX to the Word to PDF converter on [ToolHub](https://codaiman.com/toolhub).',
      'Convert, then open the PDF and compare page breaks against the original.',
      'If line breaks moved, a font was substituted. Switch to a common font or embed the one you are using.',
      'Check that hyperlinks still work. They usually survive, but headers and footers sometimes lose them.',
    ],
    specs: [
      ['Input', 'DOCX, DOC'],
      ['Layout fidelity', 'High. This is the easy direction'],
      ['Main failure mode', 'Font substitution shifting line breaks'],
      ['Hyperlinks', 'Usually preserved'],
      ['Editable after', 'No, that is the point'],
    ],
    problems: [
      { q: 'PDF me page breaks Word se alag aa gaye.', a: 'Font substitution hua hai. Converter ke paas aapka font nahi tha, usne milta-julta font laga diya, aur line widths badal gayi. Common font use karo ya font embed karo.' },
      { q: 'Links click nahi ho rahe PDF me.', a: 'Body ke links usually survive karte hain. Header aur footer ke links kabhi kabhi lost ho jaate hain. Unhe body me move karo agar zaruri hain.' },
      { q: 'PDF ka size zarurat se zyada bada hai.', a: 'Word ke andar jo images hain wo full resolution me embed ho jaati hain. Word me hi unhe compress karo, ya PDF ko baad me compress karo.' },
    ],
    tips: [
      'Convert last. Every edit after conversion means doing it again.',
      'Send PDFs, not DOCX, when you do not want the layout changed or the file edited.',
      'For anything customer-facing, open the PDF on a phone before sending. That is where layout problems become obvious.',
    ],
    related: ['pdf-to-word', 'compress-pdf', 'jpg-to-pdf'],
    target: 'toolhub',
    keywords: ['word to pdf', 'docx to pdf converter', 'convert word to pdf free', 'word to pdf online'],
  },

  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    cat: 'PDF',
    title: 'PDF to JPG Online Free – Export Pages as Images',
    h1: 'PDF to JPG: exporting pages as images, at the right resolution',
    description: 'Convert PDF pages to JPG or PNG in the browser. Choosing DPI, when to pick PNG instead, and why text goes fuzzy at low settings.',
    excerpt: 'The whole job comes down to one setting: DPI. Pick it wrong and your text is unreadable or your file is enormous.',
    what: [
      'Converting PDF pages to images is what you do when the destination cannot handle a PDF: a social post, a WhatsApp message, a slide, or a form field that only accepts images. It is a one-way trip, because you are turning structured text into pixels.',
      'The only setting that really matters is resolution. At 72 DPI a page comes out small with fuzzy text. At 300 DPI it is crisp, but the file is big. For screen viewing, 150 DPI is usually the sweet spot; for anything that will be printed or zoomed into, go to 300. [ToolHub](https://codaiman.com/toolhub)\'s converter puts that DPI choice right in front of you instead of burying it behind one fixed preset, and that is the difference between a usable tool and a frustrating one.',
    ],
    steps: [
      'Decide where the image is going. Screen viewing needs less resolution than print.',
      'Then open the PDF to JPG tool on [ToolHub](https://codaiman.com/toolhub).',
      'Set DPI: 150 for screen, 300 for print or anything that will be zoomed.',
      'Pick JPG for photos and scans, PNG if the page is mostly text and sharp lines.',
      'Export, then check the smallest text on the page at 100 percent zoom.',
    ],
    specs: [
      ['Output formats', 'JPG, PNG'],
      ['Screen DPI', '150'],
      ['Print DPI', '300'],
      ['Text-heavy pages', 'PNG holds edges better than JPG'],
      ['Reversible', 'No. Text becomes pixels'],
    ],
    problems: [
      { q: 'Image me text blurry hai.', a: 'DPI kam hai. 72 ya 96 par text fuzzy aata hai. 150 se shuru karo, aur zoom karna hai to 300 par jao.' },
      { q: 'File size bahut bada aa raha hai.', a: 'DPI zyada hai ya format galat. 600 DPI screen ke liye waste hai. Aur photos ke liye PNG ki jagah JPG use karo, PNG unme kaafi bada hota hai.' },
      { q: 'Text wale page par JPG me halka halka noise dikh raha hai.', a: 'JPG compression sharp edges ke aas paas artifacts banata hai, aur text pura sharp edges hi hota hai. Text-heavy pages ke liye PNG chuno.' },
    ],
    tips: [
      'JPG for photos, PNG for text and line art. This one rule solves most image format questions.',
      'If you need selectable text at the destination, you want the PDF, not an image of it.',
      'Exporting a page to image and then running OCR on it to get text back is a sign you converted in the wrong direction.',
    ],
    related: ['jpg-to-pdf', 'image-to-text-ocr', 'compress-image'],
    target: 'toolhub',
    keywords: ['pdf to jpg', 'pdf to image converter', 'convert pdf page to png', 'pdf to jpg free'],
  },

  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    cat: 'PDF',
    title: 'JPG to PDF Online Free – Photos and Scans Into One Document',
    h1: 'JPG to PDF: turning photos and scans into one clean document',
    description: 'Combine images into a single PDF in the browser. Page size, orientation, ordering and how to keep phone-camera scans readable.',
    excerpt: 'Mostly used for phone-camera document scans. Here is how to stop them coming out crooked, huge and unreadable.',
    what: [
      'The overwhelmingly common use for this is photographing documents with a phone and needing them as a single PDF, because almost every official portal in India accepts PDF and rejects a folder of JPGs.',
      'The conversion itself is trivial, honestly. What decides the quality of the result happens before you even convert, in how the photos were taken. Flat, evenly lit, shot straight on, cropped to the page edges — that beats any amount of post-processing you could do afterwards. You will find the converter in [ToolHub](https://codaiman.com/toolhub)\'s PDF section, where you set page size and order yourself instead of the tool guessing for you.',
    ],
    steps: [
      'Crop each image to the document edges before you start. This alone fixes most complaints about the output.',
      'Then add all your images at once to the JPG to PDF tool on [ToolHub](https://codaiman.com/toolhub).',
      'Set the order. The tool follows your arrangement, not the filename order.',
      'Choose A4 page size unless you have a specific reason not to. Portals expect it.',
      'Export, then check the file size against whatever limit you need to meet.',
    ],
    specs: [
      ['Input formats', 'JPG, PNG, and common image types'],
      ['Page size', 'A4 recommended, or fit-to-image'],
      ['Order', 'Manual, set before export'],
      ['Typical output size', 'Driven almost entirely by your source photos'],
      ['Multi-page', 'Yes, one image per page'],
    ],
    problems: [
      { q: 'PDF me pages tede aur bade dikh rahe hain.', a: 'Convert karne se pehle images crop karo, document ke edges tak. Camera ka pura frame daalne se page tedha aur border wala aata hai.' },
      { q: 'File size 20 MB ho gaya, portal 2 MB maang raha hai.', a: 'Phone photos 4 se 8 MB ke hote hain. Pehle images compress karo, phir PDF banao. Ulta karne se result kharab aata hai.' },
      { q: 'Portal keh raha hai document unreadable hai.', a: 'Usually lighting ka issue hai, resolution ka nahi. Shadow-free, even light me dobara photo lo. Flash se glare aata hai, wo aur bura hai.' },
    ],
    tips: [
      'Compress the images first, then build the PDF. This order gives a smaller file at better quality.',
      'Natural light near a window beats flash for document photos, every time.',
      'Check the portal size limit before you start, not after three failed uploads.',
    ],
    related: ['compress-image', 'compress-pdf', 'merge-pdf'],
    target: 'toolhub',
    keywords: ['jpg to pdf', 'image to pdf converter', 'photo to pdf', 'jpg to pdf free online', 'scan to pdf'],
  },

  {
    slug: 'rotate-pdf',
    name: 'Rotate PDF',
    cat: 'PDF',
    title: 'Rotate PDF Online Free – Fix Sideways Pages Permanently',
    h1: 'Rotating PDF pages so the fix actually saves',
    description: 'Rotate PDF pages in the browser and save the rotation permanently. Why viewer rotation does not stick and how to fix single pages.',
    excerpt: 'Rotating in your PDF viewer does not save. Here is the difference between viewing rotated and being rotated.',
    what: [
      'Small task, but one genuinely confusing part trips almost everyone up: rotating a page in a PDF viewer usually only changes how you are looking at it. Close the file, reopen it, and the page is sideways again. Nearly everyone hits this once and assumes the tool is broken.',
      'Doing it properly writes the rotation into the document itself, so it stays fixed for whoever opens it next. That distinction matters most when a scanner has produced a document where some pages are upright and others sideways, which is the usual reason anyone lands here. Run it through [ToolHub](https://codaiman.com/toolhub) and the rotation gets written into the file, not just how you happen to be viewing it.',
    ],
    steps: [
      'Load the file into the PDF rotate tool on [ToolHub](https://codaiman.com/toolhub).',
      'Look at the page thumbnails and identify which pages are actually wrong. Often it is only some of them.',
      'Rotate individual pages rather than the whole document, unless every page needs it.',
      'Export the file. This is the step that makes the rotation permanent.',
      'Reopen the exported file to confirm. If it is still sideways, you rotated the view instead of the document.',
    ],
    specs: [
      ['Rotation steps', '90, 180, 270 degrees'],
      ['Per-page control', 'Yes'],
      ['Quality loss', 'None. Rotation is metadata, not re-rendering'],
      ['Permanence', 'Saved into the exported file'],
      ['Common cause', 'Scanner feeding pages in mixed orientation'],
    ],
    problems: [
      { q: 'Rotate karke save kiya lekin phir bhi sideways khul raha hai.', a: 'Aap viewer me rotate kar rahe ho, document me nahi. Viewer rotation sirf display badalta hai. Proper tool se rotate karke export karo.' },
      { q: 'Sirf kuch pages ulte hain, poora document nahi.', a: 'Scanner ne mixed orientation me feed kiya hoga. Thumbnails dekho aur sirf wahi pages rotate karo. Poore document ko rotate karne se sahi pages bhi galat ho jaayenge.' },
      { q: 'Rotate karne se quality girti hai?', a: 'Nahi. Rotation metadata me likhi jaati hai, page dobara render nahi hota. Quality bilkul same rehti hai.' },
    ],
    tips: [
      'Fix rotation before merging. Rotating after a merge means finding the same pages again in a longer document.',
      'If a scanner keeps producing mixed orientations, its duplex setting is usually the cause.',
      'Rotation is free, quality-wise. There is no reason to leave a document sideways.',
    ],
    related: ['merge-pdf', 'split-pdf', 'jpg-to-pdf'],
    target: 'toolhub',
    keywords: ['rotate pdf online', 'rotate pdf pages free', 'fix sideways pdf', 'pdf rotate and save'],
  },

  {
    slug: 'unlock-pdf',
    name: 'Unlock PDF',
    cat: 'PDF',
    title: 'Unlock PDF Online Free – Remove Restrictions You Own',
    h1: 'Unlocking a PDF: the two kinds of protection and what is legitimate',
    description: 'Remove password protection from your own PDFs in the browser. The difference between owner and user passwords, and where the line is.',
    excerpt: 'There are two kinds of PDF lock and they are not the same thing. One you can clear, the other needs the password.',
    what: [
      'PDF protection comes in two forms and confusing them causes most of the frustration here. A **user password** is required to open the file at all: without it there is nothing to work with, and no legitimate tool will get you in. An **owner password** lets anyone open and read the file but blocks printing, copying or editing.',
      'Owner restrictions are the ones people usually need cleared: a bank statement you cannot print, a form you cannot fill in, a document you cannot even copy a reference number out of. Clearing those on a document you are already entitled to use is reasonable, routine stuff. You will find the tool over in [ToolHub](https://codaiman.com/toolhub).',
    ],
    steps: [
      'Check which kind of lock you have. If the file opens without asking for anything, it is an owner restriction.',
      'If it demands a password to open, you need that password. There is no way around that, and that is by design.',
      'Upload the file to the PDF unlock tool on [ToolHub](https://codaiman.com/toolhub).',
      'Remove the restrictions and export a clean copy.',
      'Test what you actually needed: try printing, or copying a line of text.',
    ],
    specs: [
      ['Owner password removal', 'Yes, for files you can already open'],
      ['User password bypass', 'No. Requires the password'],
      ['What restrictions cover', 'Printing, copying, editing, form filling, extraction'],
      ['Output', 'Unrestricted copy. The original is unchanged'],
      ['Quality loss', 'None'],
    ],
    problems: [
      { q: 'File password maang rahi hai open karne ke liye. Bypass ho sakta hai?', a: 'Nahi. Wo user password hai aur encryption uske bina file ko readable nahi banata. Ye by design hai. Password jisne file bheji hai usse maango.' },
      { q: 'File khul jaati hai lekin print nahi hoti. Ye kya hai?', a: 'Owner restriction hai. File encrypted nahi hai, sirf permission flags set hain. Unlock tool se ye clear ho jaata hai.' },
      { q: 'Copy karne par text paste nahi hota.', a: 'Extraction restriction hai, wahi owner password ka part. Unlock karke clean copy export karo, phir copy chalega.' },
    ],
    tips: [
      'Unlock only documents you are entitled to use. Bank statements, your own forms, files you were sent to work with.',
      'If a document is genuinely confidential and you need to share part of it, split out the pages instead of unlocking and forwarding the whole thing.',
      'Keep the locked original. You may need to prove it was unmodified.',
    ],
    related: ['compress-pdf', 'merge-pdf', 'pdf-to-word'],
    target: 'toolhub',
    keywords: ['unlock pdf online', 'remove pdf password', 'pdf permission remover', 'enable pdf printing'],
  },

  {
    slug: 'add-page-numbers-pdf',
    name: 'Add Page Numbers to PDF',
    cat: 'PDF',
    title: 'Add Page Numbers to PDF Online Free – Position and Format',
    h1: 'Adding page numbers to a PDF that already exists',
    description: 'Add page numbers to a finished PDF in the browser. Position, starting number, format options and skipping cover pages.',
    excerpt: 'For documents assembled from several sources, where no single file knows what page it is on.',
    what: [
      'This comes up almost exclusively with assembled documents: a submission built from a form, three annexures and a set of scans, where the pieces came from different places and none of them knows what page it sits on in the final document. Legal filings, tender submissions and academic appendices are the usual suspects.',
      'The options worth caring about are position, starting number, and whether to skip the first page. Skipping the cover matters more than it sounds, since a numbered cover page looks wrong on anything formal, and reviewers do notice. [ToolHub](https://codaiman.com/toolhub)\'s numbering tool covers all three, so you are not stuck with whatever it defaults to.',
    ],
    steps: [
      'Finish assembling the document first. Adding numbers before a merge means renumbering afterwards.',
      'Then open the page numbering tool on [ToolHub](https://codaiman.com/toolhub).',
      'Choose the position. Bottom centre is the safe default; bottom right suits documents that will be bound on the left.',
      'Set the starting number and whether to skip the cover page.',
      'Export and check the first, last and one middle page.',
    ],
    specs: [
      ['Positions', 'Header or footer, left, centre or right'],
      ['Starting number', 'Configurable'],
      ['Skip pages', 'Yes, typically the cover'],
      ['Formats', 'Plain numbers, or "Page X of Y"'],
      ['Order', 'Number after merging, not before'],
    ],
    problems: [
      { q: 'Numbers content ke upar aa rahe hain.', a: 'Position badlo. Jo document scanned pages se bana hai usme margins alag hote hain. Bottom centre usually safest hai.' },
      { q: 'Cover page par bhi number aa gaya.', a: 'Skip-first-page option on karo. Formal submissions me numbered cover galat lagta hai aur reviewers notice karte hain.' },
      { q: 'Numbering 1 se shuru nahi honi chahiye. Ho sakta hai?', a: 'Haan, starting number set kar sakte ho. Ye tab kaam aata hai jab document kisi bade set ka part ho.' },
    ],
    tips: [
      'Merge first, number second. Always.',
      '"Page X of Y" is worth it for anything that gets printed and could lose a sheet.',
      'Check a middle page too. Documents with mixed page sizes sometimes place numbers inconsistently.',
    ],
    related: ['merge-pdf', 'split-pdf', 'rotate-pdf'],
    target: 'toolhub',
    keywords: ['add page numbers to pdf', 'pdf page numbering online', 'number pdf pages free'],
  },

  {
    slug: 'compress-image',
    name: 'Compress Image',
    cat: 'Image',
    title: 'Compress Image Online Free – Smaller Files, Same Look',
    h1: 'Compressing images: how far you can go before anyone notices',
    description: 'Compress JPG and PNG images in the browser. Quality thresholds, what compression artifacts look like, and why this matters for site speed.',
    excerpt: 'Most images can lose 60 to 70 percent of their size with no visible difference. Here is where the line actually is.',
    what: [
      'Of everything on this list, this is the highest-leverage small task there is. A typical phone photo is 4 to 8 MB and looks identical at under 1 MB. That is not a marginal saving. It is the difference between a page that loads in one second and one that takes six, and between an upload that works and one that times out halfway through.',
      'The practical threshold to remember: JPG quality around 80 percent is almost always visually indistinguishable from the original. Drop below 60 percent and artifacts start showing up in smooth gradients, skies and skin tones especially. [ToolHub](https://codaiman.com/toolhub)\'s compressor lets you dial in the level and see exactly what you are getting, rather than applying some hidden preset behind the scenes.',
    ],
    steps: [
      'Fire up the image compressor on [ToolHub](https://codaiman.com/toolhub).',
      'Start at 80 percent quality. This is the sweet spot for almost every photo.',
      'Compare against the original at 100 percent zoom, looking at smooth areas rather than detailed ones. Artifacts appear in gradients first.',
      'Resize as well as compress if the image is larger than it will ever be displayed. A 4000 pixel wide photo in a 800 pixel slot is wasting 80 percent of its bytes.',
      'Export. Keep the original if the image matters.',
    ],
    specs: [
      ['Formats', 'JPG, PNG, WebP'],
      ['Safe quality level', '80 percent for photos'],
      ['Visible artifacts start', 'Below about 60 percent'],
      ['Typical saving', '60 to 80 percent with no visible change'],
      ['Where artifacts show first', 'Skies, skin tones, and other smooth gradients'],
    ],
    problems: [
      { q: 'Compress karne ke baad image me patches dikh rahe hain.', a: 'Quality bahut kam set ki hai. Smooth areas jaise sky ya skin me artifacts pehle dikhte hain. 80 percent par wapas jao, wahan farq nazar nahi aata.' },
      { q: 'PNG compress karne par size kam nahi hua.', a: 'PNG lossless hai, wo photos ke liye bana hi nahi hai. Photo ko JPG ya WebP me convert karo, size dramatically girega.' },
      { q: 'Website slow hai, images compress karna kaafi hai?', a: 'Compression bada hissa hai lekin sirf ek hissa. Dimensions bhi theek karo aur lazy loading lagao. CodaiMan ka website speed guide poori list deta hai.' },
    ],
    tips: [
      'Resize and compress together. Compressing a 4000 pixel image that displays at 800 pixels solves half the problem.',
      'Serve WebP where you can. It beats both JPG and PNG at the same visual quality.',
      'Oversized images are the most common cause of a slow site. [CodeAiMan\'s speed guide](https://codaiman.com/blog/how-to-improve-website-speed) covers the rest, and [siteIQ](https://codaiman.com/siteiq) will find them for you automatically.',
    ],
    related: ['resize-image', 'convert-image-to-webp', 'png-to-jpg'],
    target: 'siteiq',
    keywords: ['compress image online', 'reduce image size', 'image compressor free', 'compress jpg', 'photo size reducer'],
  },

  {
    slug: 'resize-image',
    name: 'Resize Image',
    cat: 'Image',
    title: 'Resize Image Online Free – Exact Pixels Without Distortion',
    h1: 'Resizing images to exact dimensions without stretching them',
    description: 'Resize images in the browser to exact pixel dimensions. Aspect ratio, upscaling limits, and the dimensions common platforms expect.',
    excerpt: 'Resizing down is free and lossless in perceived quality. Resizing up cannot invent detail. Know which you are doing.',
    what: [
      'Resizing and compressing get confused constantly, and they are different operations. Compression keeps the dimensions and reduces the data used to describe them. Resizing changes the dimensions. For web images you almost always want both, in that order: resize to the size it will display at, then compress.',
      'Here is the asymmetry worth knowing: shrinking an image is essentially free, because you are just discarding data you never needed anyway. Making it bigger cannot work as well, because the detail was never there to begin with. Upscale a 300 pixel logo to 1200 pixels and all you get is a blurry 1200 pixel logo. [ToolHub](https://codaiman.com/toolhub) locks the aspect ratio by default for exactly this reason, so you would have to go out of your way to stretch something.',
    ],
    steps: [
      'Find the dimensions you actually need. Check the platform requirement rather than guessing.',
      'Open up the image resizer on [ToolHub](https://codaiman.com/toolhub).',
      'Keep aspect ratio locked unless you specifically want to crop. Unlocking it stretches faces and text.',
      'Enter the target width. Height follows automatically.',
      'Compress afterwards for a second saving on top of the resize.',
    ],
    specs: [
      ['Formats', 'JPG, PNG, WebP and common types'],
      ['Aspect ratio', 'Locked by default'],
      ['Downscaling', 'Effectively lossless in appearance'],
      ['Upscaling', 'Cannot add detail that was not captured'],
      ['Order of operations', 'Resize, then compress'],
    ],
    problems: [
      { q: 'Resize karne par image stretch ho gayi.', a: 'Aspect ratio unlock tha. Width aur height independently badalne se image distort hoti hai. Ratio lock karke sirf width do, height khud adjust ho jaayegi.' },
      { q: 'Chhoti image ko bada kiya to blurry ho gayi.', a: 'Ye upscaling ki limitation hai, tool ki nahi. Jo detail capture nahi hui thi wo add nahi ho sakti. Higher resolution original chahiye.' },
      { q: 'Exact size chahiye lekin aspect ratio match nahi karta.', a: 'Pehle crop karo taaki ratio match ho, phir resize karo. Bas stretch mat karo, wo hamesha bura dikhta hai.' },
    ],
    tips: [
      'Resize to display size, then compress. This combination fixes most image weight problems.',
      'Never upscale for print. Get a higher resolution source instead.',
      'Keep one high resolution master and generate sizes from it, rather than resizing a resized copy.',
    ],
    related: ['compress-image', 'crop-image', 'convert-image-to-webp'],
    target: 'toolhub',
    keywords: ['resize image online', 'image resizer free', 'change image dimensions', 'resize photo pixels'],
  },

  {
    slug: 'convert-image-to-webp',
    name: 'Convert Image to WebP',
    cat: 'Image',
    title: 'Convert Image to WebP Online Free – Smaller Than JPG and PNG',
    h1: 'Converting images to WebP, and when not to',
    description: 'Convert JPG and PNG to WebP in the browser. Real size savings, browser support in 2026, transparency handling and when to keep the original format.',
    excerpt: 'WebP beats JPG and PNG at the same visual quality. Support is no longer the issue it was, but there are still two cases to avoid it.',
    what: [
      'WebP is the format that should be your default for web images now. At the same visual quality it is typically 25 to 35 percent smaller than JPG, and considerably smaller than PNG for anything photographic. It also supports transparency, which historically forced people into PNG and its much larger files.',
      'Browser support stopped being a real objection years ago. Two cases still make a case for keeping the original: images users will download and open in older desktop software, and images headed into print workflows, where JPG or TIFF is still what is expected. For everything that lives on a web page, WebP wins, and you will find the converter in [ToolHub](https://codaiman.com/toolhub).',
    ],
    steps: [
      'Add your images to the WebP converter on [ToolHub](https://codaiman.com/toolhub).',
      'Set quality around 80 percent. WebP holds up better than JPG at the same number.',
      'Convert, then compare the file sizes. The saving over JPG should be visible immediately.',
      'Check any image that had transparency. WebP keeps it, but confirm rather than assume.',
      'On a website, serve WebP with a fallback if you support very old clients.',
    ],
    specs: [
      ['Input', 'JPG, PNG, and common formats'],
      ['Saving over JPG', '25 to 35 percent at equal quality'],
      ['Saving over PNG', 'Often much larger, for photographic content'],
      ['Transparency', 'Supported'],
      ['Keep original for', 'Print workflows and user-downloaded files'],
    ],
    problems: [
      { q: 'WebP kis kaam ka hai, JPG se better kaise?', a: 'Same visual quality par WebP 25 se 35 percent chhota hota hai, aur transparency bhi support karta hai. Web images ke liye ye default hona chahiye.' },
      { q: 'Client WebP file open nahi kar pa raha.', a: 'Purana desktop software ho sakta hai. Jo files users download karenge unke liye JPG rakho, aur website par WebP serve karo. Dono ka use case alag hai.' },
      { q: 'Transparent PNG ko WebP me convert kiya, transparency gayi?', a: 'Nahi jaani chahiye, WebP transparency support karta hai. Agar gayi hai to conversion setting galat thi. Result ko dark background par check karo.' },
    ],
    tips: [
      'Make WebP the default for web images and keep JPG only where something outside the browser will open the file.',
      'Combine with resizing. Format conversion and correct dimensions together are what make pages fast.',
      'Run [siteIQ](https://codaiman.com/siteiq) on a site to find which images are still costing you load time.',
    ],
    related: ['compress-image', 'png-to-jpg', 'resize-image'],
    target: 'siteiq',
    keywords: ['convert to webp', 'jpg to webp converter', 'png to webp online', 'webp converter free'],
  },

  {
    slug: 'png-to-jpg',
    name: 'PNG to JPG',
    cat: 'Image',
    title: 'PNG to JPG Online Free – When to Convert and When Not To',
    h1: 'PNG to JPG: a big win for photos, a mistake for graphics',
    description: 'Convert PNG to JPG in the browser. Why photos shrink dramatically, what happens to transparency, and which images should stay PNG.',
    excerpt: 'A PNG photo converted to JPG can lose 80 percent of its size. A PNG logo converted to JPG just looks worse.',
    what: [
      'PNG and JPG are built for different content and using the wrong one is the most common image mistake there is. PNG is lossless and holds sharp edges perfectly, which makes it right for logos, screenshots, diagrams and anything with text. JPG is lossy and excellent at photographs, where the eye does not notice the discarded data.',
      'Convert a photograph from PNG to JPG and you get a real win, often 80 percent smaller with no visible difference. Convert a logo or a screenshot to JPG and you have made a mistake, because JPG puts visible noise around sharp edges. One more thing worth knowing: **JPG has no transparency.** Anything transparent turns into a solid colour, usually white or black. The converter lives in [ToolHub](https://codaiman.com/toolhub) when you need it.',
    ],
    steps: [
      'Look at the image and decide what it is. Photograph, or graphic with sharp edges and text?',
      'If it is a photograph, head to the PNG to JPG converter on [ToolHub](https://codaiman.com/toolhub).',
      'Check whether it has transparency. If it does, decide what background colour you want, because you are getting one.',
      'Convert at around 85 percent quality and compare the file sizes.',
      'If it is a logo, screenshot or diagram, stop. Keep the PNG, or convert to WebP instead.',
    ],
    specs: [
      ['Best for', 'Photographs stored as PNG'],
      ['Wrong for', 'Logos, screenshots, diagrams, anything with text'],
      ['Transparency', 'Lost. Becomes a solid colour'],
      ['Typical photo saving', 'Up to 80 percent'],
      ['Better alternative', 'WebP, which handles both cases'],
    ],
    problems: [
      { q: 'Logo JPG me convert kiya, edges ke around gandagi aa gayi.', a: 'JPG sharp edges ke aas paas artifacts banata hai, aur logo pura sharp edges hi hota hai. Logo ke liye PNG rakho ya WebP use karo.' },
      { q: 'Transparent background white ho gaya.', a: 'JPG me transparency support hi nahi hai, isliye ye expected hai. Transparency chahiye to PNG ya WebP use karo.' },
      { q: 'Photo PNG me 5 MB thi, JPG me 600 KB. Quality kahan gayi?', a: 'Kahin nahi gayi jo aapko dikhe. PNG photographs ke liye extremely inefficient hai. Ye conversion sabse zyada worth-it wala hai.' },
    ],
    tips: [
      'The rule: photos as JPG or WebP, graphics and text as PNG or WebP.',
      'Screenshots should stay PNG. JPG makes UI text look dirty.',
      'WebP sidesteps the whole decision, since it handles photos and transparency both.',
    ],
    related: ['convert-image-to-webp', 'compress-image', 'crop-image'],
    target: 'toolhub',
    keywords: ['png to jpg', 'convert png to jpeg', 'png to jpg converter free', 'png to jpg online'],
  },

  {
    slug: 'crop-image',
    name: 'Crop Image',
    cat: 'Image',
    title: 'Crop Image Online Free – Exact Ratios for Every Platform',
    h1: 'Cropping images to the ratios platforms actually want',
    description: 'Crop images in the browser to exact aspect ratios. Platform requirements, why centre-cropping cuts heads off, and cropping before resizing.',
    excerpt: 'Cropping is how you hit a required aspect ratio without stretching. Here are the ratios that actually matter.',
    what: [
      'Cropping and resizing get lumped together but solve different problems, and you often need both. Resizing changes how big an image is. Cropping changes what is actually in the frame, and with it, the aspect ratio. When a platform demands a square image and yours is a wide photo, cropping is the only correct answer. Stretching it is not, no matter how tempting the shortcut looks.',
      'Better to crop it yourself than let a platform do it automatically, because automatic crops take the centre, and a photo\'s subject is very often not sitting dead centre. That is exactly why profile pictures end up cropped through someone\'s forehead. [ToolHub](https://codaiman.com/toolhub) gives you ratio presets plus manual control, so you decide what stays in frame.',
    ],
    steps: [
      'Find the required aspect ratio. Square, 4:5, 16:9 and 1.91:1 cover most platforms.',
      'Then open the crop tool on [ToolHub](https://codaiman.com/toolhub).',
      'Select the ratio preset first, then position the frame. Doing it the other way round means redoing it.',
      'Position around the subject, not the centre of the image.',
      'Crop first, then resize, then compress. That order avoids compounding quality loss.',
    ],
    specs: [
      ['Common ratios', '1:1, 4:5, 16:9, 1.91:1, 9:16'],
      ['Manual crop', 'Yes, free selection'],
      ['Quality loss', 'None from the crop itself'],
      ['Order', 'Crop, then resize, then compress'],
      ['Reversible', 'No. Cropped pixels are gone'],
    ],
    problems: [
      { q: 'Platform ne mera image crop kar diya aur subject kat gaya.', a: 'Automatic crops centre se hote hain, aur photo ka subject aksar centre me nahi hota. Upload se pehle khud sahi ratio me crop karo.' },
      { q: 'Square chahiye lekin photo wide hai. Stretch kar dun?', a: 'Bilkul nahi. Stretch karne se faces distort hote hain aur turant dikh jaata hai. Crop karo, wahi correct answer hai.' },
      { q: 'Crop karne se quality girti hai?', a: 'Crop se nahi. Pixels bas hat jaate hain. Quality tab girti hai jab aap crop ke baad chhoti image ko upscale karte ho.' },
    ],
    tips: [
      'Set the ratio before you position the frame, not after.',
      'Crop before resizing. Resizing then cropping wastes the resize.',
      'Keep the uncropped original. You will need a different ratio eventually.',
    ],
    related: ['resize-image', 'compress-image', 'png-to-jpg'],
    target: 'uiux',
    keywords: ['crop image online', 'image cropper free', 'crop photo to square', 'aspect ratio crop tool'],
  },

  {
    slug: 'image-to-text-ocr',
    name: 'Image to Text (OCR)',
    cat: 'Image',
    title: 'Image to Text OCR Online Free – Extract Text From Photos',
    h1: 'OCR: pulling text out of images and scans',
    description: 'Extract text from images and scanned documents with OCR in the browser. What affects accuracy, handling Hindi and English, and where OCR fails.',
    excerpt: 'OCR accuracy depends almost entirely on the input image. Here is what to fix before you blame the tool.',
    what: [
      'OCR reads text out of pixels. It is what turns a photographed page into something you can search, copy and edit, and it is the missing step whenever a PDF to Word conversion produces nothing but images.',
      'Accuracy is decided by the input far more than by the software behind it. Straight, evenly lit, in-focus, high-contrast text reads almost perfectly. Skewed, shadowed, low-contrast or handwritten text does not, and there is not much a tool can do about that. Handwriting especially is a different and much harder problem, and general OCR handles it poorly no matter what any tool claims. You will find the OCR tool tucked into [ToolHub](https://codaiman.com/toolhub)\'s image section.',
    ],
    steps: [
      'Improve the image before you run OCR. This has more effect than any setting.',
      'Crop to the text area, straighten it, and make sure the contrast is strong.',
      'Then upload it to the OCR tool on [ToolHub](https://codaiman.com/toolhub).',
      'Set the language. Getting this wrong is a common cause of garbled output, particularly when mixing Hindi and English.',
      'Proofread the result. Always. OCR confuses similar characters and a number read wrong is worse than no number.',
    ],
    specs: [
      ['Input', 'JPG, PNG, and scanned pages'],
      ['Best accuracy', 'Printed text, straight, well lit, high contrast'],
      ['Poor accuracy', 'Handwriting, low contrast, heavy skew'],
      ['Language setting', 'Matters. Set it before running'],
      ['Output', 'Plain text for copying or editing'],
    ],
    problems: [
      { q: 'OCR ka output bilkul galat aa raha hai.', a: 'Pehle input theek karo, tool ko blame karne se pehle. Crop karo, straighten karo, contrast badhao. Aur language setting check karo, galat language garbled output deti hai.' },
      { q: 'Handwriting read nahi ho rahi.', a: 'General OCR handwriting par kaam nahi karta, chahe koi bhi tool kuch bhi dawa kare. Ye ek alag aur kaafi mushkil problem hai.' },
      { q: 'Numbers galat aa rahe hain. Kya karein?', a: 'OCR similar characters confuse karta hai: 0 aur O, 1 aur l, 5 aur S. Numbers hamesha manually verify karo. Galat number no number se zyada khatarnak hai.' },
    ],
    tips: [
      'Shoot documents in even natural light. Flash creates glare that destroys OCR accuracy.',
      'If a PDF gives you no selectable text, OCR is the step you are missing.',
      'Always proofread numbers, dates and reference codes. Those are where OCR errors do real damage.',
    ],
    related: ['pdf-to-word', 'pdf-to-jpg', 'jpg-to-pdf'],
    target: 'home',
    keywords: ['image to text', 'ocr online free', 'extract text from image', 'photo to text converter', 'scanned pdf to text'],
  },
];
